// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv1_output_address0,
        conv1_output_ce0,
        conv1_output_q0,
        conv1_output_address1,
        conv1_output_ce1,
        conv1_output_q1,
        conv1_output_address2,
        conv1_output_ce2,
        conv1_output_q2,
        conv1_output_address3,
        conv1_output_ce3,
        conv1_output_q3,
        pool1_output_address0,
        pool1_output_ce0,
        pool1_output_we0,
        pool1_output_d0,
        grp_fu_1410_p_din0,
        grp_fu_1410_p_din1,
        grp_fu_1410_p_opcode,
        grp_fu_1410_p_dout0,
        grp_fu_1410_p_ce,
        grp_fu_1414_p_din0,
        grp_fu_1414_p_din1,
        grp_fu_1414_p_opcode,
        grp_fu_1414_p_dout0,
        grp_fu_1414_p_ce,
        grp_fu_1418_p_din0,
        grp_fu_1418_p_din1,
        grp_fu_1418_p_opcode,
        grp_fu_1418_p_dout0,
        grp_fu_1418_p_ce,
        grp_fu_1422_p_din0,
        grp_fu_1422_p_din1,
        grp_fu_1422_p_opcode,
        grp_fu_1422_p_dout0,
        grp_fu_1422_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] conv1_output_address0;
output   conv1_output_ce0;
input  [31:0] conv1_output_q0;
output  [12:0] conv1_output_address1;
output   conv1_output_ce1;
input  [31:0] conv1_output_q1;
output  [12:0] conv1_output_address2;
output   conv1_output_ce2;
input  [31:0] conv1_output_q2;
output  [12:0] conv1_output_address3;
output   conv1_output_ce3;
input  [31:0] conv1_output_q3;
output  [10:0] pool1_output_address0;
output   pool1_output_ce0;
output   pool1_output_we0;
output  [31:0] pool1_output_d0;
output  [31:0] grp_fu_1410_p_din0;
output  [31:0] grp_fu_1410_p_din1;
output  [4:0] grp_fu_1410_p_opcode;
input  [0:0] grp_fu_1410_p_dout0;
output   grp_fu_1410_p_ce;
output  [31:0] grp_fu_1414_p_din0;
output  [31:0] grp_fu_1414_p_din1;
output  [4:0] grp_fu_1414_p_opcode;
input  [0:0] grp_fu_1414_p_dout0;
output   grp_fu_1414_p_ce;
output  [31:0] grp_fu_1418_p_din0;
output  [31:0] grp_fu_1418_p_din1;
output  [4:0] grp_fu_1418_p_opcode;
input  [0:0] grp_fu_1418_p_dout0;
output   grp_fu_1418_p_ce;
output  [31:0] grp_fu_1422_p_din0;
output  [31:0] grp_fu_1422_p_din1;
output  [4:0] grp_fu_1422_p_opcode;
input  [0:0] grp_fu_1422_p_dout0;
output   grp_fu_1422_p_ce;

reg ap_idle;
reg conv1_output_ce0;
reg conv1_output_ce1;
reg conv1_output_ce2;
reg conv1_output_ce3;
reg pool1_output_ce0;
reg pool1_output_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln91_fu_277_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] output_row_reg_1283;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] channel_2_reg_1288;
wire   [8:0] empty_39_fu_267_p2;
reg   [8:0] empty_39_reg_1294;
wire   [7:0] empty_40_fu_273_p1;
reg   [7:0] empty_40_reg_1300;
reg   [0:0] icmp_ln91_reg_1305;
wire   [0:0] icmp_ln93_fu_295_p2;
reg   [0:0] icmp_ln93_reg_1309;
wire   [2:0] add_ln91_fu_309_p2;
reg   [2:0] add_ln91_reg_1317;
wire   [8:0] p_mid142_fu_339_p2;
reg   [8:0] p_mid142_reg_1323;
wire   [7:0] empty_47_fu_353_p1;
reg   [7:0] empty_47_reg_1329;
wire   [0:0] and_ln91_fu_369_p2;
reg   [0:0] and_ln91_reg_1334;
wire   [3:0] add_ln93_fu_383_p2;
reg   [3:0] add_ln93_reg_1341;
wire   [3:0] select_ln93_fu_395_p3;
reg   [3:0] select_ln93_reg_1346;
wire   [8:0] p_mid122_fu_415_p2;
reg   [8:0] p_mid122_reg_1352;
wire   [7:0] empty_50_fu_421_p1;
reg   [7:0] empty_50_reg_1358;
wire   [10:0] add_ln114_fu_926_p2;
reg   [10:0] add_ln114_reg_1383;
reg   [10:0] add_ln114_reg_1383_pp0_iter2_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter3_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter4_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter5_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter6_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter7_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter8_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter9_reg;
reg   [10:0] add_ln114_reg_1383_pp0_iter10_reg;
reg   [31:0] conv1_output_load_reg_1388;
reg   [31:0] conv1_output_load_reg_1388_pp0_iter3_reg;
reg   [31:0] conv1_output_load_1_reg_1395;
reg   [31:0] conv1_output_load_1_reg_1395_pp0_iter3_reg;
reg   [31:0] conv1_output_load_1_reg_1395_pp0_iter4_reg;
reg   [31:0] conv1_output_load_1_reg_1395_pp0_iter5_reg;
reg   [31:0] conv1_output_load_2_reg_1402;
reg   [31:0] conv1_output_load_2_reg_1402_pp0_iter3_reg;
reg   [31:0] conv1_output_load_2_reg_1402_pp0_iter4_reg;
reg   [31:0] conv1_output_load_2_reg_1402_pp0_iter5_reg;
reg   [31:0] conv1_output_load_2_reg_1402_pp0_iter6_reg;
reg   [31:0] conv1_output_load_2_reg_1402_pp0_iter7_reg;
reg   [31:0] conv1_output_load_3_reg_1409;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter3_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter4_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter5_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter6_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter7_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter8_reg;
reg   [31:0] conv1_output_load_3_reg_1409_pp0_iter9_reg;
wire   [31:0] select_ln107_fu_973_p3;
reg   [31:0] select_ln107_reg_1416;
reg   [31:0] select_ln107_reg_1416_pp0_iter5_reg;
wire   [31:0] select_ln107_1_fu_1062_p3;
reg   [31:0] select_ln107_1_reg_1423;
reg   [31:0] select_ln107_1_reg_1423_pp0_iter7_reg;
wire   [31:0] select_ln107_2_fu_1150_p3;
reg   [31:0] select_ln107_2_reg_1430;
reg   [31:0] select_ln107_2_reg_1430_pp0_iter9_reg;
wire   [31:0] select_ln107_3_fu_1238_p3;
reg   [31:0] select_ln107_3_reg_1437;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln106_fu_888_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln106_1_fu_899_p1;
wire   [63:0] zext_ln106_2_fu_910_p1;
wire   [63:0] zext_ln106_3_fu_921_p1;
wire   [63:0] zext_ln115_fu_1244_p1;
reg   [3:0] output_col_fu_92;
wire   [3:0] add_ln95_fu_433_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_output_col_load;
reg   [3:0] output_row_1_fu_96;
wire   [3:0] select_ln93_4_fu_425_p3;
reg   [3:0] ap_sig_allocacmp_output_row;
reg   [7:0] indvar_flatten30_fu_100;
wire   [7:0] select_ln93_5_fu_445_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten30_load;
reg   [2:0] channel_fu_104;
wire   [2:0] select_ln91_6_fu_375_p3;
reg   [2:0] ap_sig_allocacmp_channel_2;
reg   [10:0] indvar_flatten98_fu_108;
wire   [10:0] add_ln91_1_fu_283_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten98_load;
wire   [7:0] p_shl9_fu_225_p3;
wire   [4:0] p_shl4_fu_237_p3;
wire   [8:0] p_shl9_cast_fu_233_p1;
wire   [8:0] p_shl10_cast_fu_245_p1;
wire   [4:0] tmp_1_fu_255_p3;
wire   [8:0] p_cast20_fu_263_p1;
wire   [8:0] empty_fu_249_p2;
wire   [7:0] p_shl9_mid1_fu_315_p3;
wire   [4:0] p_shl10_mid1_fu_327_p3;
wire   [8:0] p_shl9_cast_mid1_fu_323_p1;
wire   [8:0] p_shl10_cast_mid1_fu_335_p1;
wire   [0:0] icmp_ln95_fu_363_p2;
wire   [0:0] xor_ln91_fu_357_p2;
wire   [3:0] select_ln91_fu_301_p3;
wire   [0:0] or_ln93_fu_389_p2;
wire   [4:0] p_mid_fu_403_p3;
wire   [8:0] p_cast20_mid1_fu_411_p1;
wire   [8:0] select_ln91_1_fu_345_p3;
wire   [7:0] add_ln93_2_fu_439_p2;
wire   [6:0] p_shl7_fu_478_p3;
wire   [3:0] p_shl8_fu_489_p3;
wire   [7:0] p_shl7_cast_fu_485_p1;
wire   [7:0] p_shl8_cast_fu_496_p1;
wire   [7:0] zext_ln93_fu_506_p1;
wire   [7:0] empty_35_fu_500_p2;
wire   [7:0] empty_36_fu_509_p2;
wire   [6:0] empty_37_fu_515_p1;
wire   [8:0] p_shl6_fu_527_p3;
wire   [10:0] p_shl5_fu_519_p3;
wire  signed [10:0] p_shl12_cast_fu_535_p1;
wire   [10:0] p_shl2_fu_552_p3;
wire   [12:0] p_shl_fu_545_p3;
wire  signed [12:0] p_shl14_0_cast_fu_559_p1;
wire   [8:0] empty_42_fu_569_p2;
wire   [7:0] empty_43_fu_574_p1;
wire   [10:0] p_shl14_1_fu_586_p3;
wire   [12:0] p_shl13_1_fu_578_p3;
wire  signed [12:0] p_shl14_1_cast_fu_594_p1;
wire   [6:0] p_shl7_mid1_fu_604_p3;
wire   [3:0] p_shl8_mid1_fu_615_p3;
wire   [7:0] p_shl7_cast_mid1_fu_611_p1;
wire   [7:0] p_shl8_cast_mid1_fu_622_p1;
wire   [7:0] p_mid144_fu_626_p2;
wire   [6:0] empty_46_fu_639_p1;
wire   [8:0] p_shl12_mid_fu_651_p3;
wire   [10:0] p_shl11_mid_fu_643_p3;
wire  signed [10:0] p_shl12_cast_mid164_fu_659_p1;
wire   [10:0] p_mid166_fu_663_p2;
wire   [10:0] empty_38_fu_539_p2;
wire   [10:0] p_shl14_0_mid_fu_683_p3;
wire   [12:0] p_shl13_0_mid_fu_676_p3;
wire  signed [12:0] p_shl14_0_cast_mid178_fu_690_p1;
wire   [12:0] p_mid180_fu_694_p2;
wire   [12:0] empty_41_fu_563_p2;
wire   [8:0] p_mid182_fu_707_p2;
wire   [7:0] empty_48_fu_712_p1;
wire   [10:0] p_shl14_1_mid_fu_724_p3;
wire   [12:0] p_shl13_1_mid_fu_716_p3;
wire  signed [12:0] p_shl14_1_cast_mid192_fu_732_p1;
wire   [12:0] p_mid194_fu_736_p2;
wire   [12:0] empty_44_fu_598_p2;
wire   [7:0] zext_ln93_1_fu_749_p1;
wire   [7:0] select_ln91_2_fu_632_p3;
wire   [7:0] p_mid118_fu_752_p2;
wire   [6:0] empty_49_fu_758_p1;
wire   [8:0] p_shl12_mid1_fu_770_p3;
wire   [10:0] p_shl11_mid1_fu_762_p3;
wire  signed [10:0] p_shl12_cast_mid1_fu_778_p1;
wire   [10:0] p_mid120_fu_782_p2;
wire   [10:0] select_ln91_3_fu_669_p3;
wire   [10:0] p_shl14_0_mid1_fu_802_p3;
wire   [12:0] p_shl13_0_mid1_fu_795_p3;
wire  signed [12:0] p_shl14_0_cast_mid1_fu_809_p1;
wire   [12:0] p_mid124_fu_813_p2;
wire   [12:0] select_ln91_4_fu_700_p3;
wire   [8:0] p_mid126_fu_826_p2;
wire   [7:0] empty_51_fu_831_p1;
wire   [10:0] p_shl14_1_mid1_fu_843_p3;
wire   [12:0] p_shl13_1_mid1_fu_835_p3;
wire  signed [12:0] p_shl14_1_cast_mid1_fu_851_p1;
wire   [12:0] p_mid128_fu_855_p2;
wire   [12:0] select_ln91_5_fu_742_p3;
wire   [4:0] tmp_16_fu_871_p3;
wire   [12:0] select_ln93_2_fu_819_p3;
wire   [12:0] zext_ln105_fu_878_p1;
wire   [12:0] add_ln105_fu_882_p2;
wire   [12:0] or_ln105_fu_893_p2;
wire   [12:0] select_ln93_3_fu_861_p3;
wire   [12:0] add_ln105_1_fu_904_p2;
wire   [12:0] or_ln105_1_fu_915_p2;
wire   [10:0] output_col_cast35_fu_868_p1;
wire   [10:0] select_ln93_1_fu_788_p3;
wire   [31:0] bitcast_ln107_fu_932_p1;
wire   [7:0] tmp_6_fu_935_p4;
wire   [22:0] trunc_ln107_fu_945_p1;
wire   [0:0] icmp_ln107_1_fu_955_p2;
wire   [0:0] icmp_ln107_fu_949_p2;
wire   [0:0] or_ln107_fu_961_p2;
wire   [0:0] and_ln107_fu_967_p2;
wire   [31:0] bitcast_ln107_1_fu_980_p1;
wire   [31:0] bitcast_ln107_2_fu_997_p1;
wire   [7:0] tmp_8_fu_983_p4;
wire   [22:0] trunc_ln107_7_fu_993_p1;
wire   [0:0] icmp_ln107_3_fu_1020_p2;
wire   [0:0] icmp_ln107_2_fu_1014_p2;
wire   [7:0] tmp_9_fu_1000_p4;
wire   [22:0] trunc_ln107_8_fu_1010_p1;
wire   [0:0] icmp_ln107_5_fu_1038_p2;
wire   [0:0] icmp_ln107_4_fu_1032_p2;
wire   [0:0] or_ln107_1_fu_1026_p2;
wire   [0:0] or_ln107_2_fu_1044_p2;
wire   [0:0] and_ln107_1_fu_1050_p2;
wire   [0:0] and_ln107_2_fu_1056_p2;
wire   [31:0] bitcast_ln107_3_fu_1068_p1;
wire   [31:0] bitcast_ln107_4_fu_1085_p1;
wire   [7:0] tmp_10_fu_1071_p4;
wire   [22:0] trunc_ln107_9_fu_1081_p1;
wire   [0:0] icmp_ln107_7_fu_1108_p2;
wire   [0:0] icmp_ln107_6_fu_1102_p2;
wire   [7:0] tmp_11_fu_1088_p4;
wire   [22:0] trunc_ln107_10_fu_1098_p1;
wire   [0:0] icmp_ln107_9_fu_1126_p2;
wire   [0:0] icmp_ln107_8_fu_1120_p2;
wire   [0:0] or_ln107_3_fu_1114_p2;
wire   [0:0] or_ln107_4_fu_1132_p2;
wire   [0:0] and_ln107_3_fu_1138_p2;
wire   [0:0] and_ln107_4_fu_1144_p2;
wire   [31:0] bitcast_ln107_5_fu_1156_p1;
wire   [31:0] bitcast_ln107_6_fu_1173_p1;
wire   [7:0] tmp_13_fu_1159_p4;
wire   [22:0] trunc_ln107_11_fu_1169_p1;
wire   [0:0] icmp_ln107_11_fu_1196_p2;
wire   [0:0] icmp_ln107_10_fu_1190_p2;
wire   [7:0] tmp_14_fu_1176_p4;
wire   [22:0] trunc_ln107_12_fu_1186_p1;
wire   [0:0] icmp_ln107_13_fu_1214_p2;
wire   [0:0] icmp_ln107_12_fu_1208_p2;
wire   [0:0] or_ln107_5_fu_1202_p2;
wire   [0:0] or_ln107_6_fu_1220_p2;
wire   [0:0] and_ln107_5_fu_1226_p2;
wire   [0:0] and_ln107_6_fu_1232_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_full_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            channel_fu_104 <= select_ln91_6_fu_375_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            channel_fu_104 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten30_fu_100 <= select_ln93_5_fu_445_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten30_fu_100 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten98_fu_108 <= add_ln91_1_fu_283_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten98_fu_108 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_col_fu_92 <= add_ln95_fu_433_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            output_col_fu_92 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_row_1_fu_96 <= select_ln93_4_fu_425_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            output_row_1_fu_96 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln91_reg_1305 == 1'd0))) begin
        add_ln114_reg_1383 <= add_ln114_fu_926_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln114_reg_1383_pp0_iter10_reg <= add_ln114_reg_1383_pp0_iter9_reg;
        add_ln114_reg_1383_pp0_iter2_reg <= add_ln114_reg_1383;
        add_ln114_reg_1383_pp0_iter3_reg <= add_ln114_reg_1383_pp0_iter2_reg;
        add_ln114_reg_1383_pp0_iter4_reg <= add_ln114_reg_1383_pp0_iter3_reg;
        add_ln114_reg_1383_pp0_iter5_reg <= add_ln114_reg_1383_pp0_iter4_reg;
        add_ln114_reg_1383_pp0_iter6_reg <= add_ln114_reg_1383_pp0_iter5_reg;
        add_ln114_reg_1383_pp0_iter7_reg <= add_ln114_reg_1383_pp0_iter6_reg;
        add_ln114_reg_1383_pp0_iter8_reg <= add_ln114_reg_1383_pp0_iter7_reg;
        add_ln114_reg_1383_pp0_iter9_reg <= add_ln114_reg_1383_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv1_output_load_1_reg_1395_pp0_iter3_reg <= conv1_output_load_1_reg_1395;
        conv1_output_load_1_reg_1395_pp0_iter4_reg <= conv1_output_load_1_reg_1395_pp0_iter3_reg;
        conv1_output_load_1_reg_1395_pp0_iter5_reg <= conv1_output_load_1_reg_1395_pp0_iter4_reg;
        conv1_output_load_2_reg_1402_pp0_iter3_reg <= conv1_output_load_2_reg_1402;
        conv1_output_load_2_reg_1402_pp0_iter4_reg <= conv1_output_load_2_reg_1402_pp0_iter3_reg;
        conv1_output_load_2_reg_1402_pp0_iter5_reg <= conv1_output_load_2_reg_1402_pp0_iter4_reg;
        conv1_output_load_2_reg_1402_pp0_iter6_reg <= conv1_output_load_2_reg_1402_pp0_iter5_reg;
        conv1_output_load_2_reg_1402_pp0_iter7_reg <= conv1_output_load_2_reg_1402_pp0_iter6_reg;
        conv1_output_load_3_reg_1409_pp0_iter3_reg <= conv1_output_load_3_reg_1409;
        conv1_output_load_3_reg_1409_pp0_iter4_reg <= conv1_output_load_3_reg_1409_pp0_iter3_reg;
        conv1_output_load_3_reg_1409_pp0_iter5_reg <= conv1_output_load_3_reg_1409_pp0_iter4_reg;
        conv1_output_load_3_reg_1409_pp0_iter6_reg <= conv1_output_load_3_reg_1409_pp0_iter5_reg;
        conv1_output_load_3_reg_1409_pp0_iter7_reg <= conv1_output_load_3_reg_1409_pp0_iter6_reg;
        conv1_output_load_3_reg_1409_pp0_iter8_reg <= conv1_output_load_3_reg_1409_pp0_iter7_reg;
        conv1_output_load_3_reg_1409_pp0_iter9_reg <= conv1_output_load_3_reg_1409_pp0_iter8_reg;
        conv1_output_load_reg_1388_pp0_iter3_reg <= conv1_output_load_reg_1388;
        select_ln107_1_reg_1423 <= select_ln107_1_fu_1062_p3;
        select_ln107_1_reg_1423_pp0_iter7_reg <= select_ln107_1_reg_1423;
        select_ln107_2_reg_1430 <= select_ln107_2_fu_1150_p3;
        select_ln107_2_reg_1430_pp0_iter9_reg <= select_ln107_2_reg_1430;
        select_ln107_3_reg_1437 <= select_ln107_3_fu_1238_p3;
        select_ln107_reg_1416 <= select_ln107_fu_973_p3;
        select_ln107_reg_1416_pp0_iter5_reg <= select_ln107_reg_1416;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln91_fu_277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln91_reg_1317 <= add_ln91_fu_309_p2;
        add_ln93_reg_1341 <= add_ln93_fu_383_p2;
        and_ln91_reg_1334 <= and_ln91_fu_369_p2;
        empty_47_reg_1329[7 : 2] <= empty_47_fu_353_p1[7 : 2];
        empty_50_reg_1358[7 : 1] <= empty_50_fu_421_p1[7 : 1];
        icmp_ln93_reg_1309 <= icmp_ln93_fu_295_p2;
        p_mid122_reg_1352[8 : 1] <= p_mid122_fu_415_p2[8 : 1];
        p_mid142_reg_1323[8 : 2] <= p_mid142_fu_339_p2[8 : 2];
        select_ln93_reg_1346 <= select_ln93_fu_395_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        channel_2_reg_1288 <= ap_sig_allocacmp_channel_2;
        empty_39_reg_1294[8 : 1] <= empty_39_fu_267_p2[8 : 1];
        empty_40_reg_1300[7 : 1] <= empty_40_fu_273_p1[7 : 1];
        icmp_ln91_reg_1305 <= icmp_ln91_fu_277_p2;
        output_row_reg_1283 <= ap_sig_allocacmp_output_row;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv1_output_load_1_reg_1395 <= conv1_output_q2;
        conv1_output_load_2_reg_1402 <= conv1_output_q1;
        conv1_output_load_3_reg_1409 <= conv1_output_q0;
        conv1_output_load_reg_1388 <= conv1_output_q3;
    end
end

always @ (*) begin
    if (((icmp_ln91_fu_277_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln91_reg_1305 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_channel_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_channel_2 = channel_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten30_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten30_load = indvar_flatten30_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten98_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten98_load = indvar_flatten98_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_col_load = 4'd0;
    end else begin
        ap_sig_allocacmp_output_col_load = output_col_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_row = 4'd0;
    end else begin
        ap_sig_allocacmp_output_row = output_row_1_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce0 = 1'b1;
    end else begin
        conv1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce1 = 1'b1;
    end else begin
        conv1_output_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce2 = 1'b1;
    end else begin
        conv1_output_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce3 = 1'b1;
    end else begin
        conv1_output_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        pool1_output_ce0 = 1'b1;
    end else begin
        pool1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        pool1_output_we0 = 1'b1;
    end else begin
        pool1_output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_1_fu_904_p2 = (select_ln93_3_fu_861_p3 + zext_ln105_fu_878_p1);

assign add_ln105_fu_882_p2 = (select_ln93_2_fu_819_p3 + zext_ln105_fu_878_p1);

assign add_ln114_fu_926_p2 = (output_col_cast35_fu_868_p1 + select_ln93_1_fu_788_p3);

assign add_ln91_1_fu_283_p2 = (ap_sig_allocacmp_indvar_flatten98_load + 11'd1);

assign add_ln91_fu_309_p2 = (ap_sig_allocacmp_channel_2 + 3'd1);

assign add_ln93_2_fu_439_p2 = (ap_sig_allocacmp_indvar_flatten30_load + 8'd1);

assign add_ln93_fu_383_p2 = (select_ln91_fu_301_p3 + 4'd1);

assign add_ln95_fu_433_p2 = (select_ln93_fu_395_p3 + 4'd1);

assign and_ln107_1_fu_1050_p2 = (or_ln107_2_fu_1044_p2 & or_ln107_1_fu_1026_p2);

assign and_ln107_2_fu_1056_p2 = (grp_fu_1414_p_dout0 & and_ln107_1_fu_1050_p2);

assign and_ln107_3_fu_1138_p2 = (or_ln107_4_fu_1132_p2 & or_ln107_3_fu_1114_p2);

assign and_ln107_4_fu_1144_p2 = (grp_fu_1418_p_dout0 & and_ln107_3_fu_1138_p2);

assign and_ln107_5_fu_1226_p2 = (or_ln107_6_fu_1220_p2 & or_ln107_5_fu_1202_p2);

assign and_ln107_6_fu_1232_p2 = (grp_fu_1422_p_dout0 & and_ln107_5_fu_1226_p2);

assign and_ln107_fu_967_p2 = (or_ln107_fu_961_p2 & grp_fu_1410_p_dout0);

assign and_ln91_fu_369_p2 = (xor_ln91_fu_357_p2 & icmp_ln95_fu_363_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln107_1_fu_980_p1 = conv1_output_load_1_reg_1395_pp0_iter5_reg;

assign bitcast_ln107_2_fu_997_p1 = select_ln107_reg_1416_pp0_iter5_reg;

assign bitcast_ln107_3_fu_1068_p1 = conv1_output_load_2_reg_1402_pp0_iter7_reg;

assign bitcast_ln107_4_fu_1085_p1 = select_ln107_1_reg_1423_pp0_iter7_reg;

assign bitcast_ln107_5_fu_1156_p1 = conv1_output_load_3_reg_1409_pp0_iter9_reg;

assign bitcast_ln107_6_fu_1173_p1 = select_ln107_2_reg_1430_pp0_iter9_reg;

assign bitcast_ln107_fu_932_p1 = conv1_output_load_reg_1388_pp0_iter3_reg;

assign conv1_output_address0 = zext_ln106_3_fu_921_p1;

assign conv1_output_address1 = zext_ln106_2_fu_910_p1;

assign conv1_output_address2 = zext_ln106_1_fu_899_p1;

assign conv1_output_address3 = zext_ln106_fu_888_p1;

assign empty_35_fu_500_p2 = (p_shl7_cast_fu_485_p1 - p_shl8_cast_fu_496_p1);

assign empty_36_fu_509_p2 = (zext_ln93_fu_506_p1 + empty_35_fu_500_p2);

assign empty_37_fu_515_p1 = empty_36_fu_509_p2[6:0];

assign empty_38_fu_539_p2 = ($signed(p_shl5_fu_519_p3) - $signed(p_shl12_cast_fu_535_p1));

assign empty_39_fu_267_p2 = (p_cast20_fu_263_p1 + empty_fu_249_p2);

assign empty_40_fu_273_p1 = empty_39_fu_267_p2[7:0];

assign empty_41_fu_563_p2 = ($signed(p_shl_fu_545_p3) - $signed(p_shl14_0_cast_fu_559_p1));

assign empty_42_fu_569_p2 = (empty_39_reg_1294 | 9'd1);

assign empty_43_fu_574_p1 = empty_42_fu_569_p2[7:0];

assign empty_44_fu_598_p2 = ($signed(p_shl13_1_fu_578_p3) - $signed(p_shl14_1_cast_fu_594_p1));

assign empty_46_fu_639_p1 = p_mid144_fu_626_p2[6:0];

assign empty_47_fu_353_p1 = p_mid142_fu_339_p2[7:0];

assign empty_48_fu_712_p1 = p_mid182_fu_707_p2[7:0];

assign empty_49_fu_758_p1 = p_mid118_fu_752_p2[6:0];

assign empty_50_fu_421_p1 = p_mid122_fu_415_p2[7:0];

assign empty_51_fu_831_p1 = p_mid126_fu_826_p2[7:0];

assign empty_fu_249_p2 = (p_shl9_cast_fu_233_p1 - p_shl10_cast_fu_245_p1);

assign grp_fu_1410_p_ce = 1'b1;

assign grp_fu_1410_p_din0 = conv1_output_load_reg_1388;

assign grp_fu_1410_p_din1 = 32'd0;

assign grp_fu_1410_p_opcode = 5'd2;

assign grp_fu_1414_p_ce = 1'b1;

assign grp_fu_1414_p_din0 = conv1_output_load_1_reg_1395_pp0_iter4_reg;

assign grp_fu_1414_p_din1 = select_ln107_reg_1416;

assign grp_fu_1414_p_opcode = 5'd2;

assign grp_fu_1418_p_ce = 1'b1;

assign grp_fu_1418_p_din0 = conv1_output_load_2_reg_1402_pp0_iter6_reg;

assign grp_fu_1418_p_din1 = select_ln107_1_reg_1423;

assign grp_fu_1418_p_opcode = 5'd2;

assign grp_fu_1422_p_ce = 1'b1;

assign grp_fu_1422_p_din0 = conv1_output_load_3_reg_1409_pp0_iter8_reg;

assign grp_fu_1422_p_din1 = select_ln107_2_reg_1430;

assign grp_fu_1422_p_opcode = 5'd2;

assign icmp_ln107_10_fu_1190_p2 = ((tmp_13_fu_1159_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_11_fu_1196_p2 = ((trunc_ln107_11_fu_1169_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_12_fu_1208_p2 = ((tmp_14_fu_1176_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_13_fu_1214_p2 = ((trunc_ln107_12_fu_1186_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_1_fu_955_p2 = ((trunc_ln107_fu_945_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_2_fu_1014_p2 = ((tmp_8_fu_983_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_3_fu_1020_p2 = ((trunc_ln107_7_fu_993_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_4_fu_1032_p2 = ((tmp_9_fu_1000_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_5_fu_1038_p2 = ((trunc_ln107_8_fu_1010_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_6_fu_1102_p2 = ((tmp_10_fu_1071_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_7_fu_1108_p2 = ((trunc_ln107_9_fu_1081_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_8_fu_1120_p2 = ((tmp_11_fu_1088_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_9_fu_1126_p2 = ((trunc_ln107_10_fu_1098_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_949_p2 = ((tmp_6_fu_935_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_277_p2 = ((ap_sig_allocacmp_indvar_flatten98_load == 11'd1176) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_295_p2 = ((ap_sig_allocacmp_indvar_flatten30_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_363_p2 = ((ap_sig_allocacmp_output_col_load == 4'd14) ? 1'b1 : 1'b0);

assign or_ln105_1_fu_915_p2 = (13'd1 | add_ln105_1_fu_904_p2);

assign or_ln105_fu_893_p2 = (13'd1 | add_ln105_fu_882_p2);

assign or_ln107_1_fu_1026_p2 = (icmp_ln107_3_fu_1020_p2 | icmp_ln107_2_fu_1014_p2);

assign or_ln107_2_fu_1044_p2 = (icmp_ln107_5_fu_1038_p2 | icmp_ln107_4_fu_1032_p2);

assign or_ln107_3_fu_1114_p2 = (icmp_ln107_7_fu_1108_p2 | icmp_ln107_6_fu_1102_p2);

assign or_ln107_4_fu_1132_p2 = (icmp_ln107_9_fu_1126_p2 | icmp_ln107_8_fu_1120_p2);

assign or_ln107_5_fu_1202_p2 = (icmp_ln107_11_fu_1196_p2 | icmp_ln107_10_fu_1190_p2);

assign or_ln107_6_fu_1220_p2 = (icmp_ln107_13_fu_1214_p2 | icmp_ln107_12_fu_1208_p2);

assign or_ln107_fu_961_p2 = (icmp_ln107_fu_949_p2 | icmp_ln107_1_fu_955_p2);

assign or_ln93_fu_389_p2 = (icmp_ln93_fu_295_p2 | and_ln91_fu_369_p2);

assign output_col_cast35_fu_868_p1 = select_ln93_reg_1346;

assign p_cast20_fu_263_p1 = tmp_1_fu_255_p3;

assign p_cast20_mid1_fu_411_p1 = p_mid_fu_403_p3;

assign p_mid118_fu_752_p2 = (zext_ln93_1_fu_749_p1 + select_ln91_2_fu_632_p3);

assign p_mid120_fu_782_p2 = ($signed(p_shl11_mid1_fu_762_p3) - $signed(p_shl12_cast_mid1_fu_778_p1));

assign p_mid122_fu_415_p2 = (p_cast20_mid1_fu_411_p1 + select_ln91_1_fu_345_p3);

assign p_mid124_fu_813_p2 = ($signed(p_shl13_0_mid1_fu_795_p3) - $signed(p_shl14_0_cast_mid1_fu_809_p1));

assign p_mid126_fu_826_p2 = (p_mid122_reg_1352 | 9'd1);

assign p_mid128_fu_855_p2 = ($signed(p_shl13_1_mid1_fu_835_p3) - $signed(p_shl14_1_cast_mid1_fu_851_p1));

assign p_mid142_fu_339_p2 = (p_shl9_cast_mid1_fu_323_p1 - p_shl10_cast_mid1_fu_335_p1);

assign p_mid144_fu_626_p2 = (p_shl7_cast_mid1_fu_611_p1 - p_shl8_cast_mid1_fu_622_p1);

assign p_mid166_fu_663_p2 = ($signed(p_shl11_mid_fu_643_p3) - $signed(p_shl12_cast_mid164_fu_659_p1));

assign p_mid180_fu_694_p2 = ($signed(p_shl13_0_mid_fu_676_p3) - $signed(p_shl14_0_cast_mid178_fu_690_p1));

assign p_mid182_fu_707_p2 = (p_mid142_reg_1323 | 9'd1);

assign p_mid194_fu_736_p2 = ($signed(p_shl13_1_mid_fu_716_p3) - $signed(p_shl14_1_cast_mid192_fu_732_p1));

assign p_mid_fu_403_p3 = {{add_ln93_fu_383_p2}, {1'd0}};

assign p_shl10_cast_fu_245_p1 = p_shl4_fu_237_p3;

assign p_shl10_cast_mid1_fu_335_p1 = p_shl10_mid1_fu_327_p3;

assign p_shl10_mid1_fu_327_p3 = {{add_ln91_fu_309_p2}, {2'd0}};

assign p_shl11_mid1_fu_762_p3 = {{empty_49_fu_758_p1}, {4'd0}};

assign p_shl11_mid_fu_643_p3 = {{empty_46_fu_639_p1}, {4'd0}};

assign p_shl12_cast_fu_535_p1 = $signed(p_shl6_fu_527_p3);

assign p_shl12_cast_mid164_fu_659_p1 = $signed(p_shl12_mid_fu_651_p3);

assign p_shl12_cast_mid1_fu_778_p1 = $signed(p_shl12_mid1_fu_770_p3);

assign p_shl12_mid1_fu_770_p3 = {{p_mid118_fu_752_p2}, {1'd0}};

assign p_shl12_mid_fu_651_p3 = {{p_mid144_fu_626_p2}, {1'd0}};

assign p_shl13_0_mid1_fu_795_p3 = {{empty_50_reg_1358}, {5'd0}};

assign p_shl13_0_mid_fu_676_p3 = {{empty_47_reg_1329}, {5'd0}};

assign p_shl13_1_fu_578_p3 = {{empty_43_fu_574_p1}, {5'd0}};

assign p_shl13_1_mid1_fu_835_p3 = {{empty_51_fu_831_p1}, {5'd0}};

assign p_shl13_1_mid_fu_716_p3 = {{empty_48_fu_712_p1}, {5'd0}};

assign p_shl14_0_cast_fu_559_p1 = $signed(p_shl2_fu_552_p3);

assign p_shl14_0_cast_mid178_fu_690_p1 = $signed(p_shl14_0_mid_fu_683_p3);

assign p_shl14_0_cast_mid1_fu_809_p1 = $signed(p_shl14_0_mid1_fu_802_p3);

assign p_shl14_0_mid1_fu_802_p3 = {{p_mid122_reg_1352}, {2'd0}};

assign p_shl14_0_mid_fu_683_p3 = {{p_mid142_reg_1323}, {2'd0}};

assign p_shl14_1_cast_fu_594_p1 = $signed(p_shl14_1_fu_586_p3);

assign p_shl14_1_cast_mid192_fu_732_p1 = $signed(p_shl14_1_mid_fu_724_p3);

assign p_shl14_1_cast_mid1_fu_851_p1 = $signed(p_shl14_1_mid1_fu_843_p3);

assign p_shl14_1_fu_586_p3 = {{empty_42_fu_569_p2}, {2'd0}};

assign p_shl14_1_mid1_fu_843_p3 = {{p_mid126_fu_826_p2}, {2'd0}};

assign p_shl14_1_mid_fu_724_p3 = {{p_mid182_fu_707_p2}, {2'd0}};

assign p_shl2_fu_552_p3 = {{empty_39_reg_1294}, {2'd0}};

assign p_shl4_fu_237_p3 = {{ap_sig_allocacmp_channel_2}, {2'd0}};

assign p_shl5_fu_519_p3 = {{empty_37_fu_515_p1}, {4'd0}};

assign p_shl6_fu_527_p3 = {{empty_36_fu_509_p2}, {1'd0}};

assign p_shl7_cast_fu_485_p1 = p_shl7_fu_478_p3;

assign p_shl7_cast_mid1_fu_611_p1 = p_shl7_mid1_fu_604_p3;

assign p_shl7_fu_478_p3 = {{channel_2_reg_1288}, {4'd0}};

assign p_shl7_mid1_fu_604_p3 = {{add_ln91_reg_1317}, {4'd0}};

assign p_shl8_cast_fu_496_p1 = p_shl8_fu_489_p3;

assign p_shl8_cast_mid1_fu_622_p1 = p_shl8_mid1_fu_615_p3;

assign p_shl8_fu_489_p3 = {{channel_2_reg_1288}, {1'd0}};

assign p_shl8_mid1_fu_615_p3 = {{add_ln91_reg_1317}, {1'd0}};

assign p_shl9_cast_fu_233_p1 = p_shl9_fu_225_p3;

assign p_shl9_cast_mid1_fu_323_p1 = p_shl9_mid1_fu_315_p3;

assign p_shl9_fu_225_p3 = {{ap_sig_allocacmp_channel_2}, {5'd0}};

assign p_shl9_mid1_fu_315_p3 = {{add_ln91_fu_309_p2}, {5'd0}};

assign p_shl_fu_545_p3 = {{empty_40_reg_1300}, {5'd0}};

assign pool1_output_address0 = zext_ln115_fu_1244_p1;

assign pool1_output_d0 = select_ln107_3_reg_1437;

assign select_ln107_1_fu_1062_p3 = ((and_ln107_2_fu_1056_p2[0:0] == 1'b1) ? conv1_output_load_1_reg_1395_pp0_iter5_reg : select_ln107_reg_1416_pp0_iter5_reg);

assign select_ln107_2_fu_1150_p3 = ((and_ln107_4_fu_1144_p2[0:0] == 1'b1) ? conv1_output_load_2_reg_1402_pp0_iter7_reg : select_ln107_1_reg_1423_pp0_iter7_reg);

assign select_ln107_3_fu_1238_p3 = ((and_ln107_6_fu_1232_p2[0:0] == 1'b1) ? conv1_output_load_3_reg_1409_pp0_iter9_reg : select_ln107_2_reg_1430_pp0_iter9_reg);

assign select_ln107_fu_973_p3 = ((and_ln107_fu_967_p2[0:0] == 1'b1) ? conv1_output_load_reg_1388_pp0_iter3_reg : 32'd0);

assign select_ln91_1_fu_345_p3 = ((icmp_ln93_fu_295_p2[0:0] == 1'b1) ? p_mid142_fu_339_p2 : empty_fu_249_p2);

assign select_ln91_2_fu_632_p3 = ((icmp_ln93_reg_1309[0:0] == 1'b1) ? p_mid144_fu_626_p2 : empty_35_fu_500_p2);

assign select_ln91_3_fu_669_p3 = ((icmp_ln93_reg_1309[0:0] == 1'b1) ? p_mid166_fu_663_p2 : empty_38_fu_539_p2);

assign select_ln91_4_fu_700_p3 = ((icmp_ln93_reg_1309[0:0] == 1'b1) ? p_mid180_fu_694_p2 : empty_41_fu_563_p2);

assign select_ln91_5_fu_742_p3 = ((icmp_ln93_reg_1309[0:0] == 1'b1) ? p_mid194_fu_736_p2 : empty_44_fu_598_p2);

assign select_ln91_6_fu_375_p3 = ((icmp_ln93_fu_295_p2[0:0] == 1'b1) ? add_ln91_fu_309_p2 : ap_sig_allocacmp_channel_2);

assign select_ln91_fu_301_p3 = ((icmp_ln93_fu_295_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_output_row);

assign select_ln93_1_fu_788_p3 = ((and_ln91_reg_1334[0:0] == 1'b1) ? p_mid120_fu_782_p2 : select_ln91_3_fu_669_p3);

assign select_ln93_2_fu_819_p3 = ((and_ln91_reg_1334[0:0] == 1'b1) ? p_mid124_fu_813_p2 : select_ln91_4_fu_700_p3);

assign select_ln93_3_fu_861_p3 = ((and_ln91_reg_1334[0:0] == 1'b1) ? p_mid128_fu_855_p2 : select_ln91_5_fu_742_p3);

assign select_ln93_4_fu_425_p3 = ((and_ln91_fu_369_p2[0:0] == 1'b1) ? add_ln93_fu_383_p2 : select_ln91_fu_301_p3);

assign select_ln93_5_fu_445_p3 = ((icmp_ln93_fu_295_p2[0:0] == 1'b1) ? 8'd1 : add_ln93_2_fu_439_p2);

assign select_ln93_fu_395_p3 = ((or_ln93_fu_389_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_output_col_load);

assign tmp_10_fu_1071_p4 = {{bitcast_ln107_3_fu_1068_p1[30:23]}};

assign tmp_11_fu_1088_p4 = {{bitcast_ln107_4_fu_1085_p1[30:23]}};

assign tmp_13_fu_1159_p4 = {{bitcast_ln107_5_fu_1156_p1[30:23]}};

assign tmp_14_fu_1176_p4 = {{bitcast_ln107_6_fu_1173_p1[30:23]}};

assign tmp_16_fu_871_p3 = {{select_ln93_reg_1346}, {1'd0}};

assign tmp_1_fu_255_p3 = {{ap_sig_allocacmp_output_row}, {1'd0}};

assign tmp_6_fu_935_p4 = {{bitcast_ln107_fu_932_p1[30:23]}};

assign tmp_8_fu_983_p4 = {{bitcast_ln107_1_fu_980_p1[30:23]}};

assign tmp_9_fu_1000_p4 = {{bitcast_ln107_2_fu_997_p1[30:23]}};

assign trunc_ln107_10_fu_1098_p1 = bitcast_ln107_4_fu_1085_p1[22:0];

assign trunc_ln107_11_fu_1169_p1 = bitcast_ln107_5_fu_1156_p1[22:0];

assign trunc_ln107_12_fu_1186_p1 = bitcast_ln107_6_fu_1173_p1[22:0];

assign trunc_ln107_7_fu_993_p1 = bitcast_ln107_1_fu_980_p1[22:0];

assign trunc_ln107_8_fu_1010_p1 = bitcast_ln107_2_fu_997_p1[22:0];

assign trunc_ln107_9_fu_1081_p1 = bitcast_ln107_3_fu_1068_p1[22:0];

assign trunc_ln107_fu_945_p1 = bitcast_ln107_fu_932_p1[22:0];

assign xor_ln91_fu_357_p2 = (icmp_ln93_fu_295_p2 ^ 1'd1);

assign zext_ln105_fu_878_p1 = tmp_16_fu_871_p3;

assign zext_ln106_1_fu_899_p1 = or_ln105_fu_893_p2;

assign zext_ln106_2_fu_910_p1 = add_ln105_1_fu_904_p2;

assign zext_ln106_3_fu_921_p1 = or_ln105_1_fu_915_p2;

assign zext_ln106_fu_888_p1 = add_ln105_fu_882_p2;

assign zext_ln115_fu_1244_p1 = add_ln114_reg_1383_pp0_iter10_reg;

assign zext_ln93_1_fu_749_p1 = add_ln93_reg_1341;

assign zext_ln93_fu_506_p1 = output_row_reg_1283;

always @ (posedge ap_clk) begin
    empty_39_reg_1294[0] <= 1'b0;
    empty_40_reg_1300[0] <= 1'b0;
    p_mid142_reg_1323[1:0] <= 2'b00;
    empty_47_reg_1329[1:0] <= 2'b00;
    p_mid122_reg_1352[0] <= 1'b0;
    empty_50_reg_1358[0] <= 1'b0;
end

endmodule //lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL
