// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_w4a4_top_lenet_w4a4_top_Pipeline_DENSE_OUTPUT_DENSE_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        weight,
        conv3_relu_V_address0,
        conv3_relu_V_ce0,
        conv3_relu_V_q0,
        fc1_acc_V_address0,
        fc1_acc_V_ce0,
        fc1_acc_V_we0,
        fc1_acc_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] weight;
output  [6:0] conv3_relu_V_address0;
output   conv3_relu_V_ce0;
input  [2:0] conv3_relu_V_q0;
output  [6:0] fc1_acc_V_address0;
output   fc1_acc_V_ce0;
output   fc1_acc_V_we0;
output  [13:0] fc1_acc_V_d0;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg conv3_relu_V_ce0;
reg fc1_acc_V_ce0;
reg fc1_acc_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln331_fu_168_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_R;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] output_index_1_reg_440;
reg   [0:0] icmp_ln331_reg_446;
wire   [0:0] icmp_ln339_fu_183_p2;
reg   [0:0] icmp_ln339_reg_450;
reg   [0:0] icmp_ln339_reg_450_pp0_iter1_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter2_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter3_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter4_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter5_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter6_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter7_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter8_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter9_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter10_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter11_reg;
reg   [0:0] icmp_ln339_reg_450_pp0_iter12_reg;
wire   [6:0] select_ln331_fu_189_p3;
reg   [6:0] select_ln331_reg_456;
reg   [6:0] select_ln331_reg_456_pp0_iter1_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter2_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter3_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter4_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter5_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter6_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter7_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter8_reg;
reg   [6:0] select_ln331_reg_456_pp0_iter9_reg;
wire   [6:0] add_ln332_fu_197_p2;
reg   [6:0] add_ln332_reg_462;
wire   [6:0] select_ln331_2_fu_203_p3;
reg   [6:0] select_ln331_2_reg_468;
reg   [6:0] select_ln331_2_reg_468_pp0_iter1_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter2_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter3_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter4_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter5_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter6_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter7_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter8_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter9_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter10_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter11_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter12_reg;
reg   [6:0] select_ln331_2_reg_468_pp0_iter13_reg;
wire   [0:0] trunc_ln8_fu_211_p1;
reg   [0:0] trunc_ln8_reg_473;
reg   [0:0] trunc_ln8_reg_473_pp0_iter1_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter2_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter3_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter4_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter5_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter6_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter7_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter8_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter9_reg;
reg   [0:0] trunc_ln8_reg_473_pp0_iter10_reg;
wire   [0:0] ifzero_fu_221_p2;
reg   [0:0] ifzero_reg_478;
reg   [0:0] ifzero_reg_478_pp0_iter1_reg;
reg   [0:0] ifzero_reg_478_pp0_iter2_reg;
reg   [0:0] ifzero_reg_478_pp0_iter3_reg;
reg   [0:0] ifzero_reg_478_pp0_iter4_reg;
reg   [0:0] ifzero_reg_478_pp0_iter5_reg;
reg   [0:0] ifzero_reg_478_pp0_iter6_reg;
reg   [0:0] ifzero_reg_478_pp0_iter7_reg;
reg   [0:0] ifzero_reg_478_pp0_iter8_reg;
reg   [0:0] ifzero_reg_478_pp0_iter9_reg;
reg   [0:0] ifzero_reg_478_pp0_iter10_reg;
reg   [0:0] ifzero_reg_478_pp0_iter11_reg;
reg   [0:0] ifzero_reg_478_pp0_iter12_reg;
reg   [0:0] ifzero_reg_478_pp0_iter13_reg;
reg   [13:0] trunc_ln8_7_reg_482;
reg   [63:0] gmem1_addr_reg_487;
wire   [3:0] nibble_V_fu_352_p1;
reg   [3:0] nibble_V_reg_493;
reg   [3:0] nibble_V_12_reg_498;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] trunc_ln344_1_cast132_fu_348_p1;
wire   [63:0] zext_ln331_fu_389_p1;
wire   [63:0] add_ln8_fu_337_p2;
reg   [13:0] accumulator_V_1_fu_82;
wire  signed [13:0] grp_fu_397_p3;
reg   [13:0] ap_sig_allocacmp_accumulator_V_1_load;
wire    ap_loop_init;
reg   [6:0] input_index_fu_86;
wire   [6:0] add_ln340_fu_215_p2;
reg   [6:0] ap_sig_allocacmp_input_index_load;
reg   [6:0] output_index_fu_90;
reg   [6:0] ap_sig_allocacmp_output_index_1;
reg   [13:0] indvar_flatten309_fu_94;
wire   [13:0] add_ln331_1_fu_174_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten309_load;
wire   [13:0] p_shl_fu_242_p3;
wire   [9:0] p_shl11_fu_253_p3;
wire   [14:0] p_shl31_cast_fu_249_p1;
wire   [14:0] p_shl32_cast_fu_260_p1;
wire   [13:0] p_shl31_mid1_fu_270_p3;
wire   [9:0] p_shl32_mid1_fu_281_p3;
wire   [14:0] p_shl31_cast_mid1_fu_277_p1;
wire   [14:0] p_shl32_cast_mid1_fu_288_p1;
wire   [14:0] sub_ln344_1_fu_292_p2;
wire   [14:0] sub_ln344_fu_264_p2;
wire   [14:0] select_ln331_3_fu_298_p3;
wire   [14:0] add_ln331_fu_308_p2;
wire   [14:0] zext_ln6_fu_305_p1;
wire   [14:0] add_ln8_4_fu_314_p2;
wire  signed [14:0] sext_ln8_fu_330_p1;
wire   [63:0] zext_ln8_fu_333_p1;
wire  signed [3:0] nibble_V_14_fu_366_p3;
wire   [2:0] grp_fu_397_p0;
wire  signed [13:0] grp_fu_397_p2;
reg    grp_fu_397_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [6:0] grp_fu_397_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_w4a4_top_mac_muladd_3ns_4s_14s_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
mac_muladd_3ns_4s_14s_14_4_1_U110(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_397_p0),
    .din1(nibble_V_14_fu_366_p3),
    .din2(grp_fu_397_p2),
    .ce(grp_fu_397_ce),
    .dout(grp_fu_397_p3)
);

lenet_w4a4_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            accumulator_V_1_fu_82 <= 14'd0;
        end else if ((ap_enable_reg_pp0_iter14 == 1'b1)) begin
            accumulator_V_1_fu_82 <= grp_fu_397_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln331_fu_168_p2 == 1'd0))) begin
            indvar_flatten309_fu_94 <= add_ln331_1_fu_174_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten309_fu_94 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln331_fu_168_p2 == 1'd0))) begin
            input_index_fu_86 <= add_ln340_fu_215_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            input_index_fu_86 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln331_fu_168_p2 == 1'd0))) begin
            output_index_fu_90 <= select_ln331_2_fu_203_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            output_index_fu_90 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln331_fu_168_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln332_reg_462 <= add_ln332_fu_197_p2;
        icmp_ln339_reg_450 <= icmp_ln339_fu_183_p2;
        ifzero_reg_478 <= ifzero_fu_221_p2;
        select_ln331_2_reg_468 <= select_ln331_2_fu_203_p3;
        select_ln331_reg_456 <= select_ln331_fu_189_p3;
        trunc_ln8_reg_473 <= trunc_ln8_fu_211_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem1_addr_reg_487 <= add_ln8_fu_337_p2;
        icmp_ln339_reg_450_pp0_iter10_reg <= icmp_ln339_reg_450_pp0_iter9_reg;
        icmp_ln339_reg_450_pp0_iter11_reg <= icmp_ln339_reg_450_pp0_iter10_reg;
        icmp_ln339_reg_450_pp0_iter12_reg <= icmp_ln339_reg_450_pp0_iter11_reg;
        icmp_ln339_reg_450_pp0_iter2_reg <= icmp_ln339_reg_450_pp0_iter1_reg;
        icmp_ln339_reg_450_pp0_iter3_reg <= icmp_ln339_reg_450_pp0_iter2_reg;
        icmp_ln339_reg_450_pp0_iter4_reg <= icmp_ln339_reg_450_pp0_iter3_reg;
        icmp_ln339_reg_450_pp0_iter5_reg <= icmp_ln339_reg_450_pp0_iter4_reg;
        icmp_ln339_reg_450_pp0_iter6_reg <= icmp_ln339_reg_450_pp0_iter5_reg;
        icmp_ln339_reg_450_pp0_iter7_reg <= icmp_ln339_reg_450_pp0_iter6_reg;
        icmp_ln339_reg_450_pp0_iter8_reg <= icmp_ln339_reg_450_pp0_iter7_reg;
        icmp_ln339_reg_450_pp0_iter9_reg <= icmp_ln339_reg_450_pp0_iter8_reg;
        ifzero_reg_478_pp0_iter10_reg <= ifzero_reg_478_pp0_iter9_reg;
        ifzero_reg_478_pp0_iter11_reg <= ifzero_reg_478_pp0_iter10_reg;
        ifzero_reg_478_pp0_iter12_reg <= ifzero_reg_478_pp0_iter11_reg;
        ifzero_reg_478_pp0_iter13_reg <= ifzero_reg_478_pp0_iter12_reg;
        ifzero_reg_478_pp0_iter2_reg <= ifzero_reg_478_pp0_iter1_reg;
        ifzero_reg_478_pp0_iter3_reg <= ifzero_reg_478_pp0_iter2_reg;
        ifzero_reg_478_pp0_iter4_reg <= ifzero_reg_478_pp0_iter3_reg;
        ifzero_reg_478_pp0_iter5_reg <= ifzero_reg_478_pp0_iter4_reg;
        ifzero_reg_478_pp0_iter6_reg <= ifzero_reg_478_pp0_iter5_reg;
        ifzero_reg_478_pp0_iter7_reg <= ifzero_reg_478_pp0_iter6_reg;
        ifzero_reg_478_pp0_iter8_reg <= ifzero_reg_478_pp0_iter7_reg;
        ifzero_reg_478_pp0_iter9_reg <= ifzero_reg_478_pp0_iter8_reg;
        select_ln331_2_reg_468_pp0_iter10_reg <= select_ln331_2_reg_468_pp0_iter9_reg;
        select_ln331_2_reg_468_pp0_iter11_reg <= select_ln331_2_reg_468_pp0_iter10_reg;
        select_ln331_2_reg_468_pp0_iter12_reg <= select_ln331_2_reg_468_pp0_iter11_reg;
        select_ln331_2_reg_468_pp0_iter13_reg <= select_ln331_2_reg_468_pp0_iter12_reg;
        select_ln331_2_reg_468_pp0_iter2_reg <= select_ln331_2_reg_468_pp0_iter1_reg;
        select_ln331_2_reg_468_pp0_iter3_reg <= select_ln331_2_reg_468_pp0_iter2_reg;
        select_ln331_2_reg_468_pp0_iter4_reg <= select_ln331_2_reg_468_pp0_iter3_reg;
        select_ln331_2_reg_468_pp0_iter5_reg <= select_ln331_2_reg_468_pp0_iter4_reg;
        select_ln331_2_reg_468_pp0_iter6_reg <= select_ln331_2_reg_468_pp0_iter5_reg;
        select_ln331_2_reg_468_pp0_iter7_reg <= select_ln331_2_reg_468_pp0_iter6_reg;
        select_ln331_2_reg_468_pp0_iter8_reg <= select_ln331_2_reg_468_pp0_iter7_reg;
        select_ln331_2_reg_468_pp0_iter9_reg <= select_ln331_2_reg_468_pp0_iter8_reg;
        select_ln331_reg_456_pp0_iter2_reg <= select_ln331_reg_456_pp0_iter1_reg;
        select_ln331_reg_456_pp0_iter3_reg <= select_ln331_reg_456_pp0_iter2_reg;
        select_ln331_reg_456_pp0_iter4_reg <= select_ln331_reg_456_pp0_iter3_reg;
        select_ln331_reg_456_pp0_iter5_reg <= select_ln331_reg_456_pp0_iter4_reg;
        select_ln331_reg_456_pp0_iter6_reg <= select_ln331_reg_456_pp0_iter5_reg;
        select_ln331_reg_456_pp0_iter7_reg <= select_ln331_reg_456_pp0_iter6_reg;
        select_ln331_reg_456_pp0_iter8_reg <= select_ln331_reg_456_pp0_iter7_reg;
        select_ln331_reg_456_pp0_iter9_reg <= select_ln331_reg_456_pp0_iter8_reg;
        trunc_ln8_reg_473_pp0_iter10_reg <= trunc_ln8_reg_473_pp0_iter9_reg;
        trunc_ln8_reg_473_pp0_iter2_reg <= trunc_ln8_reg_473_pp0_iter1_reg;
        trunc_ln8_reg_473_pp0_iter3_reg <= trunc_ln8_reg_473_pp0_iter2_reg;
        trunc_ln8_reg_473_pp0_iter4_reg <= trunc_ln8_reg_473_pp0_iter3_reg;
        trunc_ln8_reg_473_pp0_iter5_reg <= trunc_ln8_reg_473_pp0_iter4_reg;
        trunc_ln8_reg_473_pp0_iter6_reg <= trunc_ln8_reg_473_pp0_iter5_reg;
        trunc_ln8_reg_473_pp0_iter7_reg <= trunc_ln8_reg_473_pp0_iter6_reg;
        trunc_ln8_reg_473_pp0_iter8_reg <= trunc_ln8_reg_473_pp0_iter7_reg;
        trunc_ln8_reg_473_pp0_iter9_reg <= trunc_ln8_reg_473_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln331_reg_446 <= icmp_ln331_fu_168_p2;
        icmp_ln339_reg_450_pp0_iter1_reg <= icmp_ln339_reg_450;
        ifzero_reg_478_pp0_iter1_reg <= ifzero_reg_478;
        output_index_1_reg_440 <= ap_sig_allocacmp_output_index_1;
        select_ln331_2_reg_468_pp0_iter1_reg <= select_ln331_2_reg_468;
        select_ln331_reg_456_pp0_iter1_reg <= select_ln331_reg_456;
        trunc_ln8_reg_473_pp0_iter1_reg <= trunc_ln8_reg_473;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln8_reg_473_pp0_iter9_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nibble_V_12_reg_498 <= {{m_axi_gmem1_RDATA[7:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln8_reg_473_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nibble_V_reg_493 <= nibble_V_fu_352_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln331_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln8_7_reg_482 <= {{add_ln8_4_fu_314_p2[14:1]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln331_fu_168_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln331_reg_446 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_accumulator_V_1_load = grp_fu_397_p3;
    end else begin
        ap_sig_allocacmp_accumulator_V_1_load = accumulator_V_1_fu_82;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten309_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten309_load = indvar_flatten309_fu_94;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_input_index_load = 7'd0;
    end else begin
        ap_sig_allocacmp_input_index_load = input_index_fu_86;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_output_index_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_output_index_1 = output_index_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv3_relu_V_ce0 = 1'b1;
    end else begin
        conv3_relu_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc1_acc_V_ce0 = 1'b1;
    end else begin
        fc1_acc_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (ifzero_reg_478_pp0_iter13_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc1_acc_V_we0 = 1'b1;
    end else begin
        fc1_acc_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_397_ce = 1'b1;
    end else begin
        grp_fu_397_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln331_1_fu_174_p2 = (ap_sig_allocacmp_indvar_flatten309_load + 14'd1);

assign add_ln331_fu_308_p2 = ($signed(select_ln331_3_fu_298_p3) + $signed(15'd17782));

assign add_ln332_fu_197_p2 = (ap_sig_allocacmp_output_index_1 + 7'd1);

assign add_ln340_fu_215_p2 = (select_ln331_fu_189_p3 + 7'd1);

assign add_ln8_4_fu_314_p2 = (add_ln331_fu_308_p2 + zext_ln6_fu_305_p1);

assign add_ln8_fu_337_p2 = (zext_ln8_fu_333_p1 + weight);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_relu_V_address0 = trunc_ln344_1_cast132_fu_348_p1;

assign fc1_acc_V_address0 = zext_ln331_fu_389_p1;

assign fc1_acc_V_d0 = grp_fu_397_p3;

assign grp_fu_397_p0 = grp_fu_397_p00;

assign grp_fu_397_p00 = conv3_relu_V_q0;

assign grp_fu_397_p2 = ((icmp_ln339_reg_450_pp0_iter12_reg[0:0] == 1'b1) ? 14'd0 : ap_sig_allocacmp_accumulator_V_1_load);

assign icmp_ln331_fu_168_p2 = ((ap_sig_allocacmp_indvar_flatten309_load == 14'd10080) ? 1'b1 : 1'b0);

assign icmp_ln339_fu_183_p2 = ((ap_sig_allocacmp_input_index_load == 7'd120) ? 1'b1 : 1'b0);

assign ifzero_fu_221_p2 = ((add_ln340_fu_215_p2 == 7'd120) ? 1'b1 : 1'b0);

assign m_axi_gmem1_ARADDR = gmem1_addr_reg_487;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd1;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 8'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 1'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign nibble_V_14_fu_366_p3 = ((trunc_ln8_reg_473_pp0_iter10_reg[0:0] == 1'b1) ? nibble_V_12_reg_498 : nibble_V_reg_493);

assign nibble_V_fu_352_p1 = m_axi_gmem1_RDATA[3:0];

assign p_shl11_fu_253_p3 = {{output_index_1_reg_440}, {3'd0}};

assign p_shl31_cast_fu_249_p1 = p_shl_fu_242_p3;

assign p_shl31_cast_mid1_fu_277_p1 = p_shl31_mid1_fu_270_p3;

assign p_shl31_mid1_fu_270_p3 = {{add_ln332_reg_462}, {7'd0}};

assign p_shl32_cast_fu_260_p1 = p_shl11_fu_253_p3;

assign p_shl32_cast_mid1_fu_288_p1 = p_shl32_mid1_fu_281_p3;

assign p_shl32_mid1_fu_281_p3 = {{add_ln332_reg_462}, {3'd0}};

assign p_shl_fu_242_p3 = {{output_index_1_reg_440}, {7'd0}};

assign select_ln331_2_fu_203_p3 = ((icmp_ln339_fu_183_p2[0:0] == 1'b1) ? add_ln332_fu_197_p2 : ap_sig_allocacmp_output_index_1);

assign select_ln331_3_fu_298_p3 = ((icmp_ln339_reg_450[0:0] == 1'b1) ? sub_ln344_1_fu_292_p2 : sub_ln344_fu_264_p2);

assign select_ln331_fu_189_p3 = ((icmp_ln339_fu_183_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_input_index_load);

assign sext_ln8_fu_330_p1 = $signed(trunc_ln8_7_reg_482);

assign sub_ln344_1_fu_292_p2 = (p_shl31_cast_mid1_fu_277_p1 - p_shl32_cast_mid1_fu_288_p1);

assign sub_ln344_fu_264_p2 = (p_shl31_cast_fu_249_p1 - p_shl32_cast_fu_260_p1);

assign trunc_ln344_1_cast132_fu_348_p1 = select_ln331_reg_456_pp0_iter9_reg;

assign trunc_ln8_fu_211_p1 = select_ln331_fu_189_p3[0:0];

assign zext_ln331_fu_389_p1 = select_ln331_2_reg_468_pp0_iter13_reg;

assign zext_ln6_fu_305_p1 = select_ln331_reg_456;

assign zext_ln8_fu_333_p1 = $unsigned(sext_ln8_fu_330_p1);

endmodule //lenet_w4a4_top_lenet_w4a4_top_Pipeline_DENSE_OUTPUT_DENSE_INPUT
