// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_output_address0,
        conv2_output_ce0,
        conv2_output_q0,
        conv2_output_address1,
        conv2_output_ce1,
        conv2_output_q1,
        conv2_output_address2,
        conv2_output_ce2,
        conv2_output_q2,
        conv2_output_address3,
        conv2_output_ce3,
        conv2_output_q3,
        pool2_output_address0,
        pool2_output_ce0,
        pool2_output_we0,
        pool2_output_d0,
        grp_fu_1410_p_din0,
        grp_fu_1410_p_din1,
        grp_fu_1410_p_opcode,
        grp_fu_1410_p_dout0,
        grp_fu_1410_p_ce,
        grp_fu_1414_p_din0,
        grp_fu_1414_p_din1,
        grp_fu_1414_p_opcode,
        grp_fu_1414_p_dout0,
        grp_fu_1414_p_ce,
        grp_fu_1418_p_din0,
        grp_fu_1418_p_din1,
        grp_fu_1418_p_opcode,
        grp_fu_1418_p_dout0,
        grp_fu_1418_p_ce,
        grp_fu_1422_p_din0,
        grp_fu_1422_p_din1,
        grp_fu_1422_p_opcode,
        grp_fu_1422_p_dout0,
        grp_fu_1422_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] conv2_output_address0;
output   conv2_output_ce0;
input  [31:0] conv2_output_q0;
output  [10:0] conv2_output_address1;
output   conv2_output_ce1;
input  [31:0] conv2_output_q1;
output  [10:0] conv2_output_address2;
output   conv2_output_ce2;
input  [31:0] conv2_output_q2;
output  [10:0] conv2_output_address3;
output   conv2_output_ce3;
input  [31:0] conv2_output_q3;
output  [8:0] pool2_output_address0;
output   pool2_output_ce0;
output   pool2_output_we0;
output  [31:0] pool2_output_d0;
output  [31:0] grp_fu_1410_p_din0;
output  [31:0] grp_fu_1410_p_din1;
output  [4:0] grp_fu_1410_p_opcode;
input  [0:0] grp_fu_1410_p_dout0;
output   grp_fu_1410_p_ce;
output  [31:0] grp_fu_1414_p_din0;
output  [31:0] grp_fu_1414_p_din1;
output  [4:0] grp_fu_1414_p_opcode;
input  [0:0] grp_fu_1414_p_dout0;
output   grp_fu_1414_p_ce;
output  [31:0] grp_fu_1418_p_din0;
output  [31:0] grp_fu_1418_p_din1;
output  [4:0] grp_fu_1418_p_opcode;
input  [0:0] grp_fu_1418_p_dout0;
output   grp_fu_1418_p_ce;
output  [31:0] grp_fu_1422_p_din0;
output  [31:0] grp_fu_1422_p_din1;
output  [4:0] grp_fu_1422_p_opcode;
input  [0:0] grp_fu_1422_p_dout0;
output   grp_fu_1422_p_ce;

reg ap_idle;
reg conv2_output_ce0;
reg conv2_output_ce1;
reg conv2_output_ce2;
reg conv2_output_ce3;
reg pool2_output_ce0;
reg pool2_output_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln91_fu_214_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] output_row_1_reg_1089;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln91_reg_1095;
reg   [0:0] icmp_ln91_reg_1095_pp0_iter1_reg;
wire   [0:0] icmp_ln93_fu_232_p2;
reg   [0:0] icmp_ln93_reg_1099;
reg   [0:0] icmp_ln93_reg_1099_pp0_iter1_reg;
wire   [0:0] and_ln91_fu_258_p2;
reg   [0:0] and_ln91_reg_1109;
reg   [0:0] and_ln91_reg_1109_pp0_iter1_reg;
wire   [2:0] add_ln93_fu_264_p2;
reg   [2:0] add_ln93_reg_1115;
wire   [2:0] select_ln93_fu_276_p3;
reg   [2:0] select_ln93_reg_1121;
reg   [2:0] select_ln93_reg_1121_pp0_iter1_reg;
wire   [3:0] empty_fu_335_p1;
reg   [3:0] empty_reg_1127;
wire   [4:0] tmp3_fu_375_p2;
reg   [4:0] tmp3_reg_1132;
wire   [4:0] add_ln91_fu_397_p2;
reg   [4:0] add_ln91_reg_1137;
wire   [3:0] empty_33_fu_403_p1;
reg   [3:0] empty_33_reg_1142;
wire   [4:0] tmp3_mid1_fu_485_p2;
reg   [4:0] tmp3_mid1_reg_1147;
wire   [7:0] select_ln93_2_fu_507_p3;
reg   [7:0] select_ln93_2_reg_1152;
wire   [8:0] add_ln114_1_fu_732_p2;
reg   [8:0] add_ln114_1_reg_1179;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter3_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter4_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter5_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter6_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter7_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter8_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter9_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter10_reg;
reg   [8:0] add_ln114_1_reg_1179_pp0_iter11_reg;
reg   [31:0] conv2_output_load_reg_1184;
reg   [31:0] conv2_output_load_reg_1184_pp0_iter4_reg;
reg   [31:0] conv2_output_load_1_reg_1191;
reg   [31:0] conv2_output_load_1_reg_1191_pp0_iter4_reg;
reg   [31:0] conv2_output_load_1_reg_1191_pp0_iter5_reg;
reg   [31:0] conv2_output_load_1_reg_1191_pp0_iter6_reg;
reg   [31:0] conv2_output_load_2_reg_1198;
reg   [31:0] conv2_output_load_2_reg_1198_pp0_iter4_reg;
reg   [31:0] conv2_output_load_2_reg_1198_pp0_iter5_reg;
reg   [31:0] conv2_output_load_2_reg_1198_pp0_iter6_reg;
reg   [31:0] conv2_output_load_2_reg_1198_pp0_iter7_reg;
reg   [31:0] conv2_output_load_2_reg_1198_pp0_iter8_reg;
reg   [31:0] conv2_output_load_3_reg_1205;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter4_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter5_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter6_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter7_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter8_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter9_reg;
reg   [31:0] conv2_output_load_3_reg_1205_pp0_iter10_reg;
wire   [31:0] select_ln107_fu_779_p3;
reg   [31:0] select_ln107_reg_1212;
reg   [31:0] select_ln107_reg_1212_pp0_iter6_reg;
wire   [31:0] select_ln107_1_fu_868_p3;
reg   [31:0] select_ln107_1_reg_1219;
reg   [31:0] select_ln107_1_reg_1219_pp0_iter8_reg;
wire   [31:0] select_ln107_2_fu_956_p3;
reg   [31:0] select_ln107_2_reg_1226;
reg   [31:0] select_ln107_2_reg_1226_pp0_iter10_reg;
wire   [31:0] select_ln107_3_fu_1044_p3;
reg   [31:0] select_ln107_3_reg_1233;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln106_fu_674_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln106_1_fu_685_p1;
wire   [63:0] zext_ln106_2_fu_706_p1;
wire   [63:0] zext_ln106_3_fu_717_p1;
wire   [63:0] zext_ln115_fu_1050_p1;
reg   [2:0] output_col_fu_84;
wire   [2:0] add_ln95_fu_292_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_output_col_load;
reg   [2:0] output_row_fu_88;
wire   [2:0] select_ln93_3_fu_284_p3;
reg   [2:0] ap_sig_allocacmp_output_row_1;
reg   [5:0] indvar_flatten127_fu_92;
wire   [5:0] select_ln93_4_fu_304_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten127_load;
reg   [4:0] channel_fu_96;
wire   [4:0] select_ln91_6_fu_464_p3;
reg   [8:0] indvar_flatten183_fu_100;
wire   [8:0] add_ln91_1_fu_220_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten183_load;
wire   [0:0] icmp_ln95_fu_252_p2;
wire   [0:0] xor_ln91_fu_246_p2;
wire   [2:0] select_ln91_fu_238_p3;
wire   [0:0] or_ln93_fu_270_p2;
wire   [5:0] add_ln93_1_fu_298_p2;
wire   [6:0] p_shl_fu_339_p3;
wire   [4:0] empty_29_fu_351_p2;
wire   [3:0] tmp_s_fu_364_p3;
wire   [4:0] zext_ln93_1_fu_361_p1;
wire   [5:0] p_shl26_cast_fu_357_p1;
wire   [5:0] p_cast38_fu_371_p1;
wire   [5:0] tmp4_fu_381_p2;
wire   [7:0] tmp4_cast_fu_387_p1;
wire   [7:0] p_shl25_cast_fu_347_p1;
wire   [6:0] p_shl25_mid1_fu_407_p3;
wire   [6:0] select_ln91_1_fu_419_p3;
wire   [4:0] empty_34_fu_430_p2;
wire   [4:0] select_ln91_2_fu_436_p3;
wire   [7:0] tmp4_cast_mid1157_fu_447_p1;
wire   [7:0] p_shl25_cast_mid1_fu_415_p1;
wire   [7:0] p_mid1159_fu_451_p2;
wire   [7:0] empty_31_fu_391_p2;
wire   [3:0] p_mid2_fu_474_p3;
wire   [4:0] zext_ln93_3_fu_471_p1;
wire   [5:0] zext_ln91_2_fu_443_p1;
wire   [5:0] p_cast38_mid1_fu_481_p1;
wire   [5:0] tmp4_mid1_fu_491_p2;
wire   [7:0] tmp4_cast_mid1_fu_497_p1;
wire   [7:0] zext_ln91_1_fu_426_p1;
wire   [7:0] p_mid1123_fu_501_p2;
wire   [7:0] select_ln91_5_fu_457_p3;
wire   [5:0] p_shl1_fu_519_p3;
wire   [6:0] tmp3_cast_fu_530_p1;
wire   [6:0] zext_ln93_fu_526_p1;
wire   [5:0] p_shl24_mid1_fu_542_p3;
wire   [5:0] select_ln91_3_fu_553_p3;
wire   [6:0] zext_ln91_fu_539_p1;
wire   [6:0] zext_ln93_2_fu_549_p1;
wire   [6:0] p_mid1149_fu_564_p2;
wire   [6:0] empty_30_fu_533_p2;
wire   [6:0] tmp3_cast_mid1_fu_577_p1;
wire   [6:0] zext_ln91_3_fu_560_p1;
wire   [6:0] p_mid1121_fu_580_p2;
wire   [6:0] select_ln91_4_fu_570_p3;
wire   [6:0] select_ln93_1_fu_586_p3;
wire   [7:0] or_ln93_1_fu_615_p2;
wire   [8:0] zext_ln95_mid2_v_fu_628_p3;
wire   [3:0] tmp_3_fu_643_p3;
wire   [8:0] p_shl29_0_mid2_fu_608_p3;
wire   [8:0] zext_ln105_1_fu_654_p1;
wire   [8:0] add_ln105_fu_658_p2;
wire   [10:0] zext_ln105_2_fu_664_p1;
wire   [10:0] p_shl28_0_mid2_fu_601_p3;
wire   [10:0] add_ln105_1_fu_668_p2;
wire   [10:0] or_ln105_fu_679_p2;
wire   [9:0] zext_ln93_4_fu_636_p1;
wire   [9:0] zext_ln105_fu_650_p1;
wire   [9:0] add_ln105_2_fu_690_p2;
wire   [10:0] zext_ln105_3_fu_696_p1;
wire   [10:0] p_shl28_1_mid2_fu_620_p3;
wire   [10:0] add_ln105_3_fu_700_p2;
wire   [10:0] or_ln105_1_fu_711_p2;
wire   [6:0] output_col_2_cast51_fu_640_p1;
wire   [6:0] add_ln114_fu_722_p2;
wire   [8:0] zext_ln114_fu_728_p1;
wire   [8:0] p_shl27_mid2_fu_593_p3;
wire   [31:0] bitcast_ln107_fu_738_p1;
wire   [7:0] tmp_4_fu_741_p4;
wire   [22:0] trunc_ln107_fu_751_p1;
wire   [0:0] icmp_ln107_1_fu_761_p2;
wire   [0:0] icmp_ln107_fu_755_p2;
wire   [0:0] or_ln107_fu_767_p2;
wire   [0:0] and_ln107_fu_773_p2;
wire   [31:0] bitcast_ln107_1_fu_786_p1;
wire   [31:0] bitcast_ln107_2_fu_803_p1;
wire   [7:0] tmp_6_fu_789_p4;
wire   [22:0] trunc_ln107_1_fu_799_p1;
wire   [0:0] icmp_ln107_3_fu_826_p2;
wire   [0:0] icmp_ln107_2_fu_820_p2;
wire   [7:0] tmp_7_fu_806_p4;
wire   [22:0] trunc_ln107_2_fu_816_p1;
wire   [0:0] icmp_ln107_5_fu_844_p2;
wire   [0:0] icmp_ln107_4_fu_838_p2;
wire   [0:0] or_ln107_1_fu_832_p2;
wire   [0:0] or_ln107_2_fu_850_p2;
wire   [0:0] and_ln107_1_fu_856_p2;
wire   [0:0] and_ln107_2_fu_862_p2;
wire   [31:0] bitcast_ln107_3_fu_874_p1;
wire   [31:0] bitcast_ln107_4_fu_891_p1;
wire   [7:0] tmp_9_fu_877_p4;
wire   [22:0] trunc_ln107_3_fu_887_p1;
wire   [0:0] icmp_ln107_7_fu_914_p2;
wire   [0:0] icmp_ln107_6_fu_908_p2;
wire   [7:0] tmp_10_fu_894_p4;
wire   [22:0] trunc_ln107_4_fu_904_p1;
wire   [0:0] icmp_ln107_9_fu_932_p2;
wire   [0:0] icmp_ln107_8_fu_926_p2;
wire   [0:0] or_ln107_3_fu_920_p2;
wire   [0:0] or_ln107_4_fu_938_p2;
wire   [0:0] and_ln107_3_fu_944_p2;
wire   [0:0] and_ln107_4_fu_950_p2;
wire   [31:0] bitcast_ln107_5_fu_962_p1;
wire   [31:0] bitcast_ln107_6_fu_979_p1;
wire   [7:0] tmp_12_fu_965_p4;
wire   [22:0] trunc_ln107_5_fu_975_p1;
wire   [0:0] icmp_ln107_11_fu_1002_p2;
wire   [0:0] icmp_ln107_10_fu_996_p2;
wire   [7:0] tmp_13_fu_982_p4;
wire   [22:0] trunc_ln107_6_fu_992_p1;
wire   [0:0] icmp_ln107_13_fu_1020_p2;
wire   [0:0] icmp_ln107_12_fu_1014_p2;
wire   [0:0] or_ln107_5_fu_1008_p2;
wire   [0:0] or_ln107_6_fu_1026_p2;
wire   [0:0] and_ln107_5_fu_1032_p2;
wire   [0:0] and_ln107_6_fu_1038_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_full_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            channel_fu_96 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln91_reg_1095 == 1'd0))) begin
            channel_fu_96 <= select_ln91_6_fu_464_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten127_fu_92 <= select_ln93_4_fu_304_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten127_fu_92 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten183_fu_100 <= add_ln91_1_fu_220_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten183_fu_100 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_col_fu_84 <= add_ln95_fu_292_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            output_col_fu_84 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_row_fu_88 <= select_ln93_3_fu_284_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            output_row_fu_88 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln91_reg_1095_pp0_iter1_reg == 1'd0))) begin
        add_ln114_1_reg_1179 <= add_ln114_1_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln114_1_reg_1179_pp0_iter10_reg <= add_ln114_1_reg_1179_pp0_iter9_reg;
        add_ln114_1_reg_1179_pp0_iter11_reg <= add_ln114_1_reg_1179_pp0_iter10_reg;
        add_ln114_1_reg_1179_pp0_iter3_reg <= add_ln114_1_reg_1179;
        add_ln114_1_reg_1179_pp0_iter4_reg <= add_ln114_1_reg_1179_pp0_iter3_reg;
        add_ln114_1_reg_1179_pp0_iter5_reg <= add_ln114_1_reg_1179_pp0_iter4_reg;
        add_ln114_1_reg_1179_pp0_iter6_reg <= add_ln114_1_reg_1179_pp0_iter5_reg;
        add_ln114_1_reg_1179_pp0_iter7_reg <= add_ln114_1_reg_1179_pp0_iter6_reg;
        add_ln114_1_reg_1179_pp0_iter8_reg <= add_ln114_1_reg_1179_pp0_iter7_reg;
        add_ln114_1_reg_1179_pp0_iter9_reg <= add_ln114_1_reg_1179_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv2_output_load_1_reg_1191_pp0_iter4_reg <= conv2_output_load_1_reg_1191;
        conv2_output_load_1_reg_1191_pp0_iter5_reg <= conv2_output_load_1_reg_1191_pp0_iter4_reg;
        conv2_output_load_1_reg_1191_pp0_iter6_reg <= conv2_output_load_1_reg_1191_pp0_iter5_reg;
        conv2_output_load_2_reg_1198_pp0_iter4_reg <= conv2_output_load_2_reg_1198;
        conv2_output_load_2_reg_1198_pp0_iter5_reg <= conv2_output_load_2_reg_1198_pp0_iter4_reg;
        conv2_output_load_2_reg_1198_pp0_iter6_reg <= conv2_output_load_2_reg_1198_pp0_iter5_reg;
        conv2_output_load_2_reg_1198_pp0_iter7_reg <= conv2_output_load_2_reg_1198_pp0_iter6_reg;
        conv2_output_load_2_reg_1198_pp0_iter8_reg <= conv2_output_load_2_reg_1198_pp0_iter7_reg;
        conv2_output_load_3_reg_1205_pp0_iter10_reg <= conv2_output_load_3_reg_1205_pp0_iter9_reg;
        conv2_output_load_3_reg_1205_pp0_iter4_reg <= conv2_output_load_3_reg_1205;
        conv2_output_load_3_reg_1205_pp0_iter5_reg <= conv2_output_load_3_reg_1205_pp0_iter4_reg;
        conv2_output_load_3_reg_1205_pp0_iter6_reg <= conv2_output_load_3_reg_1205_pp0_iter5_reg;
        conv2_output_load_3_reg_1205_pp0_iter7_reg <= conv2_output_load_3_reg_1205_pp0_iter6_reg;
        conv2_output_load_3_reg_1205_pp0_iter8_reg <= conv2_output_load_3_reg_1205_pp0_iter7_reg;
        conv2_output_load_3_reg_1205_pp0_iter9_reg <= conv2_output_load_3_reg_1205_pp0_iter8_reg;
        conv2_output_load_reg_1184_pp0_iter4_reg <= conv2_output_load_reg_1184;
        select_ln107_1_reg_1219 <= select_ln107_1_fu_868_p3;
        select_ln107_1_reg_1219_pp0_iter8_reg <= select_ln107_1_reg_1219;
        select_ln107_2_reg_1226 <= select_ln107_2_fu_956_p3;
        select_ln107_2_reg_1226_pp0_iter10_reg <= select_ln107_2_reg_1226;
        select_ln107_3_reg_1233 <= select_ln107_3_fu_1044_p3;
        select_ln107_reg_1212 <= select_ln107_fu_779_p3;
        select_ln107_reg_1212_pp0_iter6_reg <= select_ln107_reg_1212;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln91_reg_1137 <= add_ln91_fu_397_p2;
        and_ln91_reg_1109_pp0_iter1_reg <= and_ln91_reg_1109;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_1127 <= empty_fu_335_p1;
        icmp_ln91_reg_1095 <= icmp_ln91_fu_214_p2;
        icmp_ln91_reg_1095_pp0_iter1_reg <= icmp_ln91_reg_1095;
        icmp_ln93_reg_1099_pp0_iter1_reg <= icmp_ln93_reg_1099;
        output_row_1_reg_1089 <= ap_sig_allocacmp_output_row_1;
        select_ln93_reg_1121_pp0_iter1_reg <= select_ln93_reg_1121;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln91_fu_214_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln93_reg_1115 <= add_ln93_fu_264_p2;
        and_ln91_reg_1109 <= and_ln91_fu_258_p2;
        icmp_ln93_reg_1099 <= icmp_ln93_fu_232_p2;
        select_ln93_reg_1121 <= select_ln93_fu_276_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv2_output_load_1_reg_1191 <= conv2_output_q2;
        conv2_output_load_2_reg_1198 <= conv2_output_q1;
        conv2_output_load_3_reg_1205 <= conv2_output_q0;
        conv2_output_load_reg_1184 <= conv2_output_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln91_reg_1095 == 1'd0))) begin
        empty_33_reg_1142 <= empty_33_fu_403_p1;
        select_ln93_2_reg_1152[7 : 1] <= select_ln93_2_fu_507_p3[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln91_reg_1109) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln91_reg_1095 == 1'd0))) begin
        tmp3_mid1_reg_1147 <= tmp3_mid1_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == and_ln91_reg_1109) & (icmp_ln93_reg_1099 == 1'd0))) begin
        tmp3_reg_1132 <= tmp3_fu_375_p2;
    end
end

always @ (*) begin
    if (((icmp_ln91_fu_214_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln91_reg_1095_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten127_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten127_load = indvar_flatten127_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten183_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten183_load = indvar_flatten183_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_col_load = 3'd0;
    end else begin
        ap_sig_allocacmp_output_col_load = output_col_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_row_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_output_row_1 = output_row_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_output_ce0 = 1'b1;
    end else begin
        conv2_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_output_ce1 = 1'b1;
    end else begin
        conv2_output_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_output_ce2 = 1'b1;
    end else begin
        conv2_output_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_output_ce3 = 1'b1;
    end else begin
        conv2_output_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        pool2_output_ce0 = 1'b1;
    end else begin
        pool2_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        pool2_output_we0 = 1'b1;
    end else begin
        pool2_output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_1_fu_668_p2 = (zext_ln105_2_fu_664_p1 + p_shl28_0_mid2_fu_601_p3);

assign add_ln105_2_fu_690_p2 = (zext_ln93_4_fu_636_p1 + zext_ln105_fu_650_p1);

assign add_ln105_3_fu_700_p2 = (zext_ln105_3_fu_696_p1 + p_shl28_1_mid2_fu_620_p3);

assign add_ln105_fu_658_p2 = (p_shl29_0_mid2_fu_608_p3 + zext_ln105_1_fu_654_p1);

assign add_ln114_1_fu_732_p2 = (zext_ln114_fu_728_p1 + p_shl27_mid2_fu_593_p3);

assign add_ln114_fu_722_p2 = (select_ln93_1_fu_586_p3 + output_col_2_cast51_fu_640_p1);

assign add_ln91_1_fu_220_p2 = (ap_sig_allocacmp_indvar_flatten183_load + 9'd1);

assign add_ln91_fu_397_p2 = (channel_fu_96 + 5'd1);

assign add_ln93_1_fu_298_p2 = (ap_sig_allocacmp_indvar_flatten127_load + 6'd1);

assign add_ln93_fu_264_p2 = (select_ln91_fu_238_p3 + 3'd1);

assign add_ln95_fu_292_p2 = (select_ln93_fu_276_p3 + 3'd1);

assign and_ln107_1_fu_856_p2 = (or_ln107_2_fu_850_p2 & or_ln107_1_fu_832_p2);

assign and_ln107_2_fu_862_p2 = (grp_fu_1414_p_dout0 & and_ln107_1_fu_856_p2);

assign and_ln107_3_fu_944_p2 = (or_ln107_4_fu_938_p2 & or_ln107_3_fu_920_p2);

assign and_ln107_4_fu_950_p2 = (grp_fu_1418_p_dout0 & and_ln107_3_fu_944_p2);

assign and_ln107_5_fu_1032_p2 = (or_ln107_6_fu_1026_p2 & or_ln107_5_fu_1008_p2);

assign and_ln107_6_fu_1038_p2 = (grp_fu_1422_p_dout0 & and_ln107_5_fu_1032_p2);

assign and_ln107_fu_773_p2 = (or_ln107_fu_767_p2 & grp_fu_1410_p_dout0);

assign and_ln91_fu_258_p2 = (xor_ln91_fu_246_p2 & icmp_ln95_fu_252_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln107_1_fu_786_p1 = conv2_output_load_1_reg_1191_pp0_iter6_reg;

assign bitcast_ln107_2_fu_803_p1 = select_ln107_reg_1212_pp0_iter6_reg;

assign bitcast_ln107_3_fu_874_p1 = conv2_output_load_2_reg_1198_pp0_iter8_reg;

assign bitcast_ln107_4_fu_891_p1 = select_ln107_1_reg_1219_pp0_iter8_reg;

assign bitcast_ln107_5_fu_962_p1 = conv2_output_load_3_reg_1205_pp0_iter10_reg;

assign bitcast_ln107_6_fu_979_p1 = select_ln107_2_reg_1226_pp0_iter10_reg;

assign bitcast_ln107_fu_738_p1 = conv2_output_load_reg_1184_pp0_iter4_reg;

assign conv2_output_address0 = zext_ln106_3_fu_717_p1;

assign conv2_output_address1 = zext_ln106_2_fu_706_p1;

assign conv2_output_address2 = zext_ln106_1_fu_685_p1;

assign conv2_output_address3 = zext_ln106_fu_674_p1;

assign empty_29_fu_351_p2 = channel_fu_96 << 5'd1;

assign empty_30_fu_533_p2 = (tmp3_cast_fu_530_p1 + zext_ln93_fu_526_p1);

assign empty_31_fu_391_p2 = (tmp4_cast_fu_387_p1 + p_shl25_cast_fu_347_p1);

assign empty_33_fu_403_p1 = add_ln91_fu_397_p2[3:0];

assign empty_34_fu_430_p2 = add_ln91_fu_397_p2 << 5'd1;

assign empty_fu_335_p1 = channel_fu_96[3:0];

assign grp_fu_1410_p_ce = 1'b1;

assign grp_fu_1410_p_din0 = conv2_output_load_reg_1184;

assign grp_fu_1410_p_din1 = 32'd0;

assign grp_fu_1410_p_opcode = 5'd2;

assign grp_fu_1414_p_ce = 1'b1;

assign grp_fu_1414_p_din0 = conv2_output_load_1_reg_1191_pp0_iter5_reg;

assign grp_fu_1414_p_din1 = select_ln107_reg_1212;

assign grp_fu_1414_p_opcode = 5'd2;

assign grp_fu_1418_p_ce = 1'b1;

assign grp_fu_1418_p_din0 = conv2_output_load_2_reg_1198_pp0_iter7_reg;

assign grp_fu_1418_p_din1 = select_ln107_1_reg_1219;

assign grp_fu_1418_p_opcode = 5'd2;

assign grp_fu_1422_p_ce = 1'b1;

assign grp_fu_1422_p_din0 = conv2_output_load_3_reg_1205_pp0_iter9_reg;

assign grp_fu_1422_p_din1 = select_ln107_2_reg_1226;

assign grp_fu_1422_p_opcode = 5'd2;

assign icmp_ln107_10_fu_996_p2 = ((tmp_12_fu_965_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_11_fu_1002_p2 = ((trunc_ln107_5_fu_975_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_12_fu_1014_p2 = ((tmp_13_fu_982_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_13_fu_1020_p2 = ((trunc_ln107_6_fu_992_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_1_fu_761_p2 = ((trunc_ln107_fu_751_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_2_fu_820_p2 = ((tmp_6_fu_789_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_3_fu_826_p2 = ((trunc_ln107_1_fu_799_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_4_fu_838_p2 = ((tmp_7_fu_806_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_5_fu_844_p2 = ((trunc_ln107_2_fu_816_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_6_fu_908_p2 = ((tmp_9_fu_877_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_7_fu_914_p2 = ((trunc_ln107_3_fu_887_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_8_fu_926_p2 = ((tmp_10_fu_894_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_9_fu_932_p2 = ((trunc_ln107_4_fu_904_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_755_p2 = ((tmp_4_fu_741_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_214_p2 = ((ap_sig_allocacmp_indvar_flatten183_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_232_p2 = ((ap_sig_allocacmp_indvar_flatten127_load == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_252_p2 = ((ap_sig_allocacmp_output_col_load == 3'd5) ? 1'b1 : 1'b0);

assign or_ln105_1_fu_711_p2 = (11'd1 | add_ln105_3_fu_700_p2);

assign or_ln105_fu_679_p2 = (11'd1 | add_ln105_1_fu_668_p2);

assign or_ln107_1_fu_832_p2 = (icmp_ln107_3_fu_826_p2 | icmp_ln107_2_fu_820_p2);

assign or_ln107_2_fu_850_p2 = (icmp_ln107_5_fu_844_p2 | icmp_ln107_4_fu_838_p2);

assign or_ln107_3_fu_920_p2 = (icmp_ln107_7_fu_914_p2 | icmp_ln107_6_fu_908_p2);

assign or_ln107_4_fu_938_p2 = (icmp_ln107_9_fu_932_p2 | icmp_ln107_8_fu_926_p2);

assign or_ln107_5_fu_1008_p2 = (icmp_ln107_11_fu_1002_p2 | icmp_ln107_10_fu_996_p2);

assign or_ln107_6_fu_1026_p2 = (icmp_ln107_13_fu_1020_p2 | icmp_ln107_12_fu_1014_p2);

assign or_ln107_fu_767_p2 = (icmp_ln107_fu_755_p2 | icmp_ln107_1_fu_761_p2);

assign or_ln93_1_fu_615_p2 = (select_ln93_2_reg_1152 | 8'd1);

assign or_ln93_fu_270_p2 = (icmp_ln93_fu_232_p2 | and_ln91_fu_258_p2);

assign output_col_2_cast51_fu_640_p1 = select_ln93_reg_1121_pp0_iter1_reg;

assign p_cast38_fu_371_p1 = tmp_s_fu_364_p3;

assign p_cast38_mid1_fu_481_p1 = p_mid2_fu_474_p3;

assign p_mid1121_fu_580_p2 = (tmp3_cast_mid1_fu_577_p1 + zext_ln91_3_fu_560_p1);

assign p_mid1123_fu_501_p2 = (tmp4_cast_mid1_fu_497_p1 + zext_ln91_1_fu_426_p1);

assign p_mid1149_fu_564_p2 = (zext_ln91_fu_539_p1 + zext_ln93_2_fu_549_p1);

assign p_mid1159_fu_451_p2 = (tmp4_cast_mid1157_fu_447_p1 + p_shl25_cast_mid1_fu_415_p1);

assign p_mid2_fu_474_p3 = {{add_ln93_reg_1115}, {1'd0}};

assign p_shl1_fu_519_p3 = {{empty_reg_1127}, {2'd0}};

assign p_shl24_mid1_fu_542_p3 = {{empty_33_reg_1142}, {2'd0}};

assign p_shl25_cast_fu_347_p1 = p_shl_fu_339_p3;

assign p_shl25_cast_mid1_fu_415_p1 = p_shl25_mid1_fu_407_p3;

assign p_shl25_mid1_fu_407_p3 = {{empty_33_fu_403_p1}, {3'd0}};

assign p_shl26_cast_fu_357_p1 = empty_29_fu_351_p2;

assign p_shl27_mid2_fu_593_p3 = {{select_ln93_1_fu_586_p3}, {2'd0}};

assign p_shl28_0_mid2_fu_601_p3 = {{select_ln93_2_reg_1152}, {3'd0}};

assign p_shl28_1_mid2_fu_620_p3 = {{or_ln93_1_fu_615_p2}, {3'd0}};

assign p_shl29_0_mid2_fu_608_p3 = {{select_ln93_2_reg_1152}, {1'd0}};

assign p_shl_fu_339_p3 = {{empty_fu_335_p1}, {3'd0}};

assign pool2_output_address0 = zext_ln115_fu_1050_p1;

assign pool2_output_d0 = select_ln107_3_reg_1233;

assign select_ln107_1_fu_868_p3 = ((and_ln107_2_fu_862_p2[0:0] == 1'b1) ? conv2_output_load_1_reg_1191_pp0_iter6_reg : select_ln107_reg_1212_pp0_iter6_reg);

assign select_ln107_2_fu_956_p3 = ((and_ln107_4_fu_950_p2[0:0] == 1'b1) ? conv2_output_load_2_reg_1198_pp0_iter8_reg : select_ln107_1_reg_1219_pp0_iter8_reg);

assign select_ln107_3_fu_1044_p3 = ((and_ln107_6_fu_1038_p2[0:0] == 1'b1) ? conv2_output_load_3_reg_1205_pp0_iter10_reg : select_ln107_2_reg_1226_pp0_iter10_reg);

assign select_ln107_fu_779_p3 = ((and_ln107_fu_773_p2[0:0] == 1'b1) ? conv2_output_load_reg_1184_pp0_iter4_reg : 32'd0);

assign select_ln91_1_fu_419_p3 = ((icmp_ln93_reg_1099[0:0] == 1'b1) ? p_shl25_mid1_fu_407_p3 : p_shl_fu_339_p3);

assign select_ln91_2_fu_436_p3 = ((icmp_ln93_reg_1099[0:0] == 1'b1) ? empty_34_fu_430_p2 : empty_29_fu_351_p2);

assign select_ln91_3_fu_553_p3 = ((icmp_ln93_reg_1099_pp0_iter1_reg[0:0] == 1'b1) ? p_shl24_mid1_fu_542_p3 : p_shl1_fu_519_p3);

assign select_ln91_4_fu_570_p3 = ((icmp_ln93_reg_1099_pp0_iter1_reg[0:0] == 1'b1) ? p_mid1149_fu_564_p2 : empty_30_fu_533_p2);

assign select_ln91_5_fu_457_p3 = ((icmp_ln93_reg_1099[0:0] == 1'b1) ? p_mid1159_fu_451_p2 : empty_31_fu_391_p2);

assign select_ln91_6_fu_464_p3 = ((icmp_ln93_reg_1099[0:0] == 1'b1) ? add_ln91_fu_397_p2 : channel_fu_96);

assign select_ln91_fu_238_p3 = ((icmp_ln93_fu_232_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_output_row_1);

assign select_ln93_1_fu_586_p3 = ((and_ln91_reg_1109_pp0_iter1_reg[0:0] == 1'b1) ? p_mid1121_fu_580_p2 : select_ln91_4_fu_570_p3);

assign select_ln93_2_fu_507_p3 = ((and_ln91_reg_1109[0:0] == 1'b1) ? p_mid1123_fu_501_p2 : select_ln91_5_fu_457_p3);

assign select_ln93_3_fu_284_p3 = ((and_ln91_fu_258_p2[0:0] == 1'b1) ? add_ln93_fu_264_p2 : select_ln91_fu_238_p3);

assign select_ln93_4_fu_304_p3 = ((icmp_ln93_fu_232_p2[0:0] == 1'b1) ? 6'd1 : add_ln93_1_fu_298_p2);

assign select_ln93_fu_276_p3 = ((or_ln93_fu_270_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_output_col_load);

assign tmp3_cast_fu_530_p1 = tmp3_reg_1132;

assign tmp3_cast_mid1_fu_577_p1 = tmp3_mid1_reg_1147;

assign tmp3_fu_375_p2 = (channel_fu_96 + zext_ln93_1_fu_361_p1);

assign tmp3_mid1_fu_485_p2 = (select_ln91_6_fu_464_p3 + zext_ln93_3_fu_471_p1);

assign tmp4_cast_fu_387_p1 = tmp4_fu_381_p2;

assign tmp4_cast_mid1157_fu_447_p1 = empty_34_fu_430_p2;

assign tmp4_cast_mid1_fu_497_p1 = tmp4_mid1_fu_491_p2;

assign tmp4_fu_381_p2 = (p_shl26_cast_fu_357_p1 + p_cast38_fu_371_p1);

assign tmp4_mid1_fu_491_p2 = (zext_ln91_2_fu_443_p1 + p_cast38_mid1_fu_481_p1);

assign tmp_10_fu_894_p4 = {{bitcast_ln107_4_fu_891_p1[30:23]}};

assign tmp_12_fu_965_p4 = {{bitcast_ln107_5_fu_962_p1[30:23]}};

assign tmp_13_fu_982_p4 = {{bitcast_ln107_6_fu_979_p1[30:23]}};

assign tmp_3_fu_643_p3 = {{select_ln93_reg_1121_pp0_iter1_reg}, {1'd0}};

assign tmp_4_fu_741_p4 = {{bitcast_ln107_fu_738_p1[30:23]}};

assign tmp_6_fu_789_p4 = {{bitcast_ln107_1_fu_786_p1[30:23]}};

assign tmp_7_fu_806_p4 = {{bitcast_ln107_2_fu_803_p1[30:23]}};

assign tmp_9_fu_877_p4 = {{bitcast_ln107_3_fu_874_p1[30:23]}};

assign tmp_s_fu_364_p3 = {{output_row_1_reg_1089}, {1'd0}};

assign trunc_ln107_1_fu_799_p1 = bitcast_ln107_1_fu_786_p1[22:0];

assign trunc_ln107_2_fu_816_p1 = bitcast_ln107_2_fu_803_p1[22:0];

assign trunc_ln107_3_fu_887_p1 = bitcast_ln107_3_fu_874_p1[22:0];

assign trunc_ln107_4_fu_904_p1 = bitcast_ln107_4_fu_891_p1[22:0];

assign trunc_ln107_5_fu_975_p1 = bitcast_ln107_5_fu_962_p1[22:0];

assign trunc_ln107_6_fu_992_p1 = bitcast_ln107_6_fu_979_p1[22:0];

assign trunc_ln107_fu_751_p1 = bitcast_ln107_fu_738_p1[22:0];

assign xor_ln91_fu_246_p2 = (icmp_ln93_fu_232_p2 ^ 1'd1);

assign zext_ln105_1_fu_654_p1 = tmp_3_fu_643_p3;

assign zext_ln105_2_fu_664_p1 = add_ln105_fu_658_p2;

assign zext_ln105_3_fu_696_p1 = add_ln105_2_fu_690_p2;

assign zext_ln105_fu_650_p1 = tmp_3_fu_643_p3;

assign zext_ln106_1_fu_685_p1 = or_ln105_fu_679_p2;

assign zext_ln106_2_fu_706_p1 = add_ln105_3_fu_700_p2;

assign zext_ln106_3_fu_717_p1 = or_ln105_1_fu_711_p2;

assign zext_ln106_fu_674_p1 = add_ln105_1_fu_668_p2;

assign zext_ln114_fu_728_p1 = add_ln114_fu_722_p2;

assign zext_ln115_fu_1050_p1 = add_ln114_1_reg_1179_pp0_iter11_reg;

assign zext_ln91_1_fu_426_p1 = select_ln91_1_fu_419_p3;

assign zext_ln91_2_fu_443_p1 = select_ln91_2_fu_436_p3;

assign zext_ln91_3_fu_560_p1 = select_ln91_3_fu_553_p3;

assign zext_ln91_fu_539_p1 = add_ln91_reg_1137;

assign zext_ln93_1_fu_361_p1 = output_row_1_reg_1089;

assign zext_ln93_2_fu_549_p1 = p_shl24_mid1_fu_542_p3;

assign zext_ln93_3_fu_471_p1 = add_ln93_reg_1115;

assign zext_ln93_4_fu_636_p1 = zext_ln95_mid2_v_fu_628_p3;

assign zext_ln93_fu_526_p1 = p_shl1_fu_519_p3;

assign zext_ln95_mid2_v_fu_628_p3 = {{or_ln93_1_fu_615_p2}, {1'd0}};

always @ (posedge ap_clk) begin
    select_ln93_2_reg_1152[0] <= 1'b0;
end

endmodule //lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL1
