// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_anonymous_namespace_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_in_address0,
        feature_in_ce0,
        feature_in_q0,
        m_axi_weight_AWVALID,
        m_axi_weight_AWREADY,
        m_axi_weight_AWADDR,
        m_axi_weight_AWID,
        m_axi_weight_AWLEN,
        m_axi_weight_AWSIZE,
        m_axi_weight_AWBURST,
        m_axi_weight_AWLOCK,
        m_axi_weight_AWCACHE,
        m_axi_weight_AWPROT,
        m_axi_weight_AWQOS,
        m_axi_weight_AWREGION,
        m_axi_weight_AWUSER,
        m_axi_weight_WVALID,
        m_axi_weight_WREADY,
        m_axi_weight_WDATA,
        m_axi_weight_WSTRB,
        m_axi_weight_WLAST,
        m_axi_weight_WID,
        m_axi_weight_WUSER,
        m_axi_weight_ARVALID,
        m_axi_weight_ARREADY,
        m_axi_weight_ARADDR,
        m_axi_weight_ARID,
        m_axi_weight_ARLEN,
        m_axi_weight_ARSIZE,
        m_axi_weight_ARBURST,
        m_axi_weight_ARLOCK,
        m_axi_weight_ARCACHE,
        m_axi_weight_ARPROT,
        m_axi_weight_ARQOS,
        m_axi_weight_ARREGION,
        m_axi_weight_ARUSER,
        m_axi_weight_RVALID,
        m_axi_weight_RREADY,
        m_axi_weight_RDATA,
        m_axi_weight_RLAST,
        m_axi_weight_RID,
        m_axi_weight_RUSER,
        m_axi_weight_RRESP,
        m_axi_weight_BVALID,
        m_axi_weight_BREADY,
        m_axi_weight_BRESP,
        m_axi_weight_BID,
        m_axi_weight_BUSER,
        weight_offset,
        m_axi_bias_AWVALID,
        m_axi_bias_AWREADY,
        m_axi_bias_AWADDR,
        m_axi_bias_AWID,
        m_axi_bias_AWLEN,
        m_axi_bias_AWSIZE,
        m_axi_bias_AWBURST,
        m_axi_bias_AWLOCK,
        m_axi_bias_AWCACHE,
        m_axi_bias_AWPROT,
        m_axi_bias_AWQOS,
        m_axi_bias_AWREGION,
        m_axi_bias_AWUSER,
        m_axi_bias_WVALID,
        m_axi_bias_WREADY,
        m_axi_bias_WDATA,
        m_axi_bias_WSTRB,
        m_axi_bias_WLAST,
        m_axi_bias_WID,
        m_axi_bias_WUSER,
        m_axi_bias_ARVALID,
        m_axi_bias_ARREADY,
        m_axi_bias_ARADDR,
        m_axi_bias_ARID,
        m_axi_bias_ARLEN,
        m_axi_bias_ARSIZE,
        m_axi_bias_ARBURST,
        m_axi_bias_ARLOCK,
        m_axi_bias_ARCACHE,
        m_axi_bias_ARPROT,
        m_axi_bias_ARQOS,
        m_axi_bias_ARREGION,
        m_axi_bias_ARUSER,
        m_axi_bias_RVALID,
        m_axi_bias_RREADY,
        m_axi_bias_RDATA,
        m_axi_bias_RLAST,
        m_axi_bias_RID,
        m_axi_bias_RUSER,
        m_axi_bias_RRESP,
        m_axi_bias_BVALID,
        m_axi_bias_BREADY,
        m_axi_bias_BRESP,
        m_axi_bias_BID,
        m_axi_bias_BUSER,
        bias_offset,
        feature_out_address0,
        feature_out_ce0,
        feature_out_we0,
        feature_out_d0
);

parameter    ap_ST_fsm_state1 = 30'd1;
parameter    ap_ST_fsm_state2 = 30'd2;
parameter    ap_ST_fsm_state3 = 30'd4;
parameter    ap_ST_fsm_state4 = 30'd8;
parameter    ap_ST_fsm_state5 = 30'd16;
parameter    ap_ST_fsm_state6 = 30'd32;
parameter    ap_ST_fsm_state7 = 30'd64;
parameter    ap_ST_fsm_state8 = 30'd128;
parameter    ap_ST_fsm_state9 = 30'd256;
parameter    ap_ST_fsm_state10 = 30'd512;
parameter    ap_ST_fsm_state11 = 30'd1024;
parameter    ap_ST_fsm_state12 = 30'd2048;
parameter    ap_ST_fsm_state13 = 30'd4096;
parameter    ap_ST_fsm_state14 = 30'd8192;
parameter    ap_ST_fsm_state15 = 30'd16384;
parameter    ap_ST_fsm_state16 = 30'd32768;
parameter    ap_ST_fsm_state17 = 30'd65536;
parameter    ap_ST_fsm_state18 = 30'd131072;
parameter    ap_ST_fsm_state19 = 30'd262144;
parameter    ap_ST_fsm_state20 = 30'd524288;
parameter    ap_ST_fsm_state21 = 30'd1048576;
parameter    ap_ST_fsm_state22 = 30'd2097152;
parameter    ap_ST_fsm_state23 = 30'd4194304;
parameter    ap_ST_fsm_state24 = 30'd8388608;
parameter    ap_ST_fsm_state25 = 30'd16777216;
parameter    ap_ST_fsm_state26 = 30'd33554432;
parameter    ap_ST_fsm_state27 = 30'd67108864;
parameter    ap_ST_fsm_state28 = 30'd134217728;
parameter    ap_ST_fsm_state29 = 30'd268435456;
parameter    ap_ST_fsm_state30 = 30'd536870912;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] feature_in_address0;
output   feature_in_ce0;
input  [31:0] feature_in_q0;
output   m_axi_weight_AWVALID;
input   m_axi_weight_AWREADY;
output  [31:0] m_axi_weight_AWADDR;
output  [0:0] m_axi_weight_AWID;
output  [31:0] m_axi_weight_AWLEN;
output  [2:0] m_axi_weight_AWSIZE;
output  [1:0] m_axi_weight_AWBURST;
output  [1:0] m_axi_weight_AWLOCK;
output  [3:0] m_axi_weight_AWCACHE;
output  [2:0] m_axi_weight_AWPROT;
output  [3:0] m_axi_weight_AWQOS;
output  [3:0] m_axi_weight_AWREGION;
output  [0:0] m_axi_weight_AWUSER;
output   m_axi_weight_WVALID;
input   m_axi_weight_WREADY;
output  [31:0] m_axi_weight_WDATA;
output  [3:0] m_axi_weight_WSTRB;
output   m_axi_weight_WLAST;
output  [0:0] m_axi_weight_WID;
output  [0:0] m_axi_weight_WUSER;
output   m_axi_weight_ARVALID;
input   m_axi_weight_ARREADY;
output  [31:0] m_axi_weight_ARADDR;
output  [0:0] m_axi_weight_ARID;
output  [31:0] m_axi_weight_ARLEN;
output  [2:0] m_axi_weight_ARSIZE;
output  [1:0] m_axi_weight_ARBURST;
output  [1:0] m_axi_weight_ARLOCK;
output  [3:0] m_axi_weight_ARCACHE;
output  [2:0] m_axi_weight_ARPROT;
output  [3:0] m_axi_weight_ARQOS;
output  [3:0] m_axi_weight_ARREGION;
output  [0:0] m_axi_weight_ARUSER;
input   m_axi_weight_RVALID;
output   m_axi_weight_RREADY;
input  [31:0] m_axi_weight_RDATA;
input   m_axi_weight_RLAST;
input  [0:0] m_axi_weight_RID;
input  [0:0] m_axi_weight_RUSER;
input  [1:0] m_axi_weight_RRESP;
input   m_axi_weight_BVALID;
output   m_axi_weight_BREADY;
input  [1:0] m_axi_weight_BRESP;
input  [0:0] m_axi_weight_BID;
input  [0:0] m_axi_weight_BUSER;
input  [29:0] weight_offset;
output   m_axi_bias_AWVALID;
input   m_axi_bias_AWREADY;
output  [31:0] m_axi_bias_AWADDR;
output  [0:0] m_axi_bias_AWID;
output  [31:0] m_axi_bias_AWLEN;
output  [2:0] m_axi_bias_AWSIZE;
output  [1:0] m_axi_bias_AWBURST;
output  [1:0] m_axi_bias_AWLOCK;
output  [3:0] m_axi_bias_AWCACHE;
output  [2:0] m_axi_bias_AWPROT;
output  [3:0] m_axi_bias_AWQOS;
output  [3:0] m_axi_bias_AWREGION;
output  [0:0] m_axi_bias_AWUSER;
output   m_axi_bias_WVALID;
input   m_axi_bias_WREADY;
output  [31:0] m_axi_bias_WDATA;
output  [3:0] m_axi_bias_WSTRB;
output   m_axi_bias_WLAST;
output  [0:0] m_axi_bias_WID;
output  [0:0] m_axi_bias_WUSER;
output   m_axi_bias_ARVALID;
input   m_axi_bias_ARREADY;
output  [31:0] m_axi_bias_ARADDR;
output  [0:0] m_axi_bias_ARID;
output  [31:0] m_axi_bias_ARLEN;
output  [2:0] m_axi_bias_ARSIZE;
output  [1:0] m_axi_bias_ARBURST;
output  [1:0] m_axi_bias_ARLOCK;
output  [3:0] m_axi_bias_ARCACHE;
output  [2:0] m_axi_bias_ARPROT;
output  [3:0] m_axi_bias_ARQOS;
output  [3:0] m_axi_bias_ARREGION;
output  [0:0] m_axi_bias_ARUSER;
input   m_axi_bias_RVALID;
output   m_axi_bias_RREADY;
input  [31:0] m_axi_bias_RDATA;
input   m_axi_bias_RLAST;
input  [0:0] m_axi_bias_RID;
input  [0:0] m_axi_bias_RUSER;
input  [1:0] m_axi_bias_RRESP;
input   m_axi_bias_BVALID;
output   m_axi_bias_BREADY;
input  [1:0] m_axi_bias_BRESP;
input  [0:0] m_axi_bias_BID;
input  [0:0] m_axi_bias_BUSER;
input  [29:0] bias_offset;
output  [6:0] feature_out_address0;
output   feature_out_ce0;
output   feature_out_we0;
output  [31:0] feature_out_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg feature_in_ce0;
reg m_axi_weight_ARVALID;
reg m_axi_weight_RREADY;
reg m_axi_bias_ARVALID;
reg m_axi_bias_RREADY;
reg feature_out_ce0;
reg feature_out_we0;

(* fsm_encoding = "none" *) reg   [29:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    weight_blk_n_AR;
wire    ap_CS_fsm_state10;
reg    weight_blk_n_R;
wire    ap_CS_fsm_state21;
wire   [0:0] icmp_ln35_fu_494_p2;
reg    bias_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    bias_blk_n_R;
wire    ap_CS_fsm_state15;
wire   [30:0] add_ln56_fu_292_p2;
reg   [30:0] add_ln56_reg_520;
wire   [30:0] zext_ln51_fu_308_p1;
reg   [30:0] zext_ln51_reg_531;
wire    ap_CS_fsm_state8;
wire   [6:0] output_channel_fu_318_p2;
reg   [6:0] output_channel_reg_539;
wire    ap_CS_fsm_state9;
wire   [30:0] add_ln36_1_fu_339_p2;
reg   [30:0] add_ln36_1_reg_544;
wire   [0:0] icmp_ln51_fu_312_p2;
reg   [31:0] bias_addr_read_reg_555;
wire   [63:0] zext_ln56_fu_354_p1;
reg   [63:0] zext_ln56_reg_560;
wire    ap_CS_fsm_state16;
wire   [4:0] add_ln60_fu_364_p2;
reg   [4:0] add_ln60_reg_568;
wire    ap_CS_fsm_state17;
wire   [6:0] zext_ln21_fu_382_p1;
reg   [6:0] zext_ln21_reg_573;
wire   [0:0] icmp_ln59_fu_358_p2;
wire   [3:0] zext_ln16_fu_386_p1;
reg   [3:0] zext_ln16_reg_578;
wire    ap_CS_fsm_state18;
wire   [2:0] add_ln16_fu_400_p2;
reg   [2:0] add_ln16_reg_586;
wire   [6:0] add_ln21_2_fu_416_p2;
reg   [6:0] add_ln21_2_reg_591;
wire   [0:0] icmp_ln16_fu_394_p2;
wire   [8:0] shl_ln21_4_fu_421_p3;
reg   [8:0] shl_ln21_4_reg_596;
wire   [4:0] shl_ln3_fu_429_p3;
reg   [4:0] shl_ln3_reg_601;
wire   [2:0] add_ln18_fu_451_p2;
reg   [2:0] add_ln18_reg_609;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln18_fu_445_p2;
wire   [4:0] add_ln22_2_fu_485_p2;
reg   [4:0] add_ln22_2_reg_619;
wire   [4:0] add_ln35_fu_500_p2;
reg   [4:0] add_ln35_reg_627;
reg    ap_block_state21;
reg   [31:0] weight_addr_read_reg_637;
wire   [31:0] window_q0;
wire    ap_CS_fsm_state22;
wire   [31:0] grp_fu_283_p2;
reg   [31:0] tmp1_reg_647;
wire    ap_CS_fsm_state25;
wire   [31:0] grp_fu_278_p2;
wire    ap_CS_fsm_state30;
reg   [4:0] window_address0;
reg    window_ce0;
reg    window_we0;
reg   [6:0] output_channel_0_reg_198;
reg   [31:0] accumulator_assign_0_reg_210;
reg   [4:0] input_channel_assign_reg_221;
reg   [2:0] kernel_row_0_i_0_0_reg_233;
reg   [2:0] kernel_col_0_i_0_0_reg_244;
wire    ap_CS_fsm_state20;
reg   [31:0] accumulator_4_0_0_reg_255;
reg   [4:0] index_0_i_0_0_reg_267;
wire   [63:0] zext_ln22_fu_471_p1;
wire   [63:0] zext_ln22_2_fu_490_p1;
wire   [63:0] zext_ln36_fu_506_p1;
wire   [63:0] zext_ln56_3_fu_298_p1;
wire   [63:0] zext_ln36_5_fu_344_p1;
wire    ap_CS_fsm_state26;
wire   [30:0] zext_ln56_2_fu_288_p1;
wire   [10:0] shl_ln_fu_324_p3;
wire   [15:0] grp_fu_511_p3;
wire   [30:0] zext_ln36_4_fu_336_p1;
wire   [3:0] trunc_ln21_fu_370_p1;
wire   [5:0] shl_ln2_fu_374_p3;
wire   [4:0] zext_ln16_2_fu_390_p1;
wire   [4:0] add_ln21_fu_406_p2;
wire   [6:0] zext_ln21_1_fu_412_p1;
wire   [6:0] zext_ln18_1_fu_441_p1;
wire   [6:0] add_ln21_3_fu_457_p2;
wire   [8:0] zext_ln21_2_fu_462_p1;
wire   [8:0] add_ln21_4_fu_466_p2;
wire   [3:0] zext_ln18_fu_437_p1;
wire   [3:0] add_ln22_fu_476_p2;
wire   [4:0] zext_ln22_3_fu_481_p1;
wire   [10:0] grp_fu_511_p0;
wire   [5:0] grp_fu_511_p1;
wire   [12:0] grp_fu_511_p2;
reg   [29:0] ap_NS_fsm;
wire   [15:0] grp_fu_511_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 30'd1;
end

p_anonymous_namesbkb #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0),
    .ce0(window_ce0),
    .we0(window_we0),
    .d0(feature_in_q0),
    .q0(window_q0)
);

lenet_full_top_facud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenet_full_top_facud_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(accumulator_4_0_0_reg_255),
    .din1(tmp1_reg_647),
    .ce(1'b1),
    .dout(grp_fu_278_p2)
);

lenet_full_top_fmdEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenet_full_top_fmdEe_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_q0),
    .din1(weight_addr_read_reg_637),
    .ce(1'b1),
    .dout(grp_fu_283_p2)
);

lenet_full_top_maibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
lenet_full_top_maibs_U32(
    .din0(grp_fu_511_p0),
    .din1(grp_fu_511_p1),
    .din2(grp_fu_511_p2),
    .dout(grp_fu_511_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        accumulator_4_0_0_reg_255 <= accumulator_assign_0_reg_210;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        accumulator_4_0_0_reg_255 <= grp_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd1))) begin
        accumulator_assign_0_reg_210 <= accumulator_4_0_0_reg_255;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        accumulator_assign_0_reg_210 <= bias_addr_read_reg_555;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        index_0_i_0_0_reg_267 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        index_0_i_0_0_reg_267 <= add_ln35_reg_627;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd1))) begin
        input_channel_assign_reg_221 <= add_ln60_reg_568;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input_channel_assign_reg_221 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        kernel_col_0_i_0_0_reg_244 <= add_ln18_reg_609;
    end else if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln16_fu_394_p2 == 1'd0))) begin
        kernel_col_0_i_0_0_reg_244 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_445_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        kernel_row_0_i_0_0_reg_233 <= add_ln16_reg_586;
    end else if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln59_fu_358_p2 == 1'd0))) begin
        kernel_row_0_i_0_0_reg_233 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_fu_358_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        output_channel_0_reg_198 <= output_channel_reg_539;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_channel_0_reg_198 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        add_ln16_reg_586 <= add_ln16_fu_400_p2;
        zext_ln16_reg_578[2 : 0] <= zext_ln16_fu_386_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln18_reg_609 <= add_ln18_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln16_fu_394_p2 == 1'd0))) begin
        add_ln21_2_reg_591 <= add_ln21_2_fu_416_p2;
        shl_ln21_4_reg_596[8 : 2] <= shl_ln21_4_fu_421_p3[8 : 2];
        shl_ln3_reg_601[4 : 2] <= shl_ln3_fu_429_p3[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln18_fu_445_p2 == 1'd0))) begin
        add_ln22_2_reg_619 <= add_ln22_2_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21))) begin
        add_ln35_reg_627 <= add_ln35_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln51_fu_312_p2 == 1'd0))) begin
        add_ln36_1_reg_544 <= add_ln36_1_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln56_reg_520 <= add_ln56_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln60_reg_568 <= add_ln60_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (m_axi_bias_RVALID == 1'b1))) begin
        bias_addr_read_reg_555 <= m_axi_bias_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_channel_reg_539 <= output_channel_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp1_reg_647 <= grp_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd0))) begin
        weight_addr_read_reg_637 <= m_axi_weight_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln59_fu_358_p2 == 1'd0))) begin
        zext_ln21_reg_573[5 : 2] <= zext_ln21_fu_382_p1[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        zext_ln51_reg_531[29 : 0] <= zext_ln51_fu_308_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        zext_ln56_reg_560[6 : 0] <= zext_ln56_fu_354_p1[6 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln51_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bias_blk_n_AR = m_axi_bias_ARREADY;
    end else begin
        bias_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        bias_blk_n_R = m_axi_bias_RVALID;
    end else begin
        bias_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        feature_in_ce0 = 1'b1;
    end else begin
        feature_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        feature_out_ce0 = 1'b1;
    end else begin
        feature_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_358_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        feature_out_we0 = 1'b1;
    end else begin
        feature_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_bias_ARREADY == 1'b1))) begin
        m_axi_bias_ARVALID = 1'b1;
    end else begin
        m_axi_bias_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (m_axi_bias_RVALID == 1'b1))) begin
        m_axi_bias_RREADY = 1'b1;
    end else begin
        m_axi_bias_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_weight_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_weight_ARVALID = 1'b1;
    end else begin
        m_axi_weight_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd0))) begin
        m_axi_weight_RREADY = 1'b1;
    end else begin
        m_axi_weight_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        weight_blk_n_AR = m_axi_weight_ARREADY;
    end else begin
        weight_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd0))) begin
        weight_blk_n_R = m_axi_weight_RVALID;
    end else begin
        weight_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        window_address0 = zext_ln36_fu_506_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        window_address0 = zext_ln22_2_fu_490_p1;
    end else begin
        window_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21)))) begin
        window_ce0 = 1'b1;
    end else begin
        window_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        window_we0 = 1'b1;
    end else begin
        window_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (m_axi_bias_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln51_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((m_axi_weight_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (m_axi_bias_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln59_fu_358_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln16_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln18_fu_445_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state21 : begin
            if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln35_fu_494_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_400_p2 = (kernel_row_0_i_0_0_reg_233 + 3'd1);

assign add_ln18_fu_451_p2 = (kernel_col_0_i_0_0_reg_244 + 3'd1);

assign add_ln21_2_fu_416_p2 = (zext_ln21_reg_573 + zext_ln21_1_fu_412_p1);

assign add_ln21_3_fu_457_p2 = (add_ln21_2_reg_591 + zext_ln18_1_fu_441_p1);

assign add_ln21_4_fu_466_p2 = (zext_ln21_2_fu_462_p1 + shl_ln21_4_reg_596);

assign add_ln21_fu_406_p2 = (zext_ln16_2_fu_390_p1 + input_channel_assign_reg_221);

assign add_ln22_2_fu_485_p2 = (zext_ln22_3_fu_481_p1 + shl_ln3_reg_601);

assign add_ln22_fu_476_p2 = (zext_ln16_reg_578 + zext_ln18_fu_437_p1);

assign add_ln35_fu_500_p2 = (index_0_i_0_0_reg_267 + 5'd1);

assign add_ln36_1_fu_339_p2 = (zext_ln36_4_fu_336_p1 + zext_ln51_reg_531);

assign add_ln56_fu_292_p2 = (zext_ln56_2_fu_288_p1 + 31'd22);

assign add_ln60_fu_364_p2 = (input_channel_assign_reg_221 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state21 = ((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_494_p2 == 1'd0));
end

assign feature_in_address0 = zext_ln22_fu_471_p1;

assign feature_out_address0 = zext_ln56_reg_560;

assign feature_out_d0 = accumulator_assign_0_reg_210;

assign grp_fu_511_p0 = grp_fu_511_p00;

assign grp_fu_511_p00 = shl_ln_fu_324_p3;

assign grp_fu_511_p1 = 16'd25;

assign grp_fu_511_p2 = 16'd2550;

assign icmp_ln16_fu_394_p2 = ((kernel_row_0_i_0_0_reg_233 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_445_p2 = ((kernel_col_0_i_0_0_reg_244 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_494_p2 = ((index_0_i_0_0_reg_267 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_312_p2 = ((output_channel_0_reg_198 == 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_358_p2 = ((input_channel_assign_reg_221 == 5'd16) ? 1'b1 : 1'b0);

assign m_axi_bias_ARADDR = zext_ln56_3_fu_298_p1;

assign m_axi_bias_ARBURST = 2'd0;

assign m_axi_bias_ARCACHE = 4'd0;

assign m_axi_bias_ARID = 1'd0;

assign m_axi_bias_ARLEN = 32'd120;

assign m_axi_bias_ARLOCK = 2'd0;

assign m_axi_bias_ARPROT = 3'd0;

assign m_axi_bias_ARQOS = 4'd0;

assign m_axi_bias_ARREGION = 4'd0;

assign m_axi_bias_ARSIZE = 3'd0;

assign m_axi_bias_ARUSER = 1'd0;

assign m_axi_bias_AWADDR = 32'd0;

assign m_axi_bias_AWBURST = 2'd0;

assign m_axi_bias_AWCACHE = 4'd0;

assign m_axi_bias_AWID = 1'd0;

assign m_axi_bias_AWLEN = 32'd0;

assign m_axi_bias_AWLOCK = 2'd0;

assign m_axi_bias_AWPROT = 3'd0;

assign m_axi_bias_AWQOS = 4'd0;

assign m_axi_bias_AWREGION = 4'd0;

assign m_axi_bias_AWSIZE = 3'd0;

assign m_axi_bias_AWUSER = 1'd0;

assign m_axi_bias_AWVALID = 1'b0;

assign m_axi_bias_BREADY = 1'b0;

assign m_axi_bias_WDATA = 32'd0;

assign m_axi_bias_WID = 1'd0;

assign m_axi_bias_WLAST = 1'b0;

assign m_axi_bias_WSTRB = 4'd0;

assign m_axi_bias_WUSER = 1'd0;

assign m_axi_bias_WVALID = 1'b0;

assign m_axi_weight_ARADDR = zext_ln36_5_fu_344_p1;

assign m_axi_weight_ARBURST = 2'd0;

assign m_axi_weight_ARCACHE = 4'd0;

assign m_axi_weight_ARID = 1'd0;

assign m_axi_weight_ARLEN = 32'd400;

assign m_axi_weight_ARLOCK = 2'd0;

assign m_axi_weight_ARPROT = 3'd0;

assign m_axi_weight_ARQOS = 4'd0;

assign m_axi_weight_ARREGION = 4'd0;

assign m_axi_weight_ARSIZE = 3'd0;

assign m_axi_weight_ARUSER = 1'd0;

assign m_axi_weight_AWADDR = 32'd0;

assign m_axi_weight_AWBURST = 2'd0;

assign m_axi_weight_AWCACHE = 4'd0;

assign m_axi_weight_AWID = 1'd0;

assign m_axi_weight_AWLEN = 32'd0;

assign m_axi_weight_AWLOCK = 2'd0;

assign m_axi_weight_AWPROT = 3'd0;

assign m_axi_weight_AWQOS = 4'd0;

assign m_axi_weight_AWREGION = 4'd0;

assign m_axi_weight_AWSIZE = 3'd0;

assign m_axi_weight_AWUSER = 1'd0;

assign m_axi_weight_AWVALID = 1'b0;

assign m_axi_weight_BREADY = 1'b0;

assign m_axi_weight_WDATA = 32'd0;

assign m_axi_weight_WID = 1'd0;

assign m_axi_weight_WLAST = 1'b0;

assign m_axi_weight_WSTRB = 4'd0;

assign m_axi_weight_WUSER = 1'd0;

assign m_axi_weight_WVALID = 1'b0;

assign output_channel_fu_318_p2 = (output_channel_0_reg_198 + 7'd1);

assign shl_ln21_4_fu_421_p3 = {{add_ln21_2_fu_416_p2}, {2'd0}};

assign shl_ln2_fu_374_p3 = {{trunc_ln21_fu_370_p1}, {2'd0}};

assign shl_ln3_fu_429_p3 = {{kernel_row_0_i_0_0_reg_233}, {2'd0}};

assign shl_ln_fu_324_p3 = {{output_channel_0_reg_198}, {4'd0}};

assign trunc_ln21_fu_370_p1 = input_channel_assign_reg_221[3:0];

assign zext_ln16_2_fu_390_p1 = kernel_row_0_i_0_0_reg_233;

assign zext_ln16_fu_386_p1 = kernel_row_0_i_0_0_reg_233;

assign zext_ln18_1_fu_441_p1 = kernel_col_0_i_0_0_reg_244;

assign zext_ln18_fu_437_p1 = kernel_col_0_i_0_0_reg_244;

assign zext_ln21_1_fu_412_p1 = add_ln21_fu_406_p2;

assign zext_ln21_2_fu_462_p1 = add_ln21_3_fu_457_p2;

assign zext_ln21_fu_382_p1 = shl_ln2_fu_374_p3;

assign zext_ln22_2_fu_490_p1 = add_ln22_2_reg_619;

assign zext_ln22_3_fu_481_p1 = add_ln22_fu_476_p2;

assign zext_ln22_fu_471_p1 = add_ln21_4_fu_466_p2;

assign zext_ln36_4_fu_336_p1 = grp_fu_511_p3;

assign zext_ln36_5_fu_344_p1 = add_ln36_1_reg_544;

assign zext_ln36_fu_506_p1 = index_0_i_0_0_reg_267;

assign zext_ln51_fu_308_p1 = weight_offset;

assign zext_ln56_2_fu_288_p1 = bias_offset;

assign zext_ln56_3_fu_298_p1 = add_ln56_reg_520;

assign zext_ln56_fu_354_p1 = output_channel_0_reg_198;

always @ (posedge ap_clk) begin
    zext_ln51_reg_531[30] <= 1'b0;
    zext_ln56_reg_560[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln21_reg_573[1:0] <= 2'b00;
    zext_ln21_reg_573[6] <= 1'b0;
    zext_ln16_reg_578[3] <= 1'b0;
    shl_ln21_4_reg_596[1:0] <= 2'b00;
    shl_ln3_reg_601[1:0] <= 2'b00;
end

endmodule //p_anonymous_namespace_5
