// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_anonymous_namespace_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_in_address0,
        feature_in_ce0,
        feature_in_q0,
        feature_out_address0,
        feature_out_ce0,
        feature_out_we0,
        feature_out_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] feature_in_address0;
output   feature_in_ce0;
input  [31:0] feature_in_q0;
output  [8:0] feature_out_address0;
output   feature_out_ce0;
output   feature_out_we0;
output  [31:0] feature_out_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg feature_in_ce0;
reg feature_out_ce0;
reg feature_out_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] channel_fu_193_p2;
reg   [4:0] channel_reg_511;
wire    ap_CS_fsm_state2;
wire   [3:0] trunc_ln105_fu_199_p1;
reg   [3:0] trunc_ln105_reg_516;
wire   [0:0] icmp_ln91_fu_187_p2;
wire   [5:0] zext_ln105_fu_209_p1;
reg   [5:0] zext_ln105_reg_521;
wire   [6:0] zext_ln114_fu_221_p1;
reg   [6:0] zext_ln114_reg_526;
wire   [2:0] output_row_fu_235_p2;
reg   [2:0] output_row_reg_534;
wire    ap_CS_fsm_state3;
wire   [6:0] add_ln114_fu_263_p2;
reg   [6:0] add_ln114_reg_539;
wire   [0:0] icmp_ln93_fu_229_p2;
wire   [8:0] shl_ln114_4_fu_268_p3;
reg   [8:0] shl_ln114_4_reg_544;
wire   [7:0] zext_ln105_1_fu_281_p1;
reg   [7:0] zext_ln105_1_reg_549;
wire   [6:0] zext_ln95_fu_285_p1;
reg   [6:0] zext_ln95_reg_554;
wire    ap_CS_fsm_state4;
wire   [2:0] output_col_fu_295_p2;
reg   [2:0] output_col_reg_562;
wire   [3:0] shl_ln9_fu_301_p3;
reg   [3:0] shl_ln9_reg_567;
wire   [0:0] icmp_ln95_fu_289_p2;
wire   [1:0] kernel_row_fu_315_p2;
reg   [1:0] kernel_row_reg_575;
wire    ap_CS_fsm_state5;
wire   [10:0] add_ln105_2_fu_359_p2;
reg   [10:0] add_ln105_2_reg_580;
wire   [0:0] icmp_ln99_fu_309_p2;
wire   [1:0] kernel_col_fu_393_p2;
reg   [1:0] kernel_col_reg_588;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln101_fu_387_p2;
reg   [31:0] value_reg_598;
wire    ap_CS_fsm_state7;
wire   [31:0] maximum_2_fu_501_p3;
wire    ap_CS_fsm_state8;
reg   [4:0] channel_0_reg_100;
reg   [2:0] output_row_0_reg_112;
reg   [2:0] output_col_0_reg_123;
reg   [31:0] maximum_0_reg_134;
reg   [1:0] kernel_row_0_reg_147;
reg   [31:0] maximum_1_reg_158;
reg   [1:0] kernel_col_0_reg_170;
wire   [63:0] zext_ln115_fu_378_p1;
wire   [63:0] zext_ln106_fu_413_p1;
wire   [4:0] shl_ln105_fu_203_p2;
wire   [5:0] shl_ln7_fu_213_p3;
wire   [3:0] shl_ln8_fu_241_p3;
wire   [4:0] zext_ln93_fu_225_p1;
wire   [4:0] add_ln114_1_fu_253_p2;
wire   [6:0] zext_ln114_1_fu_259_p1;
wire   [5:0] zext_ln102_fu_249_p1;
wire   [5:0] add_ln105_1_fu_276_p2;
wire   [6:0] tmp4_fu_321_p4;
wire   [7:0] zext_ln105_2_fu_330_p1;
wire   [7:0] add_ln105_fu_334_p2;
wire   [8:0] shl_ln105_5_fu_347_p3;
wire   [10:0] zext_ln105_3_fu_355_p1;
wire   [10:0] shl_ln105_4_fu_339_p3;
wire   [6:0] add_ln114_2_fu_365_p2;
wire   [8:0] zext_ln114_2_fu_369_p1;
wire   [8:0] output_index_fu_373_p2;
wire   [3:0] zext_ln101_fu_383_p1;
wire   [3:0] add_ln105_3_fu_399_p2;
wire   [10:0] zext_ln105_4_fu_404_p1;
wire   [10:0] input_index_fu_408_p2;
wire   [31:0] bitcast_ln107_fu_418_p1;
wire   [31:0] bitcast_ln107_1_fu_435_p1;
wire   [7:0] tmp_9_fu_421_p4;
wire   [22:0] trunc_ln107_fu_431_p1;
wire   [0:0] icmp_ln107_1_fu_459_p2;
wire   [0:0] icmp_ln107_fu_453_p2;
wire   [7:0] tmp_s_fu_439_p4;
wire   [22:0] trunc_ln107_1_fu_449_p1;
wire   [0:0] icmp_ln107_3_fu_477_p2;
wire   [0:0] icmp_ln107_2_fu_471_p2;
wire   [0:0] or_ln107_fu_465_p2;
wire   [0:0] or_ln107_1_fu_483_p2;
wire   [0:0] and_ln107_fu_489_p2;
wire   [0:0] grp_fu_181_p2;
wire   [0:0] and_ln107_1_fu_495_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

lenet_full_top_fceOg #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
lenet_full_top_fceOg_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(feature_in_q0),
    .din1(maximum_1_reg_158),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_181_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        channel_0_reg_100 <= channel_reg_511;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        channel_0_reg_100 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kernel_col_0_reg_170 <= kernel_col_reg_588;
    end else if (((icmp_ln99_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        kernel_col_0_reg_170 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln101_fu_387_p2 == 1'd1))) begin
        kernel_row_0_reg_147 <= kernel_row_reg_575;
    end else if (((icmp_ln95_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_row_0_reg_147 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln101_fu_387_p2 == 1'd1))) begin
        maximum_0_reg_134 <= maximum_1_reg_158;
    end else if (((icmp_ln95_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        maximum_0_reg_134 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        maximum_1_reg_158 <= maximum_2_fu_501_p3;
    end else if (((icmp_ln99_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        maximum_1_reg_158 <= maximum_0_reg_134;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln99_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        output_col_0_reg_123 <= output_col_reg_562;
    end else if (((icmp_ln93_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        output_col_0_reg_123 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln95_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_row_0_reg_112 <= output_row_reg_534;
    end else if (((icmp_ln91_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        output_row_0_reg_112 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln99_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        add_ln105_2_reg_580[10 : 1] <= add_ln105_2_fu_359_p2[10 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln114_reg_539 <= add_ln114_fu_263_p2;
        shl_ln114_4_reg_544[8 : 2] <= shl_ln114_4_fu_268_p3[8 : 2];
        zext_ln105_1_reg_549[5 : 1] <= zext_ln105_1_fu_281_p1[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_reg_511 <= channel_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_col_reg_588 <= kernel_col_fu_393_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kernel_row_reg_575 <= kernel_row_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_col_reg_562 <= output_col_fu_295_p2;
        zext_ln95_reg_554[2 : 0] <= zext_ln95_fu_285_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        output_row_reg_534 <= output_row_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln95_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        shl_ln9_reg_567[3 : 1] <= shl_ln9_fu_301_p3[3 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln91_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln105_reg_516 <= trunc_ln105_fu_199_p1;
        zext_ln105_reg_521[4 : 1] <= zext_ln105_fu_209_p1[4 : 1];
        zext_ln114_reg_526[5 : 2] <= zext_ln114_fu_221_p1[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        value_reg_598 <= feature_in_q0;
    end
end

always @ (*) begin
    if ((((icmp_ln91_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln91_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        feature_in_ce0 = 1'b1;
    end else begin
        feature_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        feature_out_ce0 = 1'b1;
    end else begin
        feature_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln99_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        feature_out_we0 = 1'b1;
    end else begin
        feature_out_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln91_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln93_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln95_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln99_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln101_fu_387_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_1_fu_276_p2 = (zext_ln105_reg_521 + zext_ln102_fu_249_p1);

assign add_ln105_2_fu_359_p2 = (zext_ln105_3_fu_355_p1 + shl_ln105_4_fu_339_p3);

assign add_ln105_3_fu_399_p2 = (shl_ln9_reg_567 + zext_ln101_fu_383_p1);

assign add_ln105_fu_334_p2 = (zext_ln105_2_fu_330_p1 + zext_ln105_1_reg_549);

assign add_ln114_1_fu_253_p2 = (zext_ln93_fu_225_p1 + channel_0_reg_100);

assign add_ln114_2_fu_365_p2 = (add_ln114_reg_539 + zext_ln95_reg_554);

assign add_ln114_fu_263_p2 = (zext_ln114_reg_526 + zext_ln114_1_fu_259_p1);

assign and_ln107_1_fu_495_p2 = (grp_fu_181_p2 & and_ln107_fu_489_p2);

assign and_ln107_fu_489_p2 = (or_ln107_fu_465_p2 & or_ln107_1_fu_483_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign bitcast_ln107_1_fu_435_p1 = maximum_1_reg_158;

assign bitcast_ln107_fu_418_p1 = value_reg_598;

assign channel_fu_193_p2 = (channel_0_reg_100 + 5'd1);

assign feature_in_address0 = zext_ln106_fu_413_p1;

assign feature_out_address0 = zext_ln115_fu_378_p1;

assign feature_out_d0 = maximum_0_reg_134;

assign icmp_ln101_fu_387_p2 = ((kernel_col_0_reg_170 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln107_1_fu_459_p2 = ((trunc_ln107_fu_431_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_2_fu_471_p2 = ((tmp_s_fu_439_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln107_3_fu_477_p2 = ((trunc_ln107_1_fu_449_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_453_p2 = ((tmp_9_fu_421_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_187_p2 = ((channel_0_reg_100 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_229_p2 = ((output_row_0_reg_112 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_289_p2 = ((output_col_0_reg_123 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_309_p2 = ((kernel_row_0_reg_147 == 2'd2) ? 1'b1 : 1'b0);

assign input_index_fu_408_p2 = (zext_ln105_4_fu_404_p1 + add_ln105_2_reg_580);

assign kernel_col_fu_393_p2 = (kernel_col_0_reg_170 + 2'd1);

assign kernel_row_fu_315_p2 = (kernel_row_0_reg_147 + 2'd1);

assign maximum_2_fu_501_p3 = ((and_ln107_1_fu_495_p2[0:0] === 1'b1) ? value_reg_598 : maximum_1_reg_158);

assign or_ln107_1_fu_483_p2 = (icmp_ln107_3_fu_477_p2 | icmp_ln107_2_fu_471_p2);

assign or_ln107_fu_465_p2 = (icmp_ln107_fu_453_p2 | icmp_ln107_1_fu_459_p2);

assign output_col_fu_295_p2 = (output_col_0_reg_123 + 3'd1);

assign output_index_fu_373_p2 = (zext_ln114_2_fu_369_p1 + shl_ln114_4_reg_544);

assign output_row_fu_235_p2 = (output_row_0_reg_112 + 3'd1);

assign shl_ln105_4_fu_339_p3 = {{add_ln105_fu_334_p2}, {3'd0}};

assign shl_ln105_5_fu_347_p3 = {{add_ln105_fu_334_p2}, {1'd0}};

assign shl_ln105_fu_203_p2 = channel_0_reg_100 << 5'd1;

assign shl_ln114_4_fu_268_p3 = {{add_ln114_fu_263_p2}, {2'd0}};

assign shl_ln7_fu_213_p3 = {{trunc_ln105_fu_199_p1}, {2'd0}};

assign shl_ln8_fu_241_p3 = {{output_row_0_reg_112}, {1'd0}};

assign shl_ln9_fu_301_p3 = {{output_col_0_reg_123}, {1'd0}};

assign tmp4_fu_321_p4 = {{{trunc_ln105_reg_516}, {1'd0}}, {kernel_row_0_reg_147}};

assign tmp_9_fu_421_p4 = {{bitcast_ln107_fu_418_p1[30:23]}};

assign tmp_s_fu_439_p4 = {{bitcast_ln107_1_fu_435_p1[30:23]}};

assign trunc_ln105_fu_199_p1 = channel_0_reg_100[3:0];

assign trunc_ln107_1_fu_449_p1 = bitcast_ln107_1_fu_435_p1[22:0];

assign trunc_ln107_fu_431_p1 = bitcast_ln107_fu_418_p1[22:0];

assign zext_ln101_fu_383_p1 = kernel_col_0_reg_170;

assign zext_ln102_fu_249_p1 = shl_ln8_fu_241_p3;

assign zext_ln105_1_fu_281_p1 = add_ln105_1_fu_276_p2;

assign zext_ln105_2_fu_330_p1 = tmp4_fu_321_p4;

assign zext_ln105_3_fu_355_p1 = shl_ln105_5_fu_347_p3;

assign zext_ln105_4_fu_404_p1 = add_ln105_3_fu_399_p2;

assign zext_ln105_fu_209_p1 = shl_ln105_fu_203_p2;

assign zext_ln106_fu_413_p1 = input_index_fu_408_p2;

assign zext_ln114_1_fu_259_p1 = add_ln114_1_fu_253_p2;

assign zext_ln114_2_fu_369_p1 = add_ln114_2_fu_365_p2;

assign zext_ln114_fu_221_p1 = shl_ln7_fu_213_p3;

assign zext_ln115_fu_378_p1 = output_index_fu_373_p2;

assign zext_ln93_fu_225_p1 = output_row_0_reg_112;

assign zext_ln95_fu_285_p1 = output_col_0_reg_123;

always @ (posedge ap_clk) begin
    zext_ln105_reg_521[0] <= 1'b0;
    zext_ln105_reg_521[5] <= 1'b0;
    zext_ln114_reg_526[1:0] <= 2'b00;
    zext_ln114_reg_526[6] <= 1'b0;
    shl_ln114_4_reg_544[1:0] <= 2'b00;
    zext_ln105_1_reg_549[0] <= 1'b0;
    zext_ln105_1_reg_549[7:6] <= 2'b00;
    zext_ln95_reg_554[6:3] <= 4'b0000;
    shl_ln9_reg_567[0] <= 1'b0;
    add_ln105_2_reg_580[0] <= 1'b0;
end

endmodule //p_anonymous_namespace_1
