// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_anonymous_namespace_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_feature_in_AWVALID,
        m_axi_feature_in_AWREADY,
        m_axi_feature_in_AWADDR,
        m_axi_feature_in_AWID,
        m_axi_feature_in_AWLEN,
        m_axi_feature_in_AWSIZE,
        m_axi_feature_in_AWBURST,
        m_axi_feature_in_AWLOCK,
        m_axi_feature_in_AWCACHE,
        m_axi_feature_in_AWPROT,
        m_axi_feature_in_AWQOS,
        m_axi_feature_in_AWREGION,
        m_axi_feature_in_AWUSER,
        m_axi_feature_in_WVALID,
        m_axi_feature_in_WREADY,
        m_axi_feature_in_WDATA,
        m_axi_feature_in_WSTRB,
        m_axi_feature_in_WLAST,
        m_axi_feature_in_WID,
        m_axi_feature_in_WUSER,
        m_axi_feature_in_ARVALID,
        m_axi_feature_in_ARREADY,
        m_axi_feature_in_ARADDR,
        m_axi_feature_in_ARID,
        m_axi_feature_in_ARLEN,
        m_axi_feature_in_ARSIZE,
        m_axi_feature_in_ARBURST,
        m_axi_feature_in_ARLOCK,
        m_axi_feature_in_ARCACHE,
        m_axi_feature_in_ARPROT,
        m_axi_feature_in_ARQOS,
        m_axi_feature_in_ARREGION,
        m_axi_feature_in_ARUSER,
        m_axi_feature_in_RVALID,
        m_axi_feature_in_RREADY,
        m_axi_feature_in_RDATA,
        m_axi_feature_in_RLAST,
        m_axi_feature_in_RID,
        m_axi_feature_in_RUSER,
        m_axi_feature_in_RRESP,
        m_axi_feature_in_BVALID,
        m_axi_feature_in_BREADY,
        m_axi_feature_in_BRESP,
        m_axi_feature_in_BID,
        m_axi_feature_in_BUSER,
        feature_in_offset,
        m_axi_weight_AWVALID,
        m_axi_weight_AWREADY,
        m_axi_weight_AWADDR,
        m_axi_weight_AWID,
        m_axi_weight_AWLEN,
        m_axi_weight_AWSIZE,
        m_axi_weight_AWBURST,
        m_axi_weight_AWLOCK,
        m_axi_weight_AWCACHE,
        m_axi_weight_AWPROT,
        m_axi_weight_AWQOS,
        m_axi_weight_AWREGION,
        m_axi_weight_AWUSER,
        m_axi_weight_WVALID,
        m_axi_weight_WREADY,
        m_axi_weight_WDATA,
        m_axi_weight_WSTRB,
        m_axi_weight_WLAST,
        m_axi_weight_WID,
        m_axi_weight_WUSER,
        m_axi_weight_ARVALID,
        m_axi_weight_ARREADY,
        m_axi_weight_ARADDR,
        m_axi_weight_ARID,
        m_axi_weight_ARLEN,
        m_axi_weight_ARSIZE,
        m_axi_weight_ARBURST,
        m_axi_weight_ARLOCK,
        m_axi_weight_ARCACHE,
        m_axi_weight_ARPROT,
        m_axi_weight_ARQOS,
        m_axi_weight_ARREGION,
        m_axi_weight_ARUSER,
        m_axi_weight_RVALID,
        m_axi_weight_RREADY,
        m_axi_weight_RDATA,
        m_axi_weight_RLAST,
        m_axi_weight_RID,
        m_axi_weight_RUSER,
        m_axi_weight_RRESP,
        m_axi_weight_BVALID,
        m_axi_weight_BREADY,
        m_axi_weight_BRESP,
        m_axi_weight_BID,
        m_axi_weight_BUSER,
        weight_offset,
        m_axi_bias_AWVALID,
        m_axi_bias_AWREADY,
        m_axi_bias_AWADDR,
        m_axi_bias_AWID,
        m_axi_bias_AWLEN,
        m_axi_bias_AWSIZE,
        m_axi_bias_AWBURST,
        m_axi_bias_AWLOCK,
        m_axi_bias_AWCACHE,
        m_axi_bias_AWPROT,
        m_axi_bias_AWQOS,
        m_axi_bias_AWREGION,
        m_axi_bias_AWUSER,
        m_axi_bias_WVALID,
        m_axi_bias_WREADY,
        m_axi_bias_WDATA,
        m_axi_bias_WSTRB,
        m_axi_bias_WLAST,
        m_axi_bias_WID,
        m_axi_bias_WUSER,
        m_axi_bias_ARVALID,
        m_axi_bias_ARREADY,
        m_axi_bias_ARADDR,
        m_axi_bias_ARID,
        m_axi_bias_ARLEN,
        m_axi_bias_ARSIZE,
        m_axi_bias_ARBURST,
        m_axi_bias_ARLOCK,
        m_axi_bias_ARCACHE,
        m_axi_bias_ARPROT,
        m_axi_bias_ARQOS,
        m_axi_bias_ARREGION,
        m_axi_bias_ARUSER,
        m_axi_bias_RVALID,
        m_axi_bias_RREADY,
        m_axi_bias_RDATA,
        m_axi_bias_RLAST,
        m_axi_bias_RID,
        m_axi_bias_RUSER,
        m_axi_bias_RRESP,
        m_axi_bias_BVALID,
        m_axi_bias_BREADY,
        m_axi_bias_BRESP,
        m_axi_bias_BID,
        m_axi_bias_BUSER,
        bias_offset,
        feature_out_address0,
        feature_out_ce0,
        feature_out_we0,
        feature_out_d0
);

parameter    ap_ST_fsm_state1 = 37'd1;
parameter    ap_ST_fsm_state2 = 37'd2;
parameter    ap_ST_fsm_state3 = 37'd4;
parameter    ap_ST_fsm_state4 = 37'd8;
parameter    ap_ST_fsm_state5 = 37'd16;
parameter    ap_ST_fsm_state6 = 37'd32;
parameter    ap_ST_fsm_state7 = 37'd64;
parameter    ap_ST_fsm_state8 = 37'd128;
parameter    ap_ST_fsm_state9 = 37'd256;
parameter    ap_ST_fsm_state10 = 37'd512;
parameter    ap_ST_fsm_state11 = 37'd1024;
parameter    ap_ST_fsm_state12 = 37'd2048;
parameter    ap_ST_fsm_state13 = 37'd4096;
parameter    ap_ST_fsm_state14 = 37'd8192;
parameter    ap_ST_fsm_state15 = 37'd16384;
parameter    ap_ST_fsm_state16 = 37'd32768;
parameter    ap_ST_fsm_state17 = 37'd65536;
parameter    ap_ST_fsm_state18 = 37'd131072;
parameter    ap_ST_fsm_state19 = 37'd262144;
parameter    ap_ST_fsm_state20 = 37'd524288;
parameter    ap_ST_fsm_state21 = 37'd1048576;
parameter    ap_ST_fsm_state22 = 37'd2097152;
parameter    ap_ST_fsm_state23 = 37'd4194304;
parameter    ap_ST_fsm_state24 = 37'd8388608;
parameter    ap_ST_fsm_state25 = 37'd16777216;
parameter    ap_ST_fsm_state26 = 37'd33554432;
parameter    ap_ST_fsm_state27 = 37'd67108864;
parameter    ap_ST_fsm_state28 = 37'd134217728;
parameter    ap_ST_fsm_state29 = 37'd268435456;
parameter    ap_ST_fsm_state30 = 37'd536870912;
parameter    ap_ST_fsm_state31 = 37'd1073741824;
parameter    ap_ST_fsm_state32 = 37'd2147483648;
parameter    ap_ST_fsm_state33 = 37'd4294967296;
parameter    ap_ST_fsm_state34 = 37'd8589934592;
parameter    ap_ST_fsm_state35 = 37'd17179869184;
parameter    ap_ST_fsm_state36 = 37'd34359738368;
parameter    ap_ST_fsm_state37 = 37'd68719476736;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_feature_in_AWVALID;
input   m_axi_feature_in_AWREADY;
output  [31:0] m_axi_feature_in_AWADDR;
output  [0:0] m_axi_feature_in_AWID;
output  [31:0] m_axi_feature_in_AWLEN;
output  [2:0] m_axi_feature_in_AWSIZE;
output  [1:0] m_axi_feature_in_AWBURST;
output  [1:0] m_axi_feature_in_AWLOCK;
output  [3:0] m_axi_feature_in_AWCACHE;
output  [2:0] m_axi_feature_in_AWPROT;
output  [3:0] m_axi_feature_in_AWQOS;
output  [3:0] m_axi_feature_in_AWREGION;
output  [0:0] m_axi_feature_in_AWUSER;
output   m_axi_feature_in_WVALID;
input   m_axi_feature_in_WREADY;
output  [31:0] m_axi_feature_in_WDATA;
output  [3:0] m_axi_feature_in_WSTRB;
output   m_axi_feature_in_WLAST;
output  [0:0] m_axi_feature_in_WID;
output  [0:0] m_axi_feature_in_WUSER;
output   m_axi_feature_in_ARVALID;
input   m_axi_feature_in_ARREADY;
output  [31:0] m_axi_feature_in_ARADDR;
output  [0:0] m_axi_feature_in_ARID;
output  [31:0] m_axi_feature_in_ARLEN;
output  [2:0] m_axi_feature_in_ARSIZE;
output  [1:0] m_axi_feature_in_ARBURST;
output  [1:0] m_axi_feature_in_ARLOCK;
output  [3:0] m_axi_feature_in_ARCACHE;
output  [2:0] m_axi_feature_in_ARPROT;
output  [3:0] m_axi_feature_in_ARQOS;
output  [3:0] m_axi_feature_in_ARREGION;
output  [0:0] m_axi_feature_in_ARUSER;
input   m_axi_feature_in_RVALID;
output   m_axi_feature_in_RREADY;
input  [31:0] m_axi_feature_in_RDATA;
input   m_axi_feature_in_RLAST;
input  [0:0] m_axi_feature_in_RID;
input  [0:0] m_axi_feature_in_RUSER;
input  [1:0] m_axi_feature_in_RRESP;
input   m_axi_feature_in_BVALID;
output   m_axi_feature_in_BREADY;
input  [1:0] m_axi_feature_in_BRESP;
input  [0:0] m_axi_feature_in_BID;
input  [0:0] m_axi_feature_in_BUSER;
input  [29:0] feature_in_offset;
output   m_axi_weight_AWVALID;
input   m_axi_weight_AWREADY;
output  [31:0] m_axi_weight_AWADDR;
output  [0:0] m_axi_weight_AWID;
output  [31:0] m_axi_weight_AWLEN;
output  [2:0] m_axi_weight_AWSIZE;
output  [1:0] m_axi_weight_AWBURST;
output  [1:0] m_axi_weight_AWLOCK;
output  [3:0] m_axi_weight_AWCACHE;
output  [2:0] m_axi_weight_AWPROT;
output  [3:0] m_axi_weight_AWQOS;
output  [3:0] m_axi_weight_AWREGION;
output  [0:0] m_axi_weight_AWUSER;
output   m_axi_weight_WVALID;
input   m_axi_weight_WREADY;
output  [31:0] m_axi_weight_WDATA;
output  [3:0] m_axi_weight_WSTRB;
output   m_axi_weight_WLAST;
output  [0:0] m_axi_weight_WID;
output  [0:0] m_axi_weight_WUSER;
output   m_axi_weight_ARVALID;
input   m_axi_weight_ARREADY;
output  [31:0] m_axi_weight_ARADDR;
output  [0:0] m_axi_weight_ARID;
output  [31:0] m_axi_weight_ARLEN;
output  [2:0] m_axi_weight_ARSIZE;
output  [1:0] m_axi_weight_ARBURST;
output  [1:0] m_axi_weight_ARLOCK;
output  [3:0] m_axi_weight_ARCACHE;
output  [2:0] m_axi_weight_ARPROT;
output  [3:0] m_axi_weight_ARQOS;
output  [3:0] m_axi_weight_ARREGION;
output  [0:0] m_axi_weight_ARUSER;
input   m_axi_weight_RVALID;
output   m_axi_weight_RREADY;
input  [31:0] m_axi_weight_RDATA;
input   m_axi_weight_RLAST;
input  [0:0] m_axi_weight_RID;
input  [0:0] m_axi_weight_RUSER;
input  [1:0] m_axi_weight_RRESP;
input   m_axi_weight_BVALID;
output   m_axi_weight_BREADY;
input  [1:0] m_axi_weight_BRESP;
input  [0:0] m_axi_weight_BID;
input  [0:0] m_axi_weight_BUSER;
input  [29:0] weight_offset;
output   m_axi_bias_AWVALID;
input   m_axi_bias_AWREADY;
output  [31:0] m_axi_bias_AWADDR;
output  [0:0] m_axi_bias_AWID;
output  [31:0] m_axi_bias_AWLEN;
output  [2:0] m_axi_bias_AWSIZE;
output  [1:0] m_axi_bias_AWBURST;
output  [1:0] m_axi_bias_AWLOCK;
output  [3:0] m_axi_bias_AWCACHE;
output  [2:0] m_axi_bias_AWPROT;
output  [3:0] m_axi_bias_AWQOS;
output  [3:0] m_axi_bias_AWREGION;
output  [0:0] m_axi_bias_AWUSER;
output   m_axi_bias_WVALID;
input   m_axi_bias_WREADY;
output  [31:0] m_axi_bias_WDATA;
output  [3:0] m_axi_bias_WSTRB;
output   m_axi_bias_WLAST;
output  [0:0] m_axi_bias_WID;
output  [0:0] m_axi_bias_WUSER;
output   m_axi_bias_ARVALID;
input   m_axi_bias_ARREADY;
output  [31:0] m_axi_bias_ARADDR;
output  [0:0] m_axi_bias_ARID;
output  [31:0] m_axi_bias_ARLEN;
output  [2:0] m_axi_bias_ARSIZE;
output  [1:0] m_axi_bias_ARBURST;
output  [1:0] m_axi_bias_ARLOCK;
output  [3:0] m_axi_bias_ARCACHE;
output  [2:0] m_axi_bias_ARPROT;
output  [3:0] m_axi_bias_ARQOS;
output  [3:0] m_axi_bias_ARREGION;
output  [0:0] m_axi_bias_ARUSER;
input   m_axi_bias_RVALID;
output   m_axi_bias_RREADY;
input  [31:0] m_axi_bias_RDATA;
input   m_axi_bias_RLAST;
input  [0:0] m_axi_bias_RID;
input  [0:0] m_axi_bias_RUSER;
input  [1:0] m_axi_bias_RRESP;
input   m_axi_bias_BVALID;
output   m_axi_bias_BREADY;
input  [1:0] m_axi_bias_BRESP;
input  [0:0] m_axi_bias_BID;
input  [0:0] m_axi_bias_BUSER;
input  [29:0] bias_offset;
output  [12:0] feature_out_address0;
output   feature_out_ce0;
output   feature_out_we0;
output  [31:0] feature_out_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_feature_in_ARVALID;
reg m_axi_feature_in_RREADY;
reg m_axi_weight_ARVALID;
reg m_axi_weight_RREADY;
reg m_axi_bias_ARVALID;
reg m_axi_bias_RREADY;
reg feature_out_ce0;
reg feature_out_we0;

(* fsm_encoding = "none" *) reg   [36:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    feature_in_blk_n_AR;
wire    ap_CS_fsm_state13;
reg    feature_in_blk_n_R;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln18_fu_541_p2;
reg    weight_blk_n_AR;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln16_fu_479_p2;
reg    weight_blk_n_R;
wire    ap_CS_fsm_state28;
wire   [0:0] icmp_ln35_fu_571_p2;
reg    bias_blk_n_AR;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln55_fu_459_p2;
reg    bias_blk_n_R;
wire    ap_CS_fsm_state11;
wire   [30:0] zext_ln36_1_fu_306_p1;
reg   [30:0] zext_ln36_1_reg_601;
wire   [30:0] zext_ln22_fu_310_p1;
reg   [30:0] zext_ln22_reg_606;
wire   [30:0] zext_ln51_fu_314_p1;
reg   [30:0] zext_ln51_reg_611;
wire   [7:0] add_ln53_fu_318_p2;
reg   [7:0] add_ln53_reg_616;
wire    ap_CS_fsm_state2;
wire   [2:0] output_channel_fu_330_p2;
reg   [2:0] output_channel_reg_624;
reg   [31:0] bias_addr_reg_629;
wire   [0:0] icmp_ln51_fu_324_p2;
wire   [8:0] sub_ln76_fu_379_p2;
reg   [8:0] sub_ln76_reg_635;
reg   [31:0] weight_addr_reg_640;
wire   [4:0] output_row_fu_414_p2;
reg   [4:0] output_row_reg_649;
wire    ap_CS_fsm_state3;
wire   [13:0] sub_ln76_1_fu_445_p2;
reg   [13:0] sub_ln76_1_reg_654;
wire   [0:0] icmp_ln53_fu_408_p2;
wire   [9:0] zext_ln55_fu_451_p1;
reg   [9:0] zext_ln55_reg_659;
reg    ap_block_state4_io;
wire   [13:0] zext_ln55_1_fu_455_p1;
reg   [13:0] zext_ln55_1_reg_664;
wire   [4:0] output_col_fu_465_p2;
reg   [4:0] output_col_reg_672;
reg   [31:0] accumulator_reg_677;
wire   [3:0] zext_ln16_fu_471_p1;
reg   [3:0] zext_ln16_reg_682;
reg    ap_block_state12_io;
wire   [2:0] add_ln16_fu_485_p2;
reg   [2:0] add_ln16_reg_690;
wire   [30:0] add_ln22_1_fu_514_p2;
reg   [30:0] add_ln22_1_reg_695;
wire   [4:0] shl_ln1_fu_529_p3;
reg   [4:0] shl_ln1_reg_706;
wire    ap_CS_fsm_state19;
wire   [2:0] add_ln18_fu_547_p2;
reg   [2:0] add_ln18_reg_714;
reg    ap_block_state20;
reg   [31:0] feature_in_addr_read_reg_719;
wire   [4:0] add_ln22_2_fu_562_p2;
reg   [4:0] add_ln22_2_reg_724;
wire   [4:0] add_ln35_fu_577_p2;
reg   [4:0] add_ln35_reg_732;
reg    ap_block_state28;
reg   [31:0] weight_addr_read_reg_742;
wire   [31:0] window_q0;
wire    ap_CS_fsm_state29;
wire   [31:0] grp_fu_301_p2;
reg   [31:0] tmp2_reg_752;
wire    ap_CS_fsm_state32;
wire   [31:0] grp_fu_296_p2;
wire    ap_CS_fsm_state37;
reg   [4:0] window_address0;
reg    window_ce0;
reg    window_we0;
reg   [2:0] output_channel_0_reg_206;
reg   [7:0] phi_mul_reg_217;
reg   [4:0] output_row_assign_reg_228;
reg   [4:0] output_col_assign_reg_240;
reg   [2:0] kernel_row_0_i_0_reg_251;
reg   [2:0] kernel_col_0_i_0_reg_263;
wire    ap_CS_fsm_state21;
reg   [31:0] accumulator_5_0_reg_274;
wire    ap_CS_fsm_state27;
reg   [4:0] index_0_i_0_reg_285;
wire   [63:0] zext_ln22_3_fu_567_p1;
wire   [63:0] zext_ln36_fu_583_p1;
wire   [63:0] zext_ln77_fu_596_p1;
wire   [63:0] zext_ln56_1_fu_345_p1;
wire   [63:0] zext_ln36_3_fu_394_p1;
wire   [63:0] zext_ln22_2_fu_519_p1;
wire    ap_CS_fsm_state33;
wire   [30:0] zext_ln56_fu_336_p1;
wire   [30:0] add_ln56_fu_340_p2;
wire   [7:0] shl_ln_fu_355_p3;
wire   [4:0] shl_ln76_2_fu_367_p3;
wire   [8:0] zext_ln76_fu_363_p1;
wire   [8:0] zext_ln76_1_fu_375_p1;
wire   [30:0] zext_ln36_2_fu_385_p1;
wire   [30:0] add_ln36_fu_389_p2;
wire   [8:0] zext_ln53_fu_404_p1;
wire   [8:0] add_ln76_fu_420_p2;
wire   [10:0] shl_ln76_4_fu_433_p3;
wire   [13:0] shl_ln76_3_fu_425_p3;
wire  signed [13:0] sext_ln76_fu_441_p1;
wire   [4:0] zext_ln16_1_fu_475_p1;
wire   [4:0] add_ln21_fu_491_p2;
wire   [9:0] tmp_1_fu_497_p3;
wire   [9:0] add_ln21_1_fu_505_p2;
wire   [30:0] zext_ln22_1_fu_510_p1;
wire   [3:0] zext_ln18_fu_537_p1;
wire   [3:0] add_ln22_fu_553_p2;
wire   [4:0] zext_ln22_4_fu_558_p1;
wire   [13:0] output_index_fu_588_p2;
wire  signed [31:0] sext_ln76_1_fu_592_p1;
reg   [36:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 37'd1;
end

p_anonymous_namesbkb #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0),
    .ce0(window_ce0),
    .we0(window_we0),
    .d0(feature_in_addr_read_reg_719),
    .q0(window_q0)
);

lenet_full_top_facud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenet_full_top_facud_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(accumulator_5_0_reg_274),
    .din1(tmp2_reg_752),
    .ce(1'b1),
    .dout(grp_fu_296_p2)
);

lenet_full_top_fmdEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenet_full_top_fmdEe_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_q0),
    .din1(weight_addr_read_reg_742),
    .ce(1'b1),
    .dout(grp_fu_301_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        accumulator_5_0_reg_274 <= accumulator_reg_677;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        accumulator_5_0_reg_274 <= grp_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        index_0_i_0_reg_285 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        index_0_i_0_reg_285 <= add_ln35_reg_732;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        kernel_col_0_i_0_reg_263 <= add_ln18_reg_714;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        kernel_col_0_i_0_reg_263 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (icmp_ln18_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        kernel_row_0_i_0_reg_251 <= add_ln16_reg_690;
    end else if (((m_axi_bias_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        kernel_row_0_i_0_reg_251 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        output_channel_0_reg_206 <= output_channel_reg_624;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        output_channel_0_reg_206 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (icmp_ln35_fu_571_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        output_col_assign_reg_240 <= output_col_reg_672;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_408_p2 == 1'd0))) begin
        output_col_assign_reg_240 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4_io) & (icmp_ln55_fu_459_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_row_assign_reg_228 <= output_row_reg_649;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln51_fu_324_p2 == 1'd0))) begin
        output_row_assign_reg_228 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul_reg_217 <= add_ln53_reg_616;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_reg_217 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_bias_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        accumulator_reg_677 <= m_axi_bias_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12))) begin
        add_ln16_reg_690 <= add_ln16_fu_485_p2;
        zext_ln16_reg_682[2 : 0] <= zext_ln16_fu_471_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state20))) begin
        add_ln18_reg_714 <= add_ln18_fu_547_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln16_fu_479_p2 == 1'd0))) begin
        add_ln22_1_reg_695 <= add_ln22_1_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln18_fu_541_p2 == 1'd0))) begin
        add_ln22_2_reg_724 <= add_ln22_2_fu_562_p2;
        feature_in_addr_read_reg_719 <= m_axi_feature_in_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28))) begin
        add_ln35_reg_732 <= add_ln35_fu_577_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln53_reg_616 <= add_ln53_fu_318_p2;
        output_channel_reg_624 <= output_channel_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln51_fu_324_p2 == 1'd0))) begin
        bias_addr_reg_629[30 : 0] <= zext_ln56_1_fu_345_p1[30 : 0];
        sub_ln76_reg_635[8 : 2] <= sub_ln76_fu_379_p2[8 : 2];
        weight_addr_reg_640[30 : 0] <= zext_ln36_3_fu_394_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        output_col_reg_672 <= output_col_fu_465_p2;
        zext_ln55_1_reg_664[4 : 0] <= zext_ln55_1_fu_455_p1[4 : 0];
        zext_ln55_reg_659[4 : 0] <= zext_ln55_fu_451_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        output_row_reg_649 <= output_row_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        shl_ln1_reg_706[4 : 2] <= shl_ln1_fu_529_p3[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_408_p2 == 1'd0))) begin
        sub_ln76_1_reg_654[13 : 2] <= sub_ln76_1_fu_445_p2[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        tmp2_reg_752 <= grp_fu_301_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28) & (icmp_ln35_fu_571_p2 == 1'd0))) begin
        weight_addr_read_reg_742 <= m_axi_weight_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        zext_ln22_reg_606[29 : 0] <= zext_ln22_fu_310_p1[29 : 0];
        zext_ln36_1_reg_601[29 : 0] <= zext_ln36_1_fu_306_p1[29 : 0];
        zext_ln51_reg_611[29 : 0] <= zext_ln51_fu_314_p1[29 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln51_fu_324_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_324_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln55_fu_459_p2 == 1'd0))) begin
        bias_blk_n_AR = m_axi_bias_ARREADY;
    end else begin
        bias_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        bias_blk_n_R = m_axi_bias_RVALID;
    end else begin
        bias_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        feature_in_blk_n_AR = m_axi_feature_in_ARREADY;
    end else begin
        feature_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln18_fu_541_p2 == 1'd0))) begin
        feature_in_blk_n_R = m_axi_feature_in_RVALID;
    end else begin
        feature_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28))) begin
        feature_out_ce0 = 1'b1;
    end else begin
        feature_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (icmp_ln35_fu_571_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        feature_out_we0 = 1'b1;
    end else begin
        feature_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln55_fu_459_p2 == 1'd0))) begin
        m_axi_bias_ARVALID = 1'b1;
    end else begin
        m_axi_bias_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_bias_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_bias_RREADY = 1'b1;
    end else begin
        m_axi_bias_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_feature_in_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_feature_in_ARVALID = 1'b1;
    end else begin
        m_axi_feature_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln18_fu_541_p2 == 1'd0))) begin
        m_axi_feature_in_RREADY = 1'b1;
    end else begin
        m_axi_feature_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state12_io) & (icmp_ln16_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_weight_ARVALID = 1'b1;
    end else begin
        m_axi_weight_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28) & (icmp_ln35_fu_571_p2 == 1'd0))) begin
        m_axi_weight_RREADY = 1'b1;
    end else begin
        m_axi_weight_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        weight_blk_n_AR = m_axi_weight_ARREADY;
    end else begin
        weight_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) & (icmp_ln35_fu_571_p2 == 1'd0))) begin
        weight_blk_n_R = m_axi_weight_RVALID;
    end else begin
        weight_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        window_address0 = zext_ln36_fu_583_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        window_address0 = zext_ln22_3_fu_567_p1;
    end else begin
        window_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28)))) begin
        window_ce0 = 1'b1;
    end else begin
        window_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        window_we0 = 1'b1;
    end else begin
        window_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln51_fu_324_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln53_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_io) & (icmp_ln55_fu_459_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln55_fu_459_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((m_axi_bias_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_io) & (icmp_ln16_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln16_fu_479_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((m_axi_feature_in_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (icmp_ln18_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if ((~((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln18_fu_541_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (icmp_ln35_fu_571_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state28) & (icmp_ln35_fu_571_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_485_p2 = (kernel_row_0_i_0_reg_251 + 3'd1);

assign add_ln18_fu_547_p2 = (kernel_col_0_i_0_reg_263 + 3'd1);

assign add_ln21_1_fu_505_p2 = (tmp_1_fu_497_p3 + zext_ln55_reg_659);

assign add_ln21_fu_491_p2 = (output_row_assign_reg_228 + zext_ln16_1_fu_475_p1);

assign add_ln22_1_fu_514_p2 = (zext_ln22_1_fu_510_p1 + zext_ln51_reg_611);

assign add_ln22_2_fu_562_p2 = (zext_ln22_4_fu_558_p1 + shl_ln1_reg_706);

assign add_ln22_fu_553_p2 = (zext_ln16_reg_682 + zext_ln18_fu_537_p1);

assign add_ln35_fu_577_p2 = (index_0_i_0_reg_285 + 5'd1);

assign add_ln36_fu_389_p2 = (zext_ln36_2_fu_385_p1 + zext_ln22_reg_606);

assign add_ln53_fu_318_p2 = (phi_mul_reg_217 + 8'd25);

assign add_ln56_fu_340_p2 = (zext_ln56_fu_336_p1 + zext_ln36_1_reg_601);

assign add_ln76_fu_420_p2 = (zext_ln53_fu_404_p1 + sub_ln76_reg_635);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state12_io = ((m_axi_weight_ARREADY == 1'b0) & (icmp_ln16_fu_479_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state20 = ((m_axi_feature_in_RVALID == 1'b0) & (icmp_ln18_fu_541_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state28 = ((m_axi_weight_RVALID == 1'b0) & (icmp_ln35_fu_571_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_bias_ARREADY == 1'b0) & (icmp_ln55_fu_459_p2 == 1'd0));
end

assign feature_out_address0 = zext_ln77_fu_596_p1;

assign feature_out_d0 = accumulator_5_0_reg_274;

assign icmp_ln16_fu_479_p2 = ((kernel_row_0_i_0_reg_251 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_541_p2 = ((kernel_col_0_i_0_reg_263 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_571_p2 = ((index_0_i_0_reg_285 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_324_p2 = ((output_channel_0_reg_206 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_408_p2 = ((output_row_assign_reg_228 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_459_p2 = ((output_col_assign_reg_240 == 5'd28) ? 1'b1 : 1'b0);

assign m_axi_bias_ARADDR = bias_addr_reg_629;

assign m_axi_bias_ARBURST = 2'd0;

assign m_axi_bias_ARCACHE = 4'd0;

assign m_axi_bias_ARID = 1'd0;

assign m_axi_bias_ARLEN = 32'd1;

assign m_axi_bias_ARLOCK = 2'd0;

assign m_axi_bias_ARPROT = 3'd0;

assign m_axi_bias_ARQOS = 4'd0;

assign m_axi_bias_ARREGION = 4'd0;

assign m_axi_bias_ARSIZE = 3'd0;

assign m_axi_bias_ARUSER = 1'd0;

assign m_axi_bias_AWADDR = 32'd0;

assign m_axi_bias_AWBURST = 2'd0;

assign m_axi_bias_AWCACHE = 4'd0;

assign m_axi_bias_AWID = 1'd0;

assign m_axi_bias_AWLEN = 32'd0;

assign m_axi_bias_AWLOCK = 2'd0;

assign m_axi_bias_AWPROT = 3'd0;

assign m_axi_bias_AWQOS = 4'd0;

assign m_axi_bias_AWREGION = 4'd0;

assign m_axi_bias_AWSIZE = 3'd0;

assign m_axi_bias_AWUSER = 1'd0;

assign m_axi_bias_AWVALID = 1'b0;

assign m_axi_bias_BREADY = 1'b0;

assign m_axi_bias_WDATA = 32'd0;

assign m_axi_bias_WID = 1'd0;

assign m_axi_bias_WLAST = 1'b0;

assign m_axi_bias_WSTRB = 4'd0;

assign m_axi_bias_WUSER = 1'd0;

assign m_axi_bias_WVALID = 1'b0;

assign m_axi_feature_in_ARADDR = zext_ln22_2_fu_519_p1;

assign m_axi_feature_in_ARBURST = 2'd0;

assign m_axi_feature_in_ARCACHE = 4'd0;

assign m_axi_feature_in_ARID = 1'd0;

assign m_axi_feature_in_ARLEN = 32'd5;

assign m_axi_feature_in_ARLOCK = 2'd0;

assign m_axi_feature_in_ARPROT = 3'd0;

assign m_axi_feature_in_ARQOS = 4'd0;

assign m_axi_feature_in_ARREGION = 4'd0;

assign m_axi_feature_in_ARSIZE = 3'd0;

assign m_axi_feature_in_ARUSER = 1'd0;

assign m_axi_feature_in_AWADDR = 32'd0;

assign m_axi_feature_in_AWBURST = 2'd0;

assign m_axi_feature_in_AWCACHE = 4'd0;

assign m_axi_feature_in_AWID = 1'd0;

assign m_axi_feature_in_AWLEN = 32'd0;

assign m_axi_feature_in_AWLOCK = 2'd0;

assign m_axi_feature_in_AWPROT = 3'd0;

assign m_axi_feature_in_AWQOS = 4'd0;

assign m_axi_feature_in_AWREGION = 4'd0;

assign m_axi_feature_in_AWSIZE = 3'd0;

assign m_axi_feature_in_AWUSER = 1'd0;

assign m_axi_feature_in_AWVALID = 1'b0;

assign m_axi_feature_in_BREADY = 1'b0;

assign m_axi_feature_in_WDATA = 32'd0;

assign m_axi_feature_in_WID = 1'd0;

assign m_axi_feature_in_WLAST = 1'b0;

assign m_axi_feature_in_WSTRB = 4'd0;

assign m_axi_feature_in_WUSER = 1'd0;

assign m_axi_feature_in_WVALID = 1'b0;

assign m_axi_weight_ARADDR = weight_addr_reg_640;

assign m_axi_weight_ARBURST = 2'd0;

assign m_axi_weight_ARCACHE = 4'd0;

assign m_axi_weight_ARID = 1'd0;

assign m_axi_weight_ARLEN = 32'd25;

assign m_axi_weight_ARLOCK = 2'd0;

assign m_axi_weight_ARPROT = 3'd0;

assign m_axi_weight_ARQOS = 4'd0;

assign m_axi_weight_ARREGION = 4'd0;

assign m_axi_weight_ARSIZE = 3'd0;

assign m_axi_weight_ARUSER = 1'd0;

assign m_axi_weight_AWADDR = 32'd0;

assign m_axi_weight_AWBURST = 2'd0;

assign m_axi_weight_AWCACHE = 4'd0;

assign m_axi_weight_AWID = 1'd0;

assign m_axi_weight_AWLEN = 32'd0;

assign m_axi_weight_AWLOCK = 2'd0;

assign m_axi_weight_AWPROT = 3'd0;

assign m_axi_weight_AWQOS = 4'd0;

assign m_axi_weight_AWREGION = 4'd0;

assign m_axi_weight_AWSIZE = 3'd0;

assign m_axi_weight_AWUSER = 1'd0;

assign m_axi_weight_AWVALID = 1'b0;

assign m_axi_weight_BREADY = 1'b0;

assign m_axi_weight_WDATA = 32'd0;

assign m_axi_weight_WID = 1'd0;

assign m_axi_weight_WLAST = 1'b0;

assign m_axi_weight_WSTRB = 4'd0;

assign m_axi_weight_WUSER = 1'd0;

assign m_axi_weight_WVALID = 1'b0;

assign output_channel_fu_330_p2 = (output_channel_0_reg_206 + 3'd1);

assign output_col_fu_465_p2 = (output_col_assign_reg_240 + 5'd1);

assign output_index_fu_588_p2 = (sub_ln76_1_reg_654 + zext_ln55_1_reg_664);

assign output_row_fu_414_p2 = (output_row_assign_reg_228 + 5'd1);

assign sext_ln76_1_fu_592_p1 = $signed(output_index_fu_588_p2);

assign sext_ln76_fu_441_p1 = $signed(shl_ln76_4_fu_433_p3);

assign shl_ln1_fu_529_p3 = {{kernel_row_0_i_0_reg_251}, {2'd0}};

assign shl_ln76_2_fu_367_p3 = {{output_channel_0_reg_206}, {2'd0}};

assign shl_ln76_3_fu_425_p3 = {{add_ln76_fu_420_p2}, {5'd0}};

assign shl_ln76_4_fu_433_p3 = {{add_ln76_fu_420_p2}, {2'd0}};

assign shl_ln_fu_355_p3 = {{output_channel_0_reg_206}, {5'd0}};

assign sub_ln76_1_fu_445_p2 = ($signed(shl_ln76_3_fu_425_p3) - $signed(sext_ln76_fu_441_p1));

assign sub_ln76_fu_379_p2 = (zext_ln76_fu_363_p1 - zext_ln76_1_fu_375_p1);

assign tmp_1_fu_497_p3 = {{add_ln21_fu_491_p2}, {5'd0}};

assign zext_ln16_1_fu_475_p1 = kernel_row_0_i_0_reg_251;

assign zext_ln16_fu_471_p1 = kernel_row_0_i_0_reg_251;

assign zext_ln18_fu_537_p1 = kernel_col_0_i_0_reg_263;

assign zext_ln22_1_fu_510_p1 = add_ln21_1_fu_505_p2;

assign zext_ln22_2_fu_519_p1 = add_ln22_1_reg_695;

assign zext_ln22_3_fu_567_p1 = add_ln22_2_reg_724;

assign zext_ln22_4_fu_558_p1 = add_ln22_fu_553_p2;

assign zext_ln22_fu_310_p1 = weight_offset;

assign zext_ln36_1_fu_306_p1 = bias_offset;

assign zext_ln36_2_fu_385_p1 = phi_mul_reg_217;

assign zext_ln36_3_fu_394_p1 = add_ln36_fu_389_p2;

assign zext_ln36_fu_583_p1 = index_0_i_0_reg_285;

assign zext_ln51_fu_314_p1 = feature_in_offset;

assign zext_ln53_fu_404_p1 = output_row_assign_reg_228;

assign zext_ln55_1_fu_455_p1 = output_col_assign_reg_240;

assign zext_ln55_fu_451_p1 = output_col_assign_reg_240;

assign zext_ln56_1_fu_345_p1 = add_ln56_fu_340_p2;

assign zext_ln56_fu_336_p1 = output_channel_0_reg_206;

assign zext_ln76_1_fu_375_p1 = shl_ln76_2_fu_367_p3;

assign zext_ln76_fu_363_p1 = shl_ln_fu_355_p3;

assign zext_ln77_fu_596_p1 = $unsigned(sext_ln76_1_fu_592_p1);

always @ (posedge ap_clk) begin
    zext_ln36_1_reg_601[30] <= 1'b0;
    zext_ln22_reg_606[30] <= 1'b0;
    zext_ln51_reg_611[30] <= 1'b0;
    bias_addr_reg_629[31] <= 1'b0;
    sub_ln76_reg_635[1:0] <= 2'b00;
    weight_addr_reg_640[31] <= 1'b0;
    sub_ln76_1_reg_654[1:0] <= 2'b00;
    zext_ln55_reg_659[9:5] <= 5'b00000;
    zext_ln55_1_reg_664[13:5] <= 9'b000000000;
    zext_ln16_reg_682[3] <= 1'b0;
    shl_ln1_reg_706[1:0] <= 2'b00;
end

endmodule //p_anonymous_namespace_6
