# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/vivado/vivado/F_Quantization_W8A8/hls_w4a4/vivado_review/project/LeNet_W4A4_Review.srcs/sources_1/bd/lenet_system/ip/lenet_system_auto_pc_0/lenet_system_auto_pc_0.xci
# IP: The module: 'lenet_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/vivado/vivado/F_Quantization_W8A8/hls_w4a4/vivado_review/project/LeNet_W4A4_Review.gen/sources_1/bd/lenet_system/ip/lenet_system_auto_pc_0/lenet_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/GitHub/vivado/vivado/F_Quantization_W8A8/hls_w4a4/vivado_review/project/LeNet_W4A4_Review.srcs/sources_1/bd/lenet_system/ip/lenet_system_auto_pc_0/lenet_system_auto_pc_0.xci
# IP: The module: 'lenet_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/vivado/vivado/F_Quantization_W8A8/hls_w4a4/vivado_review/project/LeNet_W4A4_Review.gen/sources_1/bd/lenet_system/ip/lenet_system_auto_pc_0/lenet_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
