// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_w4a4_top_lenet_w4a4_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_acc_V_address0,
        conv2_acc_V_ce0,
        conv2_acc_V_q0,
        conv2_acc_V_address1,
        conv2_acc_V_ce1,
        conv2_acc_V_q1,
        conv2_acc_V_address2,
        conv2_acc_V_ce2,
        conv2_acc_V_q2,
        conv2_acc_V_address3,
        conv2_acc_V_ce3,
        conv2_acc_V_q3,
        pool2_V_address0,
        pool2_V_ce0,
        pool2_V_we0,
        pool2_V_d0,
        grp_fu_1456_p_din0,
        grp_fu_1456_p_din1,
        grp_fu_1456_p_dout0,
        grp_fu_1456_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] conv2_acc_V_address0;
output   conv2_acc_V_ce0;
input  [14:0] conv2_acc_V_q0;
output  [10:0] conv2_acc_V_address1;
output   conv2_acc_V_ce1;
input  [14:0] conv2_acc_V_q1;
output  [10:0] conv2_acc_V_address2;
output   conv2_acc_V_ce2;
input  [14:0] conv2_acc_V_q2;
output  [10:0] conv2_acc_V_address3;
output   conv2_acc_V_ce3;
input  [14:0] conv2_acc_V_q3;
output  [8:0] pool2_V_address0;
output   pool2_V_ce0;
output   pool2_V_we0;
output  [2:0] pool2_V_d0;
output  [31:0] grp_fu_1456_p_din0;
output  [36:0] grp_fu_1456_p_din1;
input  [67:0] grp_fu_1456_p_dout0;
output   grp_fu_1456_p_ce;

reg ap_idle;
reg conv2_acc_V_ce0;
reg conv2_acc_V_ce1;
reg conv2_acc_V_ce2;
reg conv2_acc_V_ce3;
reg pool2_V_ce0;
reg pool2_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln221_fu_211_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] output_row_1_reg_1284;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln221_reg_1290;
reg   [0:0] icmp_ln221_reg_1290_pp0_iter1_reg;
wire   [0:0] icmp_ln226_fu_229_p2;
reg   [0:0] icmp_ln226_reg_1294;
reg   [0:0] icmp_ln226_reg_1294_pp0_iter1_reg;
wire   [0:0] and_ln221_fu_255_p2;
reg   [0:0] and_ln221_reg_1304;
reg   [0:0] and_ln221_reg_1304_pp0_iter1_reg;
wire   [2:0] add_ln227_fu_261_p2;
reg   [2:0] add_ln227_reg_1310;
wire   [2:0] select_ln226_fu_273_p3;
reg   [2:0] select_ln226_reg_1316;
reg   [2:0] select_ln226_reg_1316_pp0_iter1_reg;
wire   [3:0] empty_fu_332_p1;
reg   [3:0] empty_reg_1322;
wire   [4:0] tmp66_fu_372_p2;
reg   [4:0] tmp66_reg_1327;
wire   [4:0] add_ln222_fu_394_p2;
reg   [4:0] add_ln222_reg_1332;
wire   [3:0] empty_73_fu_400_p1;
reg   [3:0] empty_73_reg_1337;
wire   [4:0] tmp66_mid1_fu_482_p2;
reg   [4:0] tmp66_mid1_reg_1342;
wire   [7:0] select_ln226_2_fu_504_p3;
reg   [7:0] select_ln226_2_reg_1347;
wire   [8:0] add_ln278_1_fu_729_p2;
reg   [8:0] add_ln278_1_reg_1374;
reg   [8:0] add_ln278_1_reg_1374_pp0_iter3_reg;
reg   [8:0] add_ln278_1_reg_1374_pp0_iter4_reg;
reg   [8:0] add_ln278_1_reg_1374_pp0_iter5_reg;
reg   [8:0] add_ln278_1_reg_1374_pp0_iter6_reg;
reg   [8:0] add_ln278_1_reg_1374_pp0_iter7_reg;
reg  signed [14:0] conv2_acc_V_load_reg_1379;
reg  signed [14:0] conv2_acc_V_load_1_reg_1385;
reg  signed [14:0] conv2_acc_V_load_2_reg_1391;
reg  signed [14:0] conv2_acc_V_load_3_reg_1397;
wire   [0:0] icmp_ln1039_fu_735_p2;
reg   [0:0] icmp_ln1039_reg_1403;
reg   [0:0] icmp_ln1039_reg_1403_pp0_iter5_reg;
wire   [67:0] zext_ln186_fu_743_p1;
wire   [0:0] icmp_ln1039_1_fu_753_p2;
reg   [0:0] icmp_ln1039_1_reg_1414;
reg   [0:0] icmp_ln1039_1_reg_1414_pp0_iter5_reg;
wire   [0:0] icmp_ln1039_2_fu_771_p2;
reg   [0:0] icmp_ln1039_2_reg_1425;
reg   [0:0] icmp_ln1039_2_reg_1425_pp0_iter5_reg;
wire   [0:0] icmp_ln1039_3_fu_789_p2;
reg   [0:0] icmp_ln1039_3_reg_1436;
reg   [0:0] icmp_ln1039_3_reg_1436_pp0_iter5_reg;
reg   [67:0] mul_ln186_reg_1447;
wire   [39:0] trunc_ln1669_fu_807_p1;
reg   [39:0] trunc_ln1669_reg_1452;
reg   [27:0] trunc_ln186_2_reg_1458;
wire   [67:0] grp_fu_765_p2;
reg   [67:0] mul_ln186_1_reg_1464;
wire   [39:0] trunc_ln1669_1_fu_821_p1;
reg   [39:0] trunc_ln1669_1_reg_1469;
reg   [27:0] trunc_ln186_5_reg_1475;
wire   [67:0] grp_fu_783_p2;
reg   [67:0] mul_ln186_2_reg_1481;
wire   [39:0] trunc_ln1669_2_fu_835_p1;
reg   [39:0] trunc_ln1669_2_reg_1486;
reg   [27:0] trunc_ln186_7_reg_1492;
wire   [67:0] grp_fu_801_p2;
reg   [67:0] mul_ln186_3_reg_1498;
wire   [39:0] trunc_ln1669_3_fu_849_p1;
reg   [39:0] trunc_ln1669_3_reg_1503;
reg   [27:0] trunc_ln186_8_reg_1509;
wire   [2:0] select_ln1039_3_fu_942_p3;
reg   [2:0] select_ln1039_3_reg_1515;
wire   [2:0] select_ln1039_5_fu_1029_p3;
reg   [2:0] select_ln1039_5_reg_1521;
wire   [2:0] select_ln1039_7_fu_1116_p3;
reg   [2:0] select_ln1039_7_reg_1527;
wire   [2:0] select_ln1039_9_fu_1203_p3;
reg   [2:0] select_ln1039_9_reg_1533;
wire   [2:0] select_ln268_2_fu_1238_p3;
reg   [2:0] select_ln268_2_reg_1539;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln263_fu_671_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln263_1_fu_682_p1;
wire   [63:0] zext_ln263_2_fu_703_p1;
wire   [63:0] zext_ln263_3_fu_714_p1;
wire   [63:0] zext_ln281_fu_1245_p1;
reg   [2:0] output_col_fu_98;
wire   [2:0] add_ln232_fu_289_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_output_col_load;
reg   [2:0] output_row_fu_102;
wire   [2:0] select_ln226_3_fu_281_p3;
reg   [2:0] ap_sig_allocacmp_output_row_1;
reg   [5:0] indvar_flatten208_fu_106;
wire   [5:0] select_ln226_4_fu_301_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten208_load;
reg   [4:0] channel_fu_110;
wire   [4:0] select_ln221_6_fu_461_p3;
reg   [8:0] indvar_flatten264_fu_114;
wire   [8:0] add_ln221_fu_217_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten264_load;
wire   [0:0] icmp_ln231_fu_249_p2;
wire   [0:0] xor_ln221_fu_243_p2;
wire   [2:0] select_ln221_fu_235_p3;
wire   [0:0] or_ln226_fu_267_p2;
wire   [5:0] add_ln226_fu_295_p2;
wire   [6:0] p_shl_fu_336_p3;
wire   [4:0] empty_69_fu_348_p2;
wire   [3:0] tmp_s_fu_361_p3;
wire   [4:0] zext_ln226_fu_358_p1;
wire   [5:0] p_shl25_cast_fu_354_p1;
wire   [5:0] p_cast100_fu_368_p1;
wire   [5:0] tmp67_fu_378_p2;
wire   [7:0] tmp67_cast_fu_384_p1;
wire   [7:0] p_shl24_cast_fu_344_p1;
wire   [6:0] p_shl24_mid1_fu_404_p3;
wire   [6:0] select_ln221_1_fu_416_p3;
wire   [4:0] empty_74_fu_427_p2;
wire   [4:0] select_ln221_2_fu_433_p3;
wire   [7:0] tmp67_cast_mid1238_fu_444_p1;
wire   [7:0] p_shl24_cast_mid1_fu_412_p1;
wire   [7:0] p_mid1240_fu_448_p2;
wire   [7:0] empty_71_fu_388_p2;
wire   [3:0] p_mid2_fu_471_p3;
wire   [4:0] zext_ln226_1_fu_468_p1;
wire   [5:0] zext_ln221_2_fu_440_p1;
wire   [5:0] p_cast100_mid1_fu_478_p1;
wire   [5:0] tmp67_mid1_fu_488_p2;
wire   [7:0] tmp67_cast_mid1_fu_494_p1;
wire   [7:0] zext_ln221_1_fu_423_p1;
wire   [7:0] p_mid1204_fu_498_p2;
wire   [7:0] select_ln221_5_fu_454_p3;
wire   [5:0] p_shl5_fu_516_p3;
wire   [6:0] tmp66_cast_fu_527_p1;
wire   [6:0] zext_ln225_fu_523_p1;
wire   [5:0] p_shl23_mid1_fu_539_p3;
wire   [5:0] select_ln221_3_fu_550_p3;
wire   [6:0] zext_ln221_fu_536_p1;
wire   [6:0] zext_ln225_1_fu_546_p1;
wire   [6:0] p_mid1230_fu_561_p2;
wire   [6:0] empty_70_fu_530_p2;
wire   [6:0] tmp66_cast_mid1_fu_574_p1;
wire   [6:0] zext_ln221_3_fu_557_p1;
wire   [6:0] p_mid1202_fu_577_p2;
wire   [6:0] select_ln221_4_fu_567_p3;
wire   [6:0] select_ln226_1_fu_583_p3;
wire   [7:0] or_ln226_1_fu_612_p2;
wire   [8:0] zext_ln230_mid2_v_fu_625_p3;
wire   [3:0] tmp_1_fu_640_p3;
wire   [8:0] p_shl28_0_mid2_fu_605_p3;
wire   [8:0] zext_ln258_1_fu_651_p1;
wire   [8:0] add_ln258_fu_655_p2;
wire   [10:0] zext_ln258_2_fu_661_p1;
wire   [10:0] p_shl27_0_mid2_fu_598_p3;
wire   [10:0] add_ln258_1_fu_665_p2;
wire   [10:0] or_ln258_fu_676_p2;
wire   [9:0] zext_ln226_2_fu_633_p1;
wire   [9:0] zext_ln258_fu_647_p1;
wire   [9:0] add_ln258_2_fu_687_p2;
wire   [10:0] zext_ln258_3_fu_693_p1;
wire   [10:0] p_shl27_1_mid2_fu_617_p3;
wire   [10:0] add_ln258_3_fu_697_p2;
wire   [10:0] or_ln258_1_fu_708_p2;
wire   [6:0] output_col_1_cast115_fu_637_p1;
wire   [6:0] add_ln278_fu_719_p2;
wire   [8:0] zext_ln278_fu_725_p1;
wire   [8:0] p_shl26_mid2_fu_590_p3;
wire  signed [31:0] sext_ln186_fu_740_p1;
wire  signed [31:0] sext_ln186_1_fu_758_p1;
wire   [31:0] grp_fu_765_p0;
wire   [36:0] grp_fu_765_p1;
wire  signed [31:0] sext_ln186_2_fu_776_p1;
wire   [31:0] grp_fu_783_p0;
wire   [36:0] grp_fu_783_p1;
wire  signed [31:0] sext_ln186_3_fu_794_p1;
wire   [31:0] grp_fu_801_p0;
wire   [36:0] grp_fu_801_p1;
wire   [0:0] icmp_ln1019_fu_880_p2;
wire   [0:0] tmp_fu_863_p3;
wire   [0:0] icmp_ln1035_fu_870_p2;
wire   [0:0] and_ln64_fu_885_p2;
wire   [0:0] or_ln64_fu_891_p2;
wire   [27:0] add_ln840_fu_875_p2;
wire   [27:0] select_ln64_fu_897_p3;
wire   [24:0] tmp_2_fu_904_p4;
wire   [0:0] xor_ln1039_fu_924_p2;
wire   [0:0] icmp_ln1035_4_fu_914_p2;
wire   [0:0] or_ln1039_fu_937_p2;
wire   [2:0] select_ln1039_fu_929_p3;
wire   [2:0] trunc_ln91_fu_920_p1;
wire   [0:0] icmp_ln1019_1_fu_967_p2;
wire   [0:0] tmp_3_fu_950_p3;
wire   [0:0] icmp_ln1035_5_fu_957_p2;
wire   [0:0] and_ln64_1_fu_972_p2;
wire   [0:0] or_ln64_1_fu_978_p2;
wire   [27:0] add_ln840_1_fu_962_p2;
wire   [27:0] select_ln64_1_fu_984_p3;
wire   [24:0] tmp_4_fu_991_p4;
wire   [0:0] xor_ln1039_1_fu_1011_p2;
wire   [0:0] icmp_ln1035_6_fu_1001_p2;
wire   [0:0] or_ln1039_1_fu_1024_p2;
wire   [2:0] select_ln1039_4_fu_1016_p3;
wire   [2:0] trunc_ln91_1_fu_1007_p1;
wire   [0:0] icmp_ln1019_2_fu_1054_p2;
wire   [0:0] tmp_5_fu_1037_p3;
wire   [0:0] icmp_ln1035_8_fu_1044_p2;
wire   [0:0] and_ln64_2_fu_1059_p2;
wire   [0:0] or_ln64_2_fu_1065_p2;
wire   [27:0] add_ln840_2_fu_1049_p2;
wire   [27:0] select_ln64_2_fu_1071_p3;
wire   [24:0] tmp_6_fu_1078_p4;
wire   [0:0] xor_ln1039_2_fu_1098_p2;
wire   [0:0] icmp_ln1035_9_fu_1088_p2;
wire   [0:0] or_ln1039_2_fu_1111_p2;
wire   [2:0] select_ln1039_6_fu_1103_p3;
wire   [2:0] trunc_ln91_2_fu_1094_p1;
wire   [0:0] icmp_ln1019_3_fu_1141_p2;
wire   [0:0] tmp_7_fu_1124_p3;
wire   [0:0] icmp_ln1035_11_fu_1131_p2;
wire   [0:0] and_ln64_3_fu_1146_p2;
wire   [0:0] or_ln64_3_fu_1152_p2;
wire   [27:0] add_ln840_3_fu_1136_p2;
wire   [27:0] select_ln64_3_fu_1158_p3;
wire   [24:0] tmp_8_fu_1165_p4;
wire   [0:0] xor_ln1039_3_fu_1185_p2;
wire   [0:0] icmp_ln1035_12_fu_1175_p2;
wire   [0:0] or_ln1039_3_fu_1198_p2;
wire   [2:0] select_ln1039_8_fu_1190_p3;
wire   [2:0] trunc_ln91_3_fu_1181_p1;
wire   [0:0] icmp_ln1035_7_fu_1211_p2;
wire   [2:0] select_ln268_fu_1215_p3;
wire   [0:0] icmp_ln1035_10_fu_1221_p2;
wire   [2:0] select_ln268_1_fu_1226_p3;
wire   [0:0] icmp_ln1035_13_fu_1233_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [67:0] grp_fu_765_p00;
wire   [67:0] grp_fu_783_p00;
wire   [67:0] grp_fu_801_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_w4a4_top_mul_32ns_37ns_68_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 37 ),
    .dout_WIDTH( 68 ))
mul_32ns_37ns_68_2_1_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_765_p0),
    .din1(grp_fu_765_p1),
    .ce(1'b1),
    .dout(grp_fu_765_p2)
);

lenet_w4a4_top_mul_32ns_37ns_68_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 37 ),
    .dout_WIDTH( 68 ))
mul_32ns_37ns_68_2_1_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_783_p0),
    .din1(grp_fu_783_p1),
    .ce(1'b1),
    .dout(grp_fu_783_p2)
);

lenet_w4a4_top_mul_32ns_37ns_68_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 37 ),
    .dout_WIDTH( 68 ))
mul_32ns_37ns_68_2_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_801_p0),
    .din1(grp_fu_801_p1),
    .ce(1'b1),
    .dout(grp_fu_801_p2)
);

lenet_w4a4_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            channel_fu_110 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln221_reg_1290 == 1'd0))) begin
            channel_fu_110 <= select_ln221_6_fu_461_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln221_fu_211_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten208_fu_106 <= select_ln226_4_fu_301_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten208_fu_106 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln221_fu_211_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten264_fu_114 <= add_ln221_fu_217_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten264_fu_114 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln221_fu_211_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_col_fu_98 <= add_ln232_fu_289_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            output_col_fu_98 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln221_fu_211_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            output_row_fu_102 <= select_ln226_3_fu_281_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            output_row_fu_102 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln222_reg_1332 <= add_ln222_fu_394_p2;
        and_ln221_reg_1304_pp0_iter1_reg <= and_ln221_reg_1304;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_1322 <= empty_fu_332_p1;
        icmp_ln221_reg_1290 <= icmp_ln221_fu_211_p2;
        icmp_ln221_reg_1290_pp0_iter1_reg <= icmp_ln221_reg_1290;
        icmp_ln226_reg_1294_pp0_iter1_reg <= icmp_ln226_reg_1294;
        output_row_1_reg_1284 <= ap_sig_allocacmp_output_row_1;
        select_ln226_reg_1316_pp0_iter1_reg <= select_ln226_reg_1316;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln221_fu_211_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln227_reg_1310 <= add_ln227_fu_261_p2;
        and_ln221_reg_1304 <= and_ln221_fu_255_p2;
        icmp_ln226_reg_1294 <= icmp_ln226_fu_229_p2;
        select_ln226_reg_1316 <= select_ln226_fu_273_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln221_reg_1290_pp0_iter1_reg == 1'd0))) begin
        add_ln278_1_reg_1374 <= add_ln278_1_fu_729_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln278_1_reg_1374_pp0_iter3_reg <= add_ln278_1_reg_1374;
        add_ln278_1_reg_1374_pp0_iter4_reg <= add_ln278_1_reg_1374_pp0_iter3_reg;
        add_ln278_1_reg_1374_pp0_iter5_reg <= add_ln278_1_reg_1374_pp0_iter4_reg;
        add_ln278_1_reg_1374_pp0_iter6_reg <= add_ln278_1_reg_1374_pp0_iter5_reg;
        add_ln278_1_reg_1374_pp0_iter7_reg <= add_ln278_1_reg_1374_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln1039_1_reg_1414 <= icmp_ln1039_1_fu_753_p2;
        icmp_ln1039_1_reg_1414_pp0_iter5_reg <= icmp_ln1039_1_reg_1414;
        icmp_ln1039_2_reg_1425 <= icmp_ln1039_2_fu_771_p2;
        icmp_ln1039_2_reg_1425_pp0_iter5_reg <= icmp_ln1039_2_reg_1425;
        icmp_ln1039_3_reg_1436 <= icmp_ln1039_3_fu_789_p2;
        icmp_ln1039_3_reg_1436_pp0_iter5_reg <= icmp_ln1039_3_reg_1436;
        icmp_ln1039_reg_1403 <= icmp_ln1039_fu_735_p2;
        icmp_ln1039_reg_1403_pp0_iter5_reg <= icmp_ln1039_reg_1403;
        mul_ln186_1_reg_1464 <= grp_fu_765_p2;
        mul_ln186_2_reg_1481 <= grp_fu_783_p2;
        mul_ln186_3_reg_1498 <= grp_fu_801_p2;
        mul_ln186_reg_1447 <= grp_fu_1456_p_dout0;
        select_ln1039_3_reg_1515 <= select_ln1039_3_fu_942_p3;
        select_ln1039_5_reg_1521 <= select_ln1039_5_fu_1029_p3;
        select_ln1039_7_reg_1527 <= select_ln1039_7_fu_1116_p3;
        select_ln1039_9_reg_1533 <= select_ln1039_9_fu_1203_p3;
        select_ln268_2_reg_1539 <= select_ln268_2_fu_1238_p3;
        trunc_ln1669_1_reg_1469 <= trunc_ln1669_1_fu_821_p1;
        trunc_ln1669_2_reg_1486 <= trunc_ln1669_2_fu_835_p1;
        trunc_ln1669_3_reg_1503 <= trunc_ln1669_3_fu_849_p1;
        trunc_ln1669_reg_1452 <= trunc_ln1669_fu_807_p1;
        trunc_ln186_2_reg_1458 <= {{grp_fu_1456_p_dout0[67:40]}};
        trunc_ln186_5_reg_1475 <= {{grp_fu_765_p2[67:40]}};
        trunc_ln186_7_reg_1492 <= {{grp_fu_783_p2[67:40]}};
        trunc_ln186_8_reg_1509 <= {{grp_fu_801_p2[67:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv2_acc_V_load_1_reg_1385 <= conv2_acc_V_q2;
        conv2_acc_V_load_2_reg_1391 <= conv2_acc_V_q1;
        conv2_acc_V_load_3_reg_1397 <= conv2_acc_V_q0;
        conv2_acc_V_load_reg_1379 <= conv2_acc_V_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln221_reg_1290 == 1'd0))) begin
        empty_73_reg_1337 <= empty_73_fu_400_p1;
        select_ln226_2_reg_1347[7 : 1] <= select_ln226_2_fu_504_p3[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln221_reg_1304) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln221_reg_1290 == 1'd0))) begin
        tmp66_mid1_reg_1342 <= tmp66_mid1_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == and_ln221_reg_1304) & (icmp_ln226_reg_1294 == 1'd0))) begin
        tmp66_reg_1327 <= tmp66_fu_372_p2;
    end
end

always @ (*) begin
    if (((icmp_ln221_fu_211_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln221_reg_1290_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten208_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten208_load = indvar_flatten208_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten264_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten264_load = indvar_flatten264_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_col_load = 3'd0;
    end else begin
        ap_sig_allocacmp_output_col_load = output_col_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_row_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_output_row_1 = output_row_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_acc_V_ce0 = 1'b1;
    end else begin
        conv2_acc_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_acc_V_ce1 = 1'b1;
    end else begin
        conv2_acc_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_acc_V_ce2 = 1'b1;
    end else begin
        conv2_acc_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_acc_V_ce3 = 1'b1;
    end else begin
        conv2_acc_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        pool2_V_ce0 = 1'b1;
    end else begin
        pool2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        pool2_V_we0 = 1'b1;
    end else begin
        pool2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln221_fu_217_p2 = (ap_sig_allocacmp_indvar_flatten264_load + 9'd1);

assign add_ln222_fu_394_p2 = (channel_fu_110 + 5'd1);

assign add_ln226_fu_295_p2 = (ap_sig_allocacmp_indvar_flatten208_load + 6'd1);

assign add_ln227_fu_261_p2 = (select_ln221_fu_235_p3 + 3'd1);

assign add_ln232_fu_289_p2 = (select_ln226_fu_273_p3 + 3'd1);

assign add_ln258_1_fu_665_p2 = (zext_ln258_2_fu_661_p1 + p_shl27_0_mid2_fu_598_p3);

assign add_ln258_2_fu_687_p2 = (zext_ln226_2_fu_633_p1 + zext_ln258_fu_647_p1);

assign add_ln258_3_fu_697_p2 = (zext_ln258_3_fu_693_p1 + p_shl27_1_mid2_fu_617_p3);

assign add_ln258_fu_655_p2 = (p_shl28_0_mid2_fu_605_p3 + zext_ln258_1_fu_651_p1);

assign add_ln278_1_fu_729_p2 = (zext_ln278_fu_725_p1 + p_shl26_mid2_fu_590_p3);

assign add_ln278_fu_719_p2 = (select_ln226_1_fu_583_p3 + output_col_1_cast115_fu_637_p1);

assign add_ln840_1_fu_962_p2 = (trunc_ln186_5_reg_1475 + 28'd1);

assign add_ln840_2_fu_1049_p2 = (trunc_ln186_7_reg_1492 + 28'd1);

assign add_ln840_3_fu_1136_p2 = (trunc_ln186_8_reg_1509 + 28'd1);

assign add_ln840_fu_875_p2 = (trunc_ln186_2_reg_1458 + 28'd1);

assign and_ln221_fu_255_p2 = (xor_ln221_fu_243_p2 & icmp_ln231_fu_249_p2);

assign and_ln64_1_fu_972_p2 = (tmp_3_fu_950_p3 & icmp_ln1019_1_fu_967_p2);

assign and_ln64_2_fu_1059_p2 = (tmp_5_fu_1037_p3 & icmp_ln1019_2_fu_1054_p2);

assign and_ln64_3_fu_1146_p2 = (tmp_7_fu_1124_p3 & icmp_ln1019_3_fu_1141_p2);

assign and_ln64_fu_885_p2 = (tmp_fu_863_p3 & icmp_ln1019_fu_880_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv2_acc_V_address0 = zext_ln263_3_fu_714_p1;

assign conv2_acc_V_address1 = zext_ln263_2_fu_703_p1;

assign conv2_acc_V_address2 = zext_ln263_1_fu_682_p1;

assign conv2_acc_V_address3 = zext_ln263_fu_671_p1;

assign empty_69_fu_348_p2 = channel_fu_110 << 5'd1;

assign empty_70_fu_530_p2 = (tmp66_cast_fu_527_p1 + zext_ln225_fu_523_p1);

assign empty_71_fu_388_p2 = (tmp67_cast_fu_384_p1 + p_shl24_cast_fu_344_p1);

assign empty_73_fu_400_p1 = add_ln222_fu_394_p2[3:0];

assign empty_74_fu_427_p2 = add_ln222_fu_394_p2 << 5'd1;

assign empty_fu_332_p1 = channel_fu_110[3:0];

assign grp_fu_1456_p_ce = 1'b1;

assign grp_fu_1456_p_din0 = zext_ln186_fu_743_p1;

assign grp_fu_1456_p_din1 = 68'd41310957922;

assign grp_fu_765_p0 = grp_fu_765_p00;

assign grp_fu_765_p00 = $unsigned(sext_ln186_1_fu_758_p1);

assign grp_fu_765_p1 = 68'd41310957922;

assign grp_fu_783_p0 = grp_fu_783_p00;

assign grp_fu_783_p00 = $unsigned(sext_ln186_2_fu_776_p1);

assign grp_fu_783_p1 = 68'd41310957922;

assign grp_fu_801_p0 = grp_fu_801_p00;

assign grp_fu_801_p00 = $unsigned(sext_ln186_3_fu_794_p1);

assign grp_fu_801_p1 = 68'd41310957922;

assign icmp_ln1019_1_fu_967_p2 = ((trunc_ln1669_1_reg_1469 == 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_1054_p2 = ((trunc_ln1669_2_reg_1486 == 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1019_3_fu_1141_p2 = ((trunc_ln1669_3_reg_1503 == 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_880_p2 = ((trunc_ln1669_reg_1452 == 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1035_10_fu_1221_p2 = ((select_ln1039_7_reg_1527 > select_ln268_fu_1215_p3) ? 1'b1 : 1'b0);

assign icmp_ln1035_11_fu_1131_p2 = ((trunc_ln1669_3_reg_1503 > 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1035_12_fu_1175_p2 = ((tmp_8_fu_1165_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1035_13_fu_1233_p2 = ((select_ln1039_9_reg_1533 > select_ln268_1_fu_1226_p3) ? 1'b1 : 1'b0);

assign icmp_ln1035_4_fu_914_p2 = ((tmp_2_fu_904_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1035_5_fu_957_p2 = ((trunc_ln1669_1_reg_1469 > 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1035_6_fu_1001_p2 = ((tmp_4_fu_991_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1035_7_fu_1211_p2 = ((select_ln1039_5_reg_1521 > select_ln1039_3_reg_1515) ? 1'b1 : 1'b0);

assign icmp_ln1035_8_fu_1044_p2 = ((trunc_ln1669_2_reg_1486 > 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1035_9_fu_1088_p2 = ((tmp_6_fu_1078_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_870_p2 = ((trunc_ln1669_reg_1452 > 40'd549755813888) ? 1'b1 : 1'b0);

assign icmp_ln1039_1_fu_753_p2 = (($signed(conv2_acc_V_load_1_reg_1385) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_771_p2 = (($signed(conv2_acc_V_load_2_reg_1391) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_3_fu_789_p2 = (($signed(conv2_acc_V_load_3_reg_1397) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_735_p2 = (($signed(conv2_acc_V_load_reg_1379) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_211_p2 = ((ap_sig_allocacmp_indvar_flatten264_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln226_fu_229_p2 = ((ap_sig_allocacmp_indvar_flatten208_load == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln231_fu_249_p2 = ((ap_sig_allocacmp_output_col_load == 3'd5) ? 1'b1 : 1'b0);

assign or_ln1039_1_fu_1024_p2 = (icmp_ln1039_1_reg_1414_pp0_iter5_reg | icmp_ln1035_6_fu_1001_p2);

assign or_ln1039_2_fu_1111_p2 = (icmp_ln1039_2_reg_1425_pp0_iter5_reg | icmp_ln1035_9_fu_1088_p2);

assign or_ln1039_3_fu_1198_p2 = (icmp_ln1039_3_reg_1436_pp0_iter5_reg | icmp_ln1035_12_fu_1175_p2);

assign or_ln1039_fu_937_p2 = (icmp_ln1039_reg_1403_pp0_iter5_reg | icmp_ln1035_4_fu_914_p2);

assign or_ln226_1_fu_612_p2 = (select_ln226_2_reg_1347 | 8'd1);

assign or_ln226_fu_267_p2 = (icmp_ln226_fu_229_p2 | and_ln221_fu_255_p2);

assign or_ln258_1_fu_708_p2 = (11'd1 | add_ln258_3_fu_697_p2);

assign or_ln258_fu_676_p2 = (11'd1 | add_ln258_1_fu_665_p2);

assign or_ln64_1_fu_978_p2 = (icmp_ln1035_5_fu_957_p2 | and_ln64_1_fu_972_p2);

assign or_ln64_2_fu_1065_p2 = (icmp_ln1035_8_fu_1044_p2 | and_ln64_2_fu_1059_p2);

assign or_ln64_3_fu_1152_p2 = (icmp_ln1035_11_fu_1131_p2 | and_ln64_3_fu_1146_p2);

assign or_ln64_fu_891_p2 = (icmp_ln1035_fu_870_p2 | and_ln64_fu_885_p2);

assign output_col_1_cast115_fu_637_p1 = select_ln226_reg_1316_pp0_iter1_reg;

assign p_cast100_fu_368_p1 = tmp_s_fu_361_p3;

assign p_cast100_mid1_fu_478_p1 = p_mid2_fu_471_p3;

assign p_mid1202_fu_577_p2 = (tmp66_cast_mid1_fu_574_p1 + zext_ln221_3_fu_557_p1);

assign p_mid1204_fu_498_p2 = (tmp67_cast_mid1_fu_494_p1 + zext_ln221_1_fu_423_p1);

assign p_mid1230_fu_561_p2 = (zext_ln221_fu_536_p1 + zext_ln225_1_fu_546_p1);

assign p_mid1240_fu_448_p2 = (tmp67_cast_mid1238_fu_444_p1 + p_shl24_cast_mid1_fu_412_p1);

assign p_mid2_fu_471_p3 = {{add_ln227_reg_1310}, {1'd0}};

assign p_shl23_mid1_fu_539_p3 = {{empty_73_reg_1337}, {2'd0}};

assign p_shl24_cast_fu_344_p1 = p_shl_fu_336_p3;

assign p_shl24_cast_mid1_fu_412_p1 = p_shl24_mid1_fu_404_p3;

assign p_shl24_mid1_fu_404_p3 = {{empty_73_fu_400_p1}, {3'd0}};

assign p_shl25_cast_fu_354_p1 = empty_69_fu_348_p2;

assign p_shl26_mid2_fu_590_p3 = {{select_ln226_1_fu_583_p3}, {2'd0}};

assign p_shl27_0_mid2_fu_598_p3 = {{select_ln226_2_reg_1347}, {3'd0}};

assign p_shl27_1_mid2_fu_617_p3 = {{or_ln226_1_fu_612_p2}, {3'd0}};

assign p_shl28_0_mid2_fu_605_p3 = {{select_ln226_2_reg_1347}, {1'd0}};

assign p_shl5_fu_516_p3 = {{empty_reg_1322}, {2'd0}};

assign p_shl_fu_336_p3 = {{empty_fu_332_p1}, {3'd0}};

assign pool2_V_address0 = zext_ln281_fu_1245_p1;

assign pool2_V_d0 = select_ln268_2_reg_1539;

assign select_ln1039_3_fu_942_p3 = ((or_ln1039_fu_937_p2[0:0] == 1'b1) ? select_ln1039_fu_929_p3 : trunc_ln91_fu_920_p1);

assign select_ln1039_4_fu_1016_p3 = ((xor_ln1039_1_fu_1011_p2[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign select_ln1039_5_fu_1029_p3 = ((or_ln1039_1_fu_1024_p2[0:0] == 1'b1) ? select_ln1039_4_fu_1016_p3 : trunc_ln91_1_fu_1007_p1);

assign select_ln1039_6_fu_1103_p3 = ((xor_ln1039_2_fu_1098_p2[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign select_ln1039_7_fu_1116_p3 = ((or_ln1039_2_fu_1111_p2[0:0] == 1'b1) ? select_ln1039_6_fu_1103_p3 : trunc_ln91_2_fu_1094_p1);

assign select_ln1039_8_fu_1190_p3 = ((xor_ln1039_3_fu_1185_p2[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign select_ln1039_9_fu_1203_p3 = ((or_ln1039_3_fu_1198_p2[0:0] == 1'b1) ? select_ln1039_8_fu_1190_p3 : trunc_ln91_3_fu_1181_p1);

assign select_ln1039_fu_929_p3 = ((xor_ln1039_fu_924_p2[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign select_ln221_1_fu_416_p3 = ((icmp_ln226_reg_1294[0:0] == 1'b1) ? p_shl24_mid1_fu_404_p3 : p_shl_fu_336_p3);

assign select_ln221_2_fu_433_p3 = ((icmp_ln226_reg_1294[0:0] == 1'b1) ? empty_74_fu_427_p2 : empty_69_fu_348_p2);

assign select_ln221_3_fu_550_p3 = ((icmp_ln226_reg_1294_pp0_iter1_reg[0:0] == 1'b1) ? p_shl23_mid1_fu_539_p3 : p_shl5_fu_516_p3);

assign select_ln221_4_fu_567_p3 = ((icmp_ln226_reg_1294_pp0_iter1_reg[0:0] == 1'b1) ? p_mid1230_fu_561_p2 : empty_70_fu_530_p2);

assign select_ln221_5_fu_454_p3 = ((icmp_ln226_reg_1294[0:0] == 1'b1) ? p_mid1240_fu_448_p2 : empty_71_fu_388_p2);

assign select_ln221_6_fu_461_p3 = ((icmp_ln226_reg_1294[0:0] == 1'b1) ? add_ln222_fu_394_p2 : channel_fu_110);

assign select_ln221_fu_235_p3 = ((icmp_ln226_fu_229_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_output_row_1);

assign select_ln226_1_fu_583_p3 = ((and_ln221_reg_1304_pp0_iter1_reg[0:0] == 1'b1) ? p_mid1202_fu_577_p2 : select_ln221_4_fu_567_p3);

assign select_ln226_2_fu_504_p3 = ((and_ln221_reg_1304[0:0] == 1'b1) ? p_mid1204_fu_498_p2 : select_ln221_5_fu_454_p3);

assign select_ln226_3_fu_281_p3 = ((and_ln221_fu_255_p2[0:0] == 1'b1) ? add_ln227_fu_261_p2 : select_ln221_fu_235_p3);

assign select_ln226_4_fu_301_p3 = ((icmp_ln226_fu_229_p2[0:0] == 1'b1) ? 6'd1 : add_ln226_fu_295_p2);

assign select_ln226_fu_273_p3 = ((or_ln226_fu_267_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_output_col_load);

assign select_ln268_1_fu_1226_p3 = ((icmp_ln1035_10_fu_1221_p2[0:0] == 1'b1) ? select_ln1039_7_reg_1527 : select_ln268_fu_1215_p3);

assign select_ln268_2_fu_1238_p3 = ((icmp_ln1035_13_fu_1233_p2[0:0] == 1'b1) ? select_ln1039_9_reg_1533 : select_ln268_1_fu_1226_p3);

assign select_ln268_fu_1215_p3 = ((icmp_ln1035_7_fu_1211_p2[0:0] == 1'b1) ? select_ln1039_5_reg_1521 : select_ln1039_3_reg_1515);

assign select_ln64_1_fu_984_p3 = ((or_ln64_1_fu_978_p2[0:0] == 1'b1) ? add_ln840_1_fu_962_p2 : trunc_ln186_5_reg_1475);

assign select_ln64_2_fu_1071_p3 = ((or_ln64_2_fu_1065_p2[0:0] == 1'b1) ? add_ln840_2_fu_1049_p2 : trunc_ln186_7_reg_1492);

assign select_ln64_3_fu_1158_p3 = ((or_ln64_3_fu_1152_p2[0:0] == 1'b1) ? add_ln840_3_fu_1136_p2 : trunc_ln186_8_reg_1509);

assign select_ln64_fu_897_p3 = ((or_ln64_fu_891_p2[0:0] == 1'b1) ? add_ln840_fu_875_p2 : trunc_ln186_2_reg_1458);

assign sext_ln186_1_fu_758_p1 = conv2_acc_V_load_1_reg_1385;

assign sext_ln186_2_fu_776_p1 = conv2_acc_V_load_2_reg_1391;

assign sext_ln186_3_fu_794_p1 = conv2_acc_V_load_3_reg_1397;

assign sext_ln186_fu_740_p1 = conv2_acc_V_load_reg_1379;

assign tmp66_cast_fu_527_p1 = tmp66_reg_1327;

assign tmp66_cast_mid1_fu_574_p1 = tmp66_mid1_reg_1342;

assign tmp66_fu_372_p2 = (channel_fu_110 + zext_ln226_fu_358_p1);

assign tmp66_mid1_fu_482_p2 = (select_ln221_6_fu_461_p3 + zext_ln226_1_fu_468_p1);

assign tmp67_cast_fu_384_p1 = tmp67_fu_378_p2;

assign tmp67_cast_mid1238_fu_444_p1 = empty_74_fu_427_p2;

assign tmp67_cast_mid1_fu_494_p1 = tmp67_mid1_fu_488_p2;

assign tmp67_fu_378_p2 = (p_shl25_cast_fu_354_p1 + p_cast100_fu_368_p1);

assign tmp67_mid1_fu_488_p2 = (zext_ln221_2_fu_440_p1 + p_cast100_mid1_fu_478_p1);

assign tmp_1_fu_640_p3 = {{select_ln226_reg_1316_pp0_iter1_reg}, {1'd0}};

assign tmp_2_fu_904_p4 = {{select_ln64_fu_897_p3[27:3]}};

assign tmp_3_fu_950_p3 = mul_ln186_1_reg_1464[32'd40];

assign tmp_4_fu_991_p4 = {{select_ln64_1_fu_984_p3[27:3]}};

assign tmp_5_fu_1037_p3 = mul_ln186_2_reg_1481[32'd40];

assign tmp_6_fu_1078_p4 = {{select_ln64_2_fu_1071_p3[27:3]}};

assign tmp_7_fu_1124_p3 = mul_ln186_3_reg_1498[32'd40];

assign tmp_8_fu_1165_p4 = {{select_ln64_3_fu_1158_p3[27:3]}};

assign tmp_fu_863_p3 = mul_ln186_reg_1447[32'd40];

assign tmp_s_fu_361_p3 = {{output_row_1_reg_1284}, {1'd0}};

assign trunc_ln1669_1_fu_821_p1 = grp_fu_765_p2[39:0];

assign trunc_ln1669_2_fu_835_p1 = grp_fu_783_p2[39:0];

assign trunc_ln1669_3_fu_849_p1 = grp_fu_801_p2[39:0];

assign trunc_ln1669_fu_807_p1 = grp_fu_1456_p_dout0[39:0];

assign trunc_ln91_1_fu_1007_p1 = select_ln64_1_fu_984_p3[2:0];

assign trunc_ln91_2_fu_1094_p1 = select_ln64_2_fu_1071_p3[2:0];

assign trunc_ln91_3_fu_1181_p1 = select_ln64_3_fu_1158_p3[2:0];

assign trunc_ln91_fu_920_p1 = select_ln64_fu_897_p3[2:0];

assign xor_ln1039_1_fu_1011_p2 = (icmp_ln1039_1_reg_1414_pp0_iter5_reg ^ 1'd1);

assign xor_ln1039_2_fu_1098_p2 = (icmp_ln1039_2_reg_1425_pp0_iter5_reg ^ 1'd1);

assign xor_ln1039_3_fu_1185_p2 = (icmp_ln1039_3_reg_1436_pp0_iter5_reg ^ 1'd1);

assign xor_ln1039_fu_924_p2 = (icmp_ln1039_reg_1403_pp0_iter5_reg ^ 1'd1);

assign xor_ln221_fu_243_p2 = (icmp_ln226_fu_229_p2 ^ 1'd1);

assign zext_ln186_fu_743_p1 = $unsigned(sext_ln186_fu_740_p1);

assign zext_ln221_1_fu_423_p1 = select_ln221_1_fu_416_p3;

assign zext_ln221_2_fu_440_p1 = select_ln221_2_fu_433_p3;

assign zext_ln221_3_fu_557_p1 = select_ln221_3_fu_550_p3;

assign zext_ln221_fu_536_p1 = add_ln222_reg_1332;

assign zext_ln225_1_fu_546_p1 = p_shl23_mid1_fu_539_p3;

assign zext_ln225_fu_523_p1 = p_shl5_fu_516_p3;

assign zext_ln226_1_fu_468_p1 = add_ln227_reg_1310;

assign zext_ln226_2_fu_633_p1 = zext_ln230_mid2_v_fu_625_p3;

assign zext_ln226_fu_358_p1 = output_row_1_reg_1284;

assign zext_ln230_mid2_v_fu_625_p3 = {{or_ln226_1_fu_612_p2}, {1'd0}};

assign zext_ln258_1_fu_651_p1 = tmp_1_fu_640_p3;

assign zext_ln258_2_fu_661_p1 = add_ln258_fu_655_p2;

assign zext_ln258_3_fu_693_p1 = add_ln258_2_fu_687_p2;

assign zext_ln258_fu_647_p1 = tmp_1_fu_640_p3;

assign zext_ln263_1_fu_682_p1 = or_ln258_fu_676_p2;

assign zext_ln263_2_fu_703_p1 = add_ln258_3_fu_697_p2;

assign zext_ln263_3_fu_714_p1 = or_ln258_1_fu_708_p2;

assign zext_ln263_fu_671_p1 = add_ln258_1_fu_665_p2;

assign zext_ln278_fu_725_p1 = add_ln278_fu_719_p2;

assign zext_ln281_fu_1245_p1 = add_ln278_1_reg_1374_pp0_iter7_reg;

always @ (posedge ap_clk) begin
    select_ln226_2_reg_1347[0] <= 1'b0;
end

endmodule //lenet_w4a4_top_lenet_w4a4_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL2
