-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2_output_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_output_ce0 : OUT STD_LOGIC;
    conv2_output_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_output_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_output_ce1 : OUT STD_LOGIC;
    conv2_output_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_output_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_output_ce2 : OUT STD_LOGIC;
    conv2_output_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_output_address3 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_output_ce3 : OUT STD_LOGIC;
    conv2_output_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    pool2_output_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pool2_output_ce0 : OUT STD_LOGIC;
    pool2_output_we0 : OUT STD_LOGIC;
    pool2_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1406_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1406_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1406_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1406_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1406_p_ce : OUT STD_LOGIC;
    grp_fu_1410_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1410_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1410_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1410_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1410_p_ce : OUT STD_LOGIC;
    grp_fu_1414_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1414_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1414_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1414_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1414_p_ce : OUT STD_LOGIC;
    grp_fu_1418_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1418_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1418_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1418_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1418_p_ce : OUT STD_LOGIC );
end;


architecture behav of lenet_full_top_lenet_full_top_Pipeline_POOL_CHANNEL_POOL_ROW_POOL_COL1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln91_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln91_reg_1074 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_1074_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_reg_1078 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_reg_1078_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_262_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_1091 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp3_fu_292_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp3_reg_1097 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp4_fu_298_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp4_reg_1102 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln91_fu_304_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln91_reg_1107 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_34_fu_320_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_34_reg_1113 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln91_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_reg_1118 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln91_6_fu_354_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln91_6_reg_1124 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln93_fu_361_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln93_reg_1129 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln93_fu_372_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln93_reg_1134 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln93_reg_1134_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp4_mid1_fu_392_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp4_mid1_reg_1140 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_fu_406_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln95_reg_1145 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln93_1_fu_561_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln93_1_reg_1150 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln93_2_fu_577_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln93_2_reg_1156 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln93_1_fu_592_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln93_1_reg_1161 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln105_fu_625_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln105_reg_1166 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln105_2_fu_631_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln105_2_reg_1171 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln114_1_fu_724_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter10_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter11_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter12_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter13_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter14_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln114_1_reg_1196_pp0_iter15_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal conv2_output_load_reg_1201 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_reg_1201_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_reg_1201_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_1_reg_1208_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_2_reg_1215_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_output_load_3_reg_1222_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1229 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_fu_770_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_reg_1234 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_reg_1234_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_reg_1234_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_reg_1241 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_1_fu_858_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_1_reg_1246 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_1_reg_1246_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_1_reg_1246_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_reg_1253 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_2_fu_945_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_2_reg_1258 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_2_reg_1258_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln107_2_reg_1258_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln107_10_fu_985_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_10_reg_1265 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_11_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_11_reg_1270 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_12_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_12_reg_1275 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_13_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_13_reg_1280 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_1285 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln106_fu_674_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln106_1_fu_685_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln106_2_fu_699_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln106_3_fu_710_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln115_fu_1035_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_col_fu_84 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_output_col_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal output_row_fu_88 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln93_3_fu_398_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten127_fu_92 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln93_4_fu_238_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten127_load : STD_LOGIC_VECTOR (5 downto 0);
    signal channel_fu_96 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten183_fu_100 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln91_1_fu_217_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten183_load : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln93_1_fu_232_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_29_fu_266_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_280_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln93_1_fu_276_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl26_cast_fu_272_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_cast38_fu_288_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln91_2_fu_326_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln95_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln91_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln91_fu_313_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln93_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid2_fu_380_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln91_2_fu_333_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_cast38_mid1_fu_388_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_422_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl1_fu_433_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp3_cast_fu_444_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln93_fu_440_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp4_cast_fu_453_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl25_cast_fu_429_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_33_fu_465_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl25_mid1_fu_468_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln91_1_fu_480_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl24_mid1_fu_491_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln91_3_fu_503_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln91_fu_462_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln93_2_fu_499_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_mid1149_fu_514_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_30_fu_447_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp4_cast_mid1157_fu_527_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl25_cast_mid1_fu_476_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid1159_fu_530_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_31_fu_456_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln93_3_fu_543_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp3_mid1_fu_546_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp3_cast_mid1_fu_551_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln91_3_fu_510_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_mid1121_fu_555_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln91_4_fu_520_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp4_cast_mid1_fu_568_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln91_1_fu_487_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid1123_fu_571_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln91_5_fu_536_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln95_mid2_v_fu_598_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_610_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl29_0_mid2_fu_584_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln105_1_fu_621_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln93_4_fu_606_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln105_fu_617_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln105_2_fu_665_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl28_0_mid2_fu_648_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln105_1_fu_668_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln105_fu_679_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln105_3_fu_690_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl28_1_mid2_fu_655_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln105_3_fu_693_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln105_1_fu_704_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal output_col_2_cast51_fu_662_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln114_fu_715_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln114_fu_720_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl27_mid2_fu_641_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal bitcast_ln107_fu_730_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_733_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_fu_743_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln107_1_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln107_1_fu_777_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln107_2_fu_794_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_780_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_1_fu_790_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln107_3_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_2_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_797_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_2_fu_807_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln107_5_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_4_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_1_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_2_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_1_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_2_fu_853_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln107_3_fu_864_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln107_4_fu_881_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_867_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_3_fu_877_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln107_7_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_6_fu_898_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_884_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_4_fu_894_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln107_9_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_8_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_3_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_4_fu_928_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_3_fu_934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_4_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln107_5_fu_951_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln107_6_fu_968_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_954_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_5_fu_964_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_13_fu_971_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln107_6_fu_981_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln107_5_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_6_fu_1013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_5_fu_1017_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_6_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lenet_full_top_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component lenet_full_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component lenet_full_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter15_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    channel_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    channel_fu_96 <= ap_const_lv5_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln91_reg_1074 = ap_const_lv1_0))) then 
                    channel_fu_96 <= select_ln91_6_fu_354_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten127_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln91_fu_211_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten127_fu_92 <= select_ln93_4_fu_238_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten127_fu_92 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten183_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln91_fu_211_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten183_fu_100 <= add_ln91_1_fu_217_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten183_fu_100 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    output_col_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    output_col_fu_84 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln91_reg_1074_pp0_iter1_reg = ap_const_lv1_0))) then 
                    output_col_fu_84 <= add_ln95_reg_1145;
                end if;
            end if; 
        end if;
    end process;

    output_row_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    output_row_fu_88 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln91_reg_1074 = ap_const_lv1_0))) then 
                    output_row_fu_88 <= select_ln93_3_fu_398_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln91_reg_1074_pp0_iter1_reg = ap_const_lv1_0))) then
                    add_ln105_2_reg_1171(9 downto 1) <= add_ln105_2_fu_631_p2(9 downto 1);
                    add_ln105_reg_1166(8 downto 1) <= add_ln105_fu_625_p2(8 downto 1);
                    or_ln93_1_reg_1161(7 downto 1) <= or_ln93_1_fu_592_p2(7 downto 1);
                select_ln93_1_reg_1150 <= select_ln93_1_fu_561_p3;
                    select_ln93_2_reg_1156(7 downto 1) <= select_ln93_2_fu_577_p3(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln114_1_reg_1196 <= add_ln114_1_fu_724_p2;
                add_ln114_1_reg_1196_pp0_iter10_reg <= add_ln114_1_reg_1196_pp0_iter9_reg;
                add_ln114_1_reg_1196_pp0_iter11_reg <= add_ln114_1_reg_1196_pp0_iter10_reg;
                add_ln114_1_reg_1196_pp0_iter12_reg <= add_ln114_1_reg_1196_pp0_iter11_reg;
                add_ln114_1_reg_1196_pp0_iter13_reg <= add_ln114_1_reg_1196_pp0_iter12_reg;
                add_ln114_1_reg_1196_pp0_iter14_reg <= add_ln114_1_reg_1196_pp0_iter13_reg;
                add_ln114_1_reg_1196_pp0_iter15_reg <= add_ln114_1_reg_1196_pp0_iter14_reg;
                add_ln114_1_reg_1196_pp0_iter4_reg <= add_ln114_1_reg_1196;
                add_ln114_1_reg_1196_pp0_iter5_reg <= add_ln114_1_reg_1196_pp0_iter4_reg;
                add_ln114_1_reg_1196_pp0_iter6_reg <= add_ln114_1_reg_1196_pp0_iter5_reg;
                add_ln114_1_reg_1196_pp0_iter7_reg <= add_ln114_1_reg_1196_pp0_iter6_reg;
                add_ln114_1_reg_1196_pp0_iter8_reg <= add_ln114_1_reg_1196_pp0_iter7_reg;
                add_ln114_1_reg_1196_pp0_iter9_reg <= add_ln114_1_reg_1196_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv2_output_load_1_reg_1208_pp0_iter5_reg <= conv2_output_load_1_reg_1208;
                conv2_output_load_1_reg_1208_pp0_iter6_reg <= conv2_output_load_1_reg_1208_pp0_iter5_reg;
                conv2_output_load_1_reg_1208_pp0_iter7_reg <= conv2_output_load_1_reg_1208_pp0_iter6_reg;
                conv2_output_load_1_reg_1208_pp0_iter8_reg <= conv2_output_load_1_reg_1208_pp0_iter7_reg;
                conv2_output_load_1_reg_1208_pp0_iter9_reg <= conv2_output_load_1_reg_1208_pp0_iter8_reg;
                conv2_output_load_2_reg_1215_pp0_iter10_reg <= conv2_output_load_2_reg_1215_pp0_iter9_reg;
                conv2_output_load_2_reg_1215_pp0_iter11_reg <= conv2_output_load_2_reg_1215_pp0_iter10_reg;
                conv2_output_load_2_reg_1215_pp0_iter12_reg <= conv2_output_load_2_reg_1215_pp0_iter11_reg;
                conv2_output_load_2_reg_1215_pp0_iter5_reg <= conv2_output_load_2_reg_1215;
                conv2_output_load_2_reg_1215_pp0_iter6_reg <= conv2_output_load_2_reg_1215_pp0_iter5_reg;
                conv2_output_load_2_reg_1215_pp0_iter7_reg <= conv2_output_load_2_reg_1215_pp0_iter6_reg;
                conv2_output_load_2_reg_1215_pp0_iter8_reg <= conv2_output_load_2_reg_1215_pp0_iter7_reg;
                conv2_output_load_2_reg_1215_pp0_iter9_reg <= conv2_output_load_2_reg_1215_pp0_iter8_reg;
                conv2_output_load_3_reg_1222_pp0_iter10_reg <= conv2_output_load_3_reg_1222_pp0_iter9_reg;
                conv2_output_load_3_reg_1222_pp0_iter11_reg <= conv2_output_load_3_reg_1222_pp0_iter10_reg;
                conv2_output_load_3_reg_1222_pp0_iter12_reg <= conv2_output_load_3_reg_1222_pp0_iter11_reg;
                conv2_output_load_3_reg_1222_pp0_iter13_reg <= conv2_output_load_3_reg_1222_pp0_iter12_reg;
                conv2_output_load_3_reg_1222_pp0_iter14_reg <= conv2_output_load_3_reg_1222_pp0_iter13_reg;
                conv2_output_load_3_reg_1222_pp0_iter15_reg <= conv2_output_load_3_reg_1222_pp0_iter14_reg;
                conv2_output_load_3_reg_1222_pp0_iter5_reg <= conv2_output_load_3_reg_1222;
                conv2_output_load_3_reg_1222_pp0_iter6_reg <= conv2_output_load_3_reg_1222_pp0_iter5_reg;
                conv2_output_load_3_reg_1222_pp0_iter7_reg <= conv2_output_load_3_reg_1222_pp0_iter6_reg;
                conv2_output_load_3_reg_1222_pp0_iter8_reg <= conv2_output_load_3_reg_1222_pp0_iter7_reg;
                conv2_output_load_3_reg_1222_pp0_iter9_reg <= conv2_output_load_3_reg_1222_pp0_iter8_reg;
                conv2_output_load_reg_1201_pp0_iter5_reg <= conv2_output_load_reg_1201;
                conv2_output_load_reg_1201_pp0_iter6_reg <= conv2_output_load_reg_1201_pp0_iter5_reg;
                icmp_ln107_10_reg_1265 <= icmp_ln107_10_fu_985_p2;
                icmp_ln107_11_reg_1270 <= icmp_ln107_11_fu_991_p2;
                icmp_ln107_12_reg_1275 <= icmp_ln107_12_fu_997_p2;
                icmp_ln107_13_reg_1280 <= icmp_ln107_13_fu_1003_p2;
                select_ln107_1_reg_1246 <= select_ln107_1_fu_858_p3;
                select_ln107_1_reg_1246_pp0_iter11_reg <= select_ln107_1_reg_1246;
                select_ln107_1_reg_1246_pp0_iter12_reg <= select_ln107_1_reg_1246_pp0_iter11_reg;
                select_ln107_2_reg_1258 <= select_ln107_2_fu_945_p3;
                select_ln107_2_reg_1258_pp0_iter14_reg <= select_ln107_2_reg_1258;
                select_ln107_2_reg_1258_pp0_iter15_reg <= select_ln107_2_reg_1258_pp0_iter14_reg;
                select_ln107_reg_1234 <= select_ln107_fu_770_p3;
                select_ln107_reg_1234_pp0_iter8_reg <= select_ln107_reg_1234;
                select_ln107_reg_1234_pp0_iter9_reg <= select_ln107_reg_1234_pp0_iter8_reg;
                select_ln93_reg_1134_pp0_iter2_reg <= select_ln93_reg_1134;
                tmp_11_reg_1253 <= grp_fu_1414_p_dout0;
                tmp_14_reg_1285 <= grp_fu_1418_p_dout0;
                tmp_5_reg_1229 <= grp_fu_1406_p_dout0;
                tmp_8_reg_1241 <= grp_fu_1410_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln91_reg_1107 <= add_ln91_fu_304_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_reg_1091 <= empty_fu_262_p1;
                icmp_ln91_reg_1074 <= icmp_ln91_fu_211_p2;
                icmp_ln91_reg_1074_pp0_iter1_reg <= icmp_ln91_reg_1074;
                icmp_ln93_reg_1078_pp0_iter1_reg <= icmp_ln93_reg_1078;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln91_reg_1074 = ap_const_lv1_0))) then
                add_ln93_reg_1129 <= add_ln93_fu_361_p2;
                add_ln95_reg_1145 <= add_ln95_fu_406_p2;
                and_ln91_reg_1118 <= and_ln91_fu_348_p2;
                    empty_34_reg_1113(4 downto 1) <= empty_34_fu_320_p2(4 downto 1);
                select_ln91_6_reg_1124 <= select_ln91_6_fu_354_p3;
                select_ln93_reg_1134 <= select_ln93_fu_372_p3;
                    tmp4_mid1_reg_1140(5 downto 1) <= tmp4_mid1_fu_392_p2(5 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                conv2_output_load_1_reg_1208 <= conv2_output_q2;
                conv2_output_load_2_reg_1215 <= conv2_output_q1;
                conv2_output_load_3_reg_1222 <= conv2_output_q0;
                conv2_output_load_reg_1201 <= conv2_output_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln91_fu_211_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln93_reg_1078 <= icmp_ln93_fu_226_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln93_reg_1078 = ap_const_lv1_0))) then
                tmp3_reg_1097 <= tmp3_fu_292_p2;
                    tmp4_reg_1102(5 downto 1) <= tmp4_fu_298_p2(5 downto 1);
            end if;
        end if;
    end process;
    tmp4_reg_1102(0) <= '0';
    empty_34_reg_1113(0) <= '0';
    tmp4_mid1_reg_1140(0) <= '0';
    select_ln93_2_reg_1156(0) <= '0';
    or_ln93_1_reg_1161(0) <= '1';
    add_ln105_reg_1166(0) <= '0';
    add_ln105_2_reg_1171(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln105_1_fu_668_p2 <= std_logic_vector(unsigned(zext_ln105_2_fu_665_p1) + unsigned(p_shl28_0_mid2_fu_648_p3));
    add_ln105_2_fu_631_p2 <= std_logic_vector(unsigned(zext_ln93_4_fu_606_p1) + unsigned(zext_ln105_fu_617_p1));
    add_ln105_3_fu_693_p2 <= std_logic_vector(unsigned(zext_ln105_3_fu_690_p1) + unsigned(p_shl28_1_mid2_fu_655_p3));
    add_ln105_fu_625_p2 <= std_logic_vector(unsigned(p_shl29_0_mid2_fu_584_p3) + unsigned(zext_ln105_1_fu_621_p1));
    add_ln114_1_fu_724_p2 <= std_logic_vector(unsigned(zext_ln114_fu_720_p1) + unsigned(p_shl27_mid2_fu_641_p3));
    add_ln114_fu_715_p2 <= std_logic_vector(unsigned(select_ln93_1_reg_1150) + unsigned(output_col_2_cast51_fu_662_p1));
    add_ln91_1_fu_217_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten183_load) + unsigned(ap_const_lv9_1));
    add_ln91_fu_304_p2 <= std_logic_vector(unsigned(channel_fu_96) + unsigned(ap_const_lv5_1));
    add_ln93_1_fu_232_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten127_load) + unsigned(ap_const_lv6_1));
    add_ln93_fu_361_p2 <= std_logic_vector(unsigned(select_ln91_fu_313_p3) + unsigned(ap_const_lv3_1));
    add_ln95_fu_406_p2 <= std_logic_vector(unsigned(select_ln93_fu_372_p3) + unsigned(ap_const_lv3_1));
    and_ln107_1_fu_847_p2 <= (or_ln107_2_fu_841_p2 and or_ln107_1_fu_823_p2);
    and_ln107_2_fu_853_p2 <= (tmp_8_reg_1241 and and_ln107_1_fu_847_p2);
    and_ln107_3_fu_934_p2 <= (or_ln107_4_fu_928_p2 and or_ln107_3_fu_910_p2);
    and_ln107_4_fu_940_p2 <= (tmp_11_reg_1253 and and_ln107_3_fu_934_p2);
    and_ln107_5_fu_1017_p2 <= (or_ln107_6_fu_1013_p2 and or_ln107_5_fu_1009_p2);
    and_ln107_6_fu_1023_p2 <= (tmp_14_reg_1285 and and_ln107_5_fu_1017_p2);
    and_ln107_fu_765_p2 <= (tmp_5_reg_1229 and or_ln107_fu_759_p2);
    and_ln91_fu_348_p2 <= (xor_ln91_fu_337_p2 and icmp_ln95_fu_342_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln91_fu_211_p2)
    begin
        if (((icmp_ln91_fu_211_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln91_reg_1074_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln91_reg_1074_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter15_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter15_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten127_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten127_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten127_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten127_load <= indvar_flatten127_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten183_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten183_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten183_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten183_load <= indvar_flatten183_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_output_col_load_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln91_reg_1074_pp0_iter1_reg, add_ln95_reg_1145, ap_block_pp0_stage0, output_col_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln91_reg_1074_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_sig_allocacmp_output_col_load <= add_ln95_reg_1145;
        else 
            ap_sig_allocacmp_output_col_load <= output_col_fu_84;
        end if; 
    end process;

    bitcast_ln107_1_fu_777_p1 <= conv2_output_load_1_reg_1208_pp0_iter9_reg;
    bitcast_ln107_2_fu_794_p1 <= select_ln107_reg_1234_pp0_iter9_reg;
    bitcast_ln107_3_fu_864_p1 <= conv2_output_load_2_reg_1215_pp0_iter12_reg;
    bitcast_ln107_4_fu_881_p1 <= select_ln107_1_reg_1246_pp0_iter12_reg;
    bitcast_ln107_5_fu_951_p1 <= conv2_output_load_3_reg_1222_pp0_iter14_reg;
    bitcast_ln107_6_fu_968_p1 <= select_ln107_2_reg_1258_pp0_iter14_reg;
    bitcast_ln107_fu_730_p1 <= conv2_output_load_reg_1201_pp0_iter6_reg;
    conv2_output_address0 <= zext_ln106_3_fu_710_p1(11 - 1 downto 0);
    conv2_output_address1 <= zext_ln106_2_fu_699_p1(11 - 1 downto 0);
    conv2_output_address2 <= zext_ln106_1_fu_685_p1(11 - 1 downto 0);
    conv2_output_address3 <= zext_ln106_fu_674_p1(11 - 1 downto 0);

    conv2_output_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_output_ce0 <= ap_const_logic_1;
        else 
            conv2_output_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_output_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_output_ce1 <= ap_const_logic_1;
        else 
            conv2_output_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_output_ce2_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_output_ce2 <= ap_const_logic_1;
        else 
            conv2_output_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_output_ce3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_output_ce3 <= ap_const_logic_1;
        else 
            conv2_output_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    empty_29_fu_266_p2 <= std_logic_vector(shift_left(unsigned(channel_fu_96),to_integer(unsigned('0' & ap_const_lv5_1(5-1 downto 0)))));
    empty_30_fu_447_p2 <= std_logic_vector(unsigned(tmp3_cast_fu_444_p1) + unsigned(zext_ln93_fu_440_p1));
    empty_31_fu_456_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_453_p1) + unsigned(p_shl25_cast_fu_429_p1));
    empty_33_fu_465_p1 <= add_ln91_reg_1107(4 - 1 downto 0);
    empty_34_fu_320_p2 <= std_logic_vector(shift_left(unsigned(add_ln91_fu_304_p2),to_integer(unsigned('0' & ap_const_lv5_1(5-1 downto 0)))));
    empty_fu_262_p1 <= channel_fu_96(4 - 1 downto 0);
    grp_fu_1406_p_ce <= ap_const_logic_1;
    grp_fu_1406_p_din0 <= conv2_output_load_reg_1201;
    grp_fu_1406_p_din1 <= ap_const_lv32_0;
    grp_fu_1406_p_opcode <= ap_const_lv5_2;
    grp_fu_1410_p_ce <= ap_const_logic_1;
    grp_fu_1410_p_din0 <= conv2_output_load_1_reg_1208_pp0_iter7_reg;
    grp_fu_1410_p_din1 <= select_ln107_reg_1234;
    grp_fu_1410_p_opcode <= ap_const_lv5_2;
    grp_fu_1414_p_ce <= ap_const_logic_1;
    grp_fu_1414_p_din0 <= conv2_output_load_2_reg_1215_pp0_iter10_reg;
    grp_fu_1414_p_din1 <= select_ln107_1_reg_1246;
    grp_fu_1414_p_opcode <= ap_const_lv5_2;
    grp_fu_1418_p_ce <= ap_const_logic_1;
    grp_fu_1418_p_din0 <= conv2_output_load_3_reg_1222_pp0_iter13_reg;
    grp_fu_1418_p_din1 <= select_ln107_2_reg_1258;
    grp_fu_1418_p_opcode <= ap_const_lv5_2;
    icmp_ln107_10_fu_985_p2 <= "0" when (tmp_12_fu_954_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_11_fu_991_p2 <= "1" when (trunc_ln107_5_fu_964_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_12_fu_997_p2 <= "0" when (tmp_13_fu_971_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_13_fu_1003_p2 <= "1" when (trunc_ln107_6_fu_981_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_1_fu_753_p2 <= "1" when (trunc_ln107_fu_743_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_2_fu_811_p2 <= "0" when (tmp_6_fu_780_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_3_fu_817_p2 <= "1" when (trunc_ln107_1_fu_790_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_4_fu_829_p2 <= "0" when (tmp_7_fu_797_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_5_fu_835_p2 <= "1" when (trunc_ln107_2_fu_807_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_6_fu_898_p2 <= "0" when (tmp_9_fu_867_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_7_fu_904_p2 <= "1" when (trunc_ln107_3_fu_877_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_8_fu_916_p2 <= "0" when (tmp_10_fu_884_p4 = ap_const_lv8_FF) else "1";
    icmp_ln107_9_fu_922_p2 <= "1" when (trunc_ln107_4_fu_894_p1 = ap_const_lv23_0) else "0";
    icmp_ln107_fu_747_p2 <= "0" when (tmp_4_fu_733_p4 = ap_const_lv8_FF) else "1";
    icmp_ln91_fu_211_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten183_load = ap_const_lv9_190) else "0";
    icmp_ln93_fu_226_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten127_load = ap_const_lv6_19) else "0";
    icmp_ln95_fu_342_p2 <= "1" when (ap_sig_allocacmp_output_col_load = ap_const_lv3_5) else "0";
    or_ln105_1_fu_704_p2 <= (ap_const_lv11_1 or add_ln105_3_fu_693_p2);
    or_ln105_fu_679_p2 <= (ap_const_lv11_1 or add_ln105_1_fu_668_p2);
    or_ln107_1_fu_823_p2 <= (icmp_ln107_3_fu_817_p2 or icmp_ln107_2_fu_811_p2);
    or_ln107_2_fu_841_p2 <= (icmp_ln107_5_fu_835_p2 or icmp_ln107_4_fu_829_p2);
    or_ln107_3_fu_910_p2 <= (icmp_ln107_7_fu_904_p2 or icmp_ln107_6_fu_898_p2);
    or_ln107_4_fu_928_p2 <= (icmp_ln107_9_fu_922_p2 or icmp_ln107_8_fu_916_p2);
    or_ln107_5_fu_1009_p2 <= (icmp_ln107_11_reg_1270 or icmp_ln107_10_reg_1265);
    or_ln107_6_fu_1013_p2 <= (icmp_ln107_13_reg_1280 or icmp_ln107_12_reg_1275);
    or_ln107_fu_759_p2 <= (icmp_ln107_fu_747_p2 or icmp_ln107_1_fu_753_p2);
    or_ln93_1_fu_592_p2 <= (select_ln93_2_fu_577_p3 or ap_const_lv8_1);
    or_ln93_fu_367_p2 <= (icmp_ln93_reg_1078 or and_ln91_fu_348_p2);
    output_col_2_cast51_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln93_reg_1134_pp0_iter2_reg),7));
    p_cast38_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_280_p3),6));
    p_cast38_mid1_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid2_fu_380_p3),6));
    p_mid1121_fu_555_p2 <= std_logic_vector(unsigned(tmp3_cast_mid1_fu_551_p1) + unsigned(zext_ln91_3_fu_510_p1));
    p_mid1123_fu_571_p2 <= std_logic_vector(unsigned(tmp4_cast_mid1_fu_568_p1) + unsigned(zext_ln91_1_fu_487_p1));
    p_mid1149_fu_514_p2 <= std_logic_vector(unsigned(zext_ln91_fu_462_p1) + unsigned(zext_ln93_2_fu_499_p1));
    p_mid1159_fu_530_p2 <= std_logic_vector(unsigned(tmp4_cast_mid1157_fu_527_p1) + unsigned(p_shl25_cast_mid1_fu_476_p1));
    p_mid2_fu_380_p3 <= (add_ln93_fu_361_p2 & ap_const_lv1_0);
    p_shl1_fu_433_p3 <= (empty_reg_1091 & ap_const_lv2_0);
    p_shl24_mid1_fu_491_p3 <= (empty_33_fu_465_p1 & ap_const_lv2_0);
    p_shl25_cast_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_422_p3),8));
    p_shl25_cast_mid1_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl25_mid1_fu_468_p3),8));
    p_shl25_mid1_fu_468_p3 <= (empty_33_fu_465_p1 & ap_const_lv3_0);
    p_shl26_cast_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_29_fu_266_p2),6));
    p_shl27_mid2_fu_641_p3 <= (select_ln93_1_reg_1150 & ap_const_lv2_0);
    p_shl28_0_mid2_fu_648_p3 <= (select_ln93_2_reg_1156 & ap_const_lv3_0);
    p_shl28_1_mid2_fu_655_p3 <= (or_ln93_1_reg_1161 & ap_const_lv3_0);
    p_shl29_0_mid2_fu_584_p3 <= (select_ln93_2_fu_577_p3 & ap_const_lv1_0);
    p_shl_fu_422_p3 <= (empty_reg_1091 & ap_const_lv3_0);
    pool2_output_address0 <= zext_ln115_fu_1035_p1(9 - 1 downto 0);

    pool2_output_ce0_assign_proc : process(ap_enable_reg_pp0_iter16, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1))) then 
            pool2_output_ce0 <= ap_const_logic_1;
        else 
            pool2_output_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pool2_output_d0 <= 
        conv2_output_load_3_reg_1222_pp0_iter15_reg when (and_ln107_6_fu_1023_p2(0) = '1') else 
        select_ln107_2_reg_1258_pp0_iter15_reg;

    pool2_output_we0_assign_proc : process(ap_enable_reg_pp0_iter16, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1))) then 
            pool2_output_we0 <= ap_const_logic_1;
        else 
            pool2_output_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln107_1_fu_858_p3 <= 
        conv2_output_load_1_reg_1208_pp0_iter9_reg when (and_ln107_2_fu_853_p2(0) = '1') else 
        select_ln107_reg_1234_pp0_iter9_reg;
    select_ln107_2_fu_945_p3 <= 
        conv2_output_load_2_reg_1215_pp0_iter12_reg when (and_ln107_4_fu_940_p2(0) = '1') else 
        select_ln107_1_reg_1246_pp0_iter12_reg;
    select_ln107_fu_770_p3 <= 
        conv2_output_load_reg_1201_pp0_iter6_reg when (and_ln107_fu_765_p2(0) = '1') else 
        ap_const_lv32_0;
    select_ln91_1_fu_480_p3 <= 
        p_shl25_mid1_fu_468_p3 when (icmp_ln93_reg_1078_pp0_iter1_reg(0) = '1') else 
        p_shl_fu_422_p3;
    select_ln91_2_fu_326_p3 <= 
        empty_34_fu_320_p2 when (icmp_ln93_reg_1078(0) = '1') else 
        empty_29_fu_266_p2;
    select_ln91_3_fu_503_p3 <= 
        p_shl24_mid1_fu_491_p3 when (icmp_ln93_reg_1078_pp0_iter1_reg(0) = '1') else 
        p_shl1_fu_433_p3;
    select_ln91_4_fu_520_p3 <= 
        p_mid1149_fu_514_p2 when (icmp_ln93_reg_1078_pp0_iter1_reg(0) = '1') else 
        empty_30_fu_447_p2;
    select_ln91_5_fu_536_p3 <= 
        p_mid1159_fu_530_p2 when (icmp_ln93_reg_1078_pp0_iter1_reg(0) = '1') else 
        empty_31_fu_456_p2;
    select_ln91_6_fu_354_p3 <= 
        add_ln91_fu_304_p2 when (icmp_ln93_reg_1078(0) = '1') else 
        channel_fu_96;
    select_ln91_fu_313_p3 <= 
        ap_const_lv3_0 when (icmp_ln93_reg_1078(0) = '1') else 
        output_row_fu_88;
    select_ln93_1_fu_561_p3 <= 
        p_mid1121_fu_555_p2 when (and_ln91_reg_1118(0) = '1') else 
        select_ln91_4_fu_520_p3;
    select_ln93_2_fu_577_p3 <= 
        p_mid1123_fu_571_p2 when (and_ln91_reg_1118(0) = '1') else 
        select_ln91_5_fu_536_p3;
    select_ln93_3_fu_398_p3 <= 
        add_ln93_fu_361_p2 when (and_ln91_fu_348_p2(0) = '1') else 
        select_ln91_fu_313_p3;
    select_ln93_4_fu_238_p3 <= 
        ap_const_lv6_1 when (icmp_ln93_fu_226_p2(0) = '1') else 
        add_ln93_1_fu_232_p2;
    select_ln93_fu_372_p3 <= 
        ap_const_lv3_0 when (or_ln93_fu_367_p2(0) = '1') else 
        ap_sig_allocacmp_output_col_load;
    tmp3_cast_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_reg_1097),7));
    tmp3_cast_mid1_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_mid1_fu_546_p2),7));
    tmp3_fu_292_p2 <= std_logic_vector(unsigned(channel_fu_96) + unsigned(zext_ln93_1_fu_276_p1));
    tmp3_mid1_fu_546_p2 <= std_logic_vector(unsigned(select_ln91_6_reg_1124) + unsigned(zext_ln93_3_fu_543_p1));
    tmp4_cast_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_reg_1102),8));
    tmp4_cast_mid1157_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_34_reg_1113),8));
    tmp4_cast_mid1_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_mid1_reg_1140),8));
    tmp4_fu_298_p2 <= std_logic_vector(unsigned(p_shl26_cast_fu_272_p1) + unsigned(p_cast38_fu_288_p1));
    tmp4_mid1_fu_392_p2 <= std_logic_vector(unsigned(zext_ln91_2_fu_333_p1) + unsigned(p_cast38_mid1_fu_388_p1));
    tmp_10_fu_884_p4 <= bitcast_ln107_4_fu_881_p1(30 downto 23);
    tmp_12_fu_954_p4 <= bitcast_ln107_5_fu_951_p1(30 downto 23);
    tmp_13_fu_971_p4 <= bitcast_ln107_6_fu_968_p1(30 downto 23);
    tmp_3_fu_610_p3 <= (select_ln93_reg_1134 & ap_const_lv1_0);
    tmp_4_fu_733_p4 <= bitcast_ln107_fu_730_p1(30 downto 23);
    tmp_6_fu_780_p4 <= bitcast_ln107_1_fu_777_p1(30 downto 23);
    tmp_7_fu_797_p4 <= bitcast_ln107_2_fu_794_p1(30 downto 23);
    tmp_9_fu_867_p4 <= bitcast_ln107_3_fu_864_p1(30 downto 23);
    tmp_s_fu_280_p3 <= (output_row_fu_88 & ap_const_lv1_0);
    trunc_ln107_1_fu_790_p1 <= bitcast_ln107_1_fu_777_p1(23 - 1 downto 0);
    trunc_ln107_2_fu_807_p1 <= bitcast_ln107_2_fu_794_p1(23 - 1 downto 0);
    trunc_ln107_3_fu_877_p1 <= bitcast_ln107_3_fu_864_p1(23 - 1 downto 0);
    trunc_ln107_4_fu_894_p1 <= bitcast_ln107_4_fu_881_p1(23 - 1 downto 0);
    trunc_ln107_5_fu_964_p1 <= bitcast_ln107_5_fu_951_p1(23 - 1 downto 0);
    trunc_ln107_6_fu_981_p1 <= bitcast_ln107_6_fu_968_p1(23 - 1 downto 0);
    trunc_ln107_fu_743_p1 <= bitcast_ln107_fu_730_p1(23 - 1 downto 0);
    xor_ln91_fu_337_p2 <= (icmp_ln93_reg_1078 xor ap_const_lv1_1);
    zext_ln105_1_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_610_p3),9));
    zext_ln105_2_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_reg_1166),11));
    zext_ln105_3_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_2_reg_1171),11));
    zext_ln105_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_610_p3),10));
    zext_ln106_1_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln105_fu_679_p2),64));
    zext_ln106_2_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_3_fu_693_p2),64));
    zext_ln106_3_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln105_1_fu_704_p2),64));
    zext_ln106_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_1_fu_668_p2),64));
    zext_ln114_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln114_fu_715_p2),9));
    zext_ln115_fu_1035_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln114_1_reg_1196_pp0_iter15_reg),64));
    zext_ln91_1_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_1_fu_480_p3),8));
    zext_ln91_2_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_2_fu_326_p3),6));
    zext_ln91_3_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_3_fu_503_p3),7));
    zext_ln91_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln91_reg_1107),7));
    zext_ln93_1_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(output_row_fu_88),5));
    zext_ln93_2_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl24_mid1_fu_491_p3),7));
    zext_ln93_3_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_reg_1129),5));
    zext_ln93_4_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln95_mid2_v_fu_598_p3),10));
    zext_ln93_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_433_p3),7));
    zext_ln95_mid2_v_fu_598_p3 <= (or_ln93_1_fu_592_p2 & ap_const_lv1_0);
end behav;
