-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet_w8a8_top_lenet_w8a8_top_Pipeline_REQUANT_VECTOR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv3_acc_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv3_acc_V_ce0 : OUT STD_LOGIC;
    conv3_acc_V_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    conv3_relu_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv3_relu_V_ce0 : OUT STD_LOGIC;
    conv3_relu_V_we0 : OUT STD_LOGIC;
    conv3_relu_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    grp_fu_1112_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1112_p_din1 : OUT STD_LOGIC_VECTOR (32 downto 0);
    grp_fu_1112_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_1112_p_ce : OUT STD_LOGIC );
end;


architecture behav of lenet_w8a8_top_lenet_w8a8_top_Pipeline_REQUANT_VECTOR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_78 : STD_LOGIC_VECTOR (6 downto 0) := "1111000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv64_90E4F348 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000010010000111001001111001101001000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv40_8000000000 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_94_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_cast_fu_106_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_240 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_240_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_240_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_240_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_240_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal value_V_reg_250 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln1039_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_256 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_256_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln186_fu_124_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal product_V_reg_267 : STD_LOGIC_VECTOR (63 downto 0);
    signal ret_V_fu_134_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal ret_V_reg_272 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln1669_5_reg_278 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln1039_2_fu_221_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1039_2_reg_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_56 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln109_fu_100_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln186_fu_121_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1019_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1035_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln20_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal quotient_V_fu_160_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal quotient_V_2_fu_182_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_189_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln1035_2_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1039_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1039_fu_209_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln628_fu_205_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lenet_w8a8_top_mul_32ns_33ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component lenet_w8a8_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component lenet_w8a8_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_94_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_56 <= add_ln109_fu_100_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_56 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    i_cast_reg_240_pp0_iter1_reg(6 downto 0) <= i_cast_reg_240(6 downto 0);
                value_V_reg_250 <= conv3_acc_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                    i_cast_reg_240_pp0_iter2_reg(6 downto 0) <= i_cast_reg_240_pp0_iter1_reg(6 downto 0);
                    i_cast_reg_240_pp0_iter3_reg(6 downto 0) <= i_cast_reg_240_pp0_iter2_reg(6 downto 0);
                    i_cast_reg_240_pp0_iter4_reg(6 downto 0) <= i_cast_reg_240_pp0_iter3_reg(6 downto 0);
                icmp_ln1039_reg_256 <= icmp_ln1039_fu_116_p2;
                icmp_ln1039_reg_256_pp0_iter3_reg <= icmp_ln1039_reg_256;
                product_V_reg_267 <= grp_fu_1112_p_dout0;
                ret_V_reg_272 <= ret_V_fu_134_p1;
                select_ln1039_2_reg_284 <= select_ln1039_2_fu_221_p3;
                trunc_ln1669_5_reg_278 <= grp_fu_1112_p_dout0(63 downto 40);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln109_fu_94_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    i_cast_reg_240(6 downto 0) <= i_cast_fu_106_p1(6 downto 0);
            end if;
        end if;
    end process;
    i_cast_reg_240(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    i_cast_reg_240_pp0_iter1_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    i_cast_reg_240_pp0_iter2_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    i_cast_reg_240_pp0_iter3_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    i_cast_reg_240_pp0_iter4_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln109_fu_100_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv7_1));
    and_ln20_fu_170_p2 <= (p_Result_s_fu_148_p3 and icmp_ln1019_fu_165_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_94_p2)
    begin
        if (((icmp_ln109_fu_94_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_56;
        end if; 
    end process;

    conv3_acc_V_address0 <= i_cast_fu_106_p1(7 - 1 downto 0);

    conv3_acc_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv3_acc_V_ce0 <= ap_const_logic_1;
        else 
            conv3_acc_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv3_relu_V_address0 <= i_cast_reg_240_pp0_iter4_reg(7 - 1 downto 0);

    conv3_relu_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            conv3_relu_V_ce0 <= ap_const_logic_1;
        else 
            conv3_relu_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv3_relu_V_d0 <= select_ln1039_2_reg_284;

    conv3_relu_V_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            conv3_relu_V_we0 <= ap_const_logic_1;
        else 
            conv3_relu_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1112_p_ce <= ap_const_logic_1;
    grp_fu_1112_p_din0 <= zext_ln186_fu_124_p1(32 - 1 downto 0);
    grp_fu_1112_p_din1 <= ap_const_lv64_90E4F348(33 - 1 downto 0);
    i_cast_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),64));
    icmp_ln1019_fu_165_p2 <= "1" when (ret_V_reg_272 = ap_const_lv40_8000000000) else "0";
    icmp_ln1035_2_fu_199_p2 <= "0" when (tmp_fu_189_p4 = ap_const_lv17_0) else "1";
    icmp_ln1035_fu_155_p2 <= "1" when (unsigned(ret_V_reg_272) > unsigned(ap_const_lv40_8000000000)) else "0";
    icmp_ln1039_fu_116_p2 <= "1" when (signed(value_V_reg_250) < signed(ap_const_lv24_1)) else "0";
    icmp_ln109_fu_94_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv7_78) else "0";
    or_ln1039_fu_216_p2 <= (icmp_ln1039_reg_256_pp0_iter3_reg or icmp_ln1035_2_fu_199_p2);
    or_ln20_fu_176_p2 <= (icmp_ln1035_fu_155_p2 or and_ln20_fu_170_p2);
    p_Result_s_fu_148_p3 <= product_V_reg_267(40 downto 40);
    quotient_V_2_fu_182_p3 <= 
        quotient_V_fu_160_p2 when (or_ln20_fu_176_p2(0) = '1') else 
        trunc_ln1669_5_reg_278;
    quotient_V_fu_160_p2 <= std_logic_vector(unsigned(trunc_ln1669_5_reg_278) + unsigned(ap_const_lv24_1));
    ret_V_fu_134_p1 <= grp_fu_1112_p_dout0(40 - 1 downto 0);
    select_ln1039_2_fu_221_p3 <= 
        select_ln1039_fu_209_p3 when (or_ln1039_fu_216_p2(0) = '1') else 
        trunc_ln628_fu_205_p1;
    select_ln1039_fu_209_p3 <= 
        ap_const_lv8_0 when (icmp_ln1039_reg_256_pp0_iter3_reg(0) = '1') else 
        ap_const_lv8_7F;
        sext_ln186_fu_121_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(value_V_reg_250),32));

    tmp_fu_189_p4 <= quotient_V_2_fu_182_p3(23 downto 7);
    trunc_ln628_fu_205_p1 <= quotient_V_2_fu_182_p3(8 - 1 downto 0);
    zext_ln186_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln186_fu_121_p1),64));
end behav;
